using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Reflection;
using System.Web.Script.Serialization;

namespace AABattle {
 public class Potential { public string id, name, description, activation, uses; public string[] triggers; }
 public class Pokemon {
  public string id, team, name, ability, item;
  public int level; public string[] types, moves; public int[] @base, iv;
  public Potential[] potentials;
 }
 public class Move {
  public string name, category, effect, attack, defense, target; public string[] types, tags;
  public double power, accuracy; public int priority;
 }
 public class Database {
  public Pokemon[] pokemon; public Move[] moves; public string[] types;
  public Dictionary<string,Dictionary<string,double>> chart;
  public static Database Load() { var json=new JavaScriptSerializer {MaxJsonLength=10000000};var db=json.Deserialize<Database>(json.Serialize(Normalize(json.DeserializeObject(Resource.Text("data.json")))));MoveCatalog.Apply(db);MoveCatalog.Test(db);return db; }
  static object Normalize(object v){var d=v as Dictionary<string,object>;if(d!=null)return d.ToDictionary(p=>p.Key,p=>Normalize(p.Value));var a=v as object[];if(a!=null)return a.Select(Normalize).ToArray();if(v is decimal){decimal n=(decimal)v;if(n==decimal.Truncate(n)&&n>=int.MinValue&&n<=int.MaxValue)return (int)n;}return v;}
 }
 public static class Resource {
  public static byte[] Bytes(string name) { using(var s=Assembly.GetExecutingAssembly().GetManifestResourceStream(name)) { if(s==null)throw new Exception("Missing resource: "+name);using(var m=new MemoryStream()){s.CopyTo(m);return m.ToArray();} } }
  public static string Text(string name){return System.Text.Encoding.UTF8.GetString(Bytes(name));}
 }
 public class Fighter {
  public Pokemon Data; public string AA="", Status="정상",OriginalAbility="",CurrentAbility=""; public bool AbilityChanged,AbilitySuppressed,OnField=true;public int HP; public int[] Stages=new int[6]; public int AccuracyStage,EvasionStage,CriticalStage; public double AccuracyMultiplier=1,EvasionMultiplier=1; public double[] Multipliers={1,1,1,1,1,1};
  public string[] Moves; public int Selected; public ConditionState Conditions=new ConditionState();
  public Fighter(Pokemon p){Data=ClonePokemon(p);Moves=(p.moves??new string[0]).Take(4).ToArray();OriginalAbility=CurrentAbility=p.ability??"";HP=Engine.Stats(this,p.level,new Rules())[0];}
  public Fighter Copy(){var f=new Fighter(Data);f.AA=AA;f.Status=Status;f.OriginalAbility=OriginalAbility;f.CurrentAbility=CurrentAbility;f.AbilityChanged=AbilityChanged;f.AbilitySuppressed=AbilitySuppressed;f.OnField=OnField;f.HP=HP;f.Stages=(int[])Stages.Clone();f.AccuracyStage=AccuracyStage;f.EvasionStage=EvasionStage;f.CriticalStage=CriticalStage;f.AccuracyMultiplier=AccuracyMultiplier;f.EvasionMultiplier=EvasionMultiplier;f.Multipliers=(double[])Multipliers.Clone();f.Moves=(string[])Moves.Clone();f.Selected=Selected;f.Conditions=Conditions.Copy();return f;}
  static Pokemon ClonePokemon(Pokemon p){return new Pokemon{id=p.id,name=p.name,team=p.team,ability=p.ability,item=p.item,level=p.level,types=(string[])p.types.Clone(),@base=(int[])p.@base.Clone(),iv=(int[])p.iv.Clone(),moves=(string[])p.moves.Clone(),potentials=p.potentials};}
 }
 public class SideFieldState {public bool StealthRock,StickyWeb;public int Spikes,ToxicSpikes;public int Reflect,LightScreen,Tailwind;public SideFieldState Copy(){return (SideFieldState)MemberwiseClone();}public void ClearHazards(){StealthRock=StickyWeb=false;Spikes=ToxicSpikes=0;}public void Clear(){ClearHazards();Reflect=LightScreen=Tailwind=0;}public bool Any(){return StealthRock||StickyWeb||Spikes>0||ToxicSpikes>0||Reflect>0||LightScreen>0||Tailwind>0;}public bool HasHazards(){return StealthRock||StickyWeb||Spikes>0||ToxicSpikes>0;}}
 public class Rules {
  public string Weather="없음", Terrain="없음"; public bool Critical, HPCorrection;
  public double PowerBonus, PowerMultiplier=1, DamageMultiplier=1, Stab, LevelCorrection=1;public int SlightSpeciesBonus=10;
  public int WeatherTurns=5,TerrainTurns=5,TrickRoom,Gravity;public bool SheetTerrain;public SideFieldState[] Sides={new SideFieldState(),new SideFieldState()};public Rules Copy(){var copy=(Rules)MemberwiseClone();copy.Sides=(Sides??new[]{new SideFieldState(),new SideFieldState()}).Select(x=>(x??new SideFieldState()).Copy()).ToArray();return copy;}
 }
 public class Damage { public int Min,Max; public int[] Rolls;public double Stab,Type; public bool Supported;public string Reason=""; }
  // 포텐셜 전체 실행기는 단계적으로 확장 중이며, 교대 효과는 SwitchRuntime에서 실행한다.
 public enum BattleEvent { OnEnter,BeforeMove,BeforeDamage,AfterDamage,TurnEnd }
 public class TrainerBattleState {
  public TrainerRecord Trainer;
  public HashSet<string> UsedForms=new HashSet<string>(),UsedOrders=new HashSet<string>(),UsedPotentials=new HashSet<string>();
  public TrainerBattleState Copy(){var s=new TrainerBattleState{Trainer=Trainer};s.UsedForms=new HashSet<string>(UsedForms);s.UsedOrders=new HashSet<string>(UsedOrders);s.UsedPotentials=new HashSet<string>(UsedPotentials);return s;}
 }
 public class DelayedAttackState {
  public Move Move;
  public string SourceName="";
  public int SourceSide=-1,SourceLevel,SourceSpecialAttack,TurnsRemaining;
  public string[] SourceTypes=new string[0];
  public DelayedAttackState Copy(){return new DelayedAttackState{Move=Move==null?null:new Move{name=Move.name,category=Move.category,effect=Move.effect,attack=Move.attack,defense=Move.defense,types=(Move.types??new string[0]).ToArray(),tags=(Move.tags??new string[0]).ToArray(),power=Move.power,accuracy=Move.accuracy,priority=Move.priority},SourceName=SourceName,SourceSide=SourceSide,SourceLevel=SourceLevel,SourceSpecialAttack=SourceSpecialAttack,TurnsRemaining=TurnsRemaining,SourceTypes=(SourceTypes??new string[0]).ToArray()};}
 }
 public class BattleCommand {
  public Move Move;public Fighter SwitchIn;public TrainerRecord Trainer;public string Form="",Order="";public string[] PreInputs=new string[0];public Fighter[] Party=new Fighter[0];
  public bool IsSwitch{get{return SwitchIn!=null;}}
 }
  public class TurnResult { public Rules Rules; public Fighter[] Fighters;public Fighter[] SwitchedOut=new Fighter[2];public TrainerBattleState[] Trainers;public bool[] Switched=new bool[2];public List<SwitchRecord> Switches=new List<SwitchRecord>();public List<string> Log=new List<string>(); }
 public static class Engine {
  public static readonly string[] Names={"체력","공격","방어","특공","특방","속도"};
  public static int[] Stats(Fighter f,int other,Rules r){var p=f.Data;int low=Math.Min(p.level,other);double c=1+Math.Max(0,p.level-other)*r.LevelCorrection/100;return p.@base.Select((v,i)=>{int species=v+(i==0?PrivilegeRules.HpBonus(f,r):0);return i==0?(int)(r.HPCorrection?Math.Floor((Math.Floor((species*2+p.iv[i])*low/100.0)+10+low)*c):Math.Floor((species*2+p.iv[i])*p.level/100.0+10+p.level)):(int)Math.Floor((Math.Floor((species*2+p.iv[i])*low/100.0)+5)*c);}).ToArray();}
  public static double Stage(int n){return n>=0?(2+n)/2.0:2.0/(2-n);}
  public static int Effective(Fighter a,Fighter b,int i,Rules r,int role=0,int side=-1){return EffectiveAtLevel(a,b,b.Data.level,i,r,role,side);}
  public static int EffectiveAtLevel(Fighter a,Fighter environmentOpponent,int otherLevel,int i,Rules r,int role=0,int side=-1){int s=a.Stages[i];double m=a.Multipliers[i];if(r.Critical&&role==1){s=Math.Max(0,s);m=Math.Max(1,m);}if(r.Critical&&role==2){s=Math.Min(0,s);m=Math.Min(1,m);}return Math.Max(1,(int)Math.Floor(Stats(a,otherLevel,r)[i]*m*Stage(s)*Mechanics.StatFactor(a,environmentOpponent,i,r,side)));}
  public static double Match(Database db,string[] at,string[] dt){return at.Length==0?1:at.Max(t=>dt.Aggregate(1.0,(n,d)=>n*(db.chart.ContainsKey(d)&&db.chart[d].ContainsKey(t)?db.chart[d][t]:1)));}
  public static Damage Calculate(Database db,Fighter a,Fighter b,Move m,Rules r,int attackerSide=-1){
   Rules active=r;if(r.Critical&&AbilityRuntime.BlocksCritical(a,b)){active=r.Copy();active.Critical=false;}
   int ai=Math.Max(1,Array.IndexOf(Names,m.attack??(m.category=="물리"?"공격":"특공"))),di=Math.Max(1,Array.IndexOf(Names,m.defense??(m.category=="물리"?"방어":"특방")));
   double power=Math.Max(0,Math.Floor(m.power+active.PowerBonus)*active.PowerMultiplier);
   power*=Mechanics.PowerFactor(a,b,m,active)*AbilityRuntime.Power(a,m);
   double normalStab=active.Stab>0?active.Stab:m.types.Any(t=>a.Data.types.Contains(t))?1.5:1,stab=AbilityRuntime.Stab(a,normalStab),type=Mechanics.TypeEffect(db,a,b,m,active);
   string reason=Mechanics.Block(db,a,b,m,active);if(reason.Length>0)type=0;
   int defenderSide=attackerSide>=0&&attackerSide<2?1-attackerSide:-1;double basis=Math.Floor(((2*a.Data.level+10)/250.0*Effective(a,b,ai,active,1,attackerSide)/Effective(b,a,di,active,2,defenderSide)*power+2)*stab*type*(active.Critical?2:1)*active.DamageMultiplier*Mechanics.DamageFactor(a,b,m,active,defenderSide)*AbilityRuntime.Damage(a,b,active));
   bool supported=m.category!="변화"&&m.power>0;
   int[] rolls=Enumerable.Range(85,16).Select(v=>supported?(int)Math.Min(int.MaxValue,Math.Floor(basis*v/100)):0).ToArray();
   return new Damage{Min=rolls[0],Max=rolls[15],Rolls=rolls,Stab=stab,Type=type,Supported=supported,Reason=reason};
  }
  public static Damage CalculateDelayed(Database db,Fighter target,Fighter environmentOpponent,DelayedAttackState delayed,Rules r){
   var m=delayed.Move;int di=Math.Max(1,Array.IndexOf(Names,m.defense??"특방"));
   double power=Math.Max(0,Math.Floor(m.power));
   var source=Mechanics.DelayedSource(delayed);
   double stab=(delayed.SourceTypes??new string[0]).Any(t=>(m.types??new string[0]).Contains(t))?1.5:1;
   double type=Mechanics.TypeEffect(db,source,target,m,r);
   int defense=EffectiveAtLevel(target,environmentOpponent,delayed.SourceLevel,di,r,2);
   double basis=Math.Floor(((2*delayed.SourceLevel+10)/250.0*delayed.SourceSpecialAttack/defense*power+2)*stab*type*Mechanics.DelayedDamageFactor(target,m));
   bool supported=m.category!="변화"&&m.power>0;
   int[] rolls=Enumerable.Range(85,16).Select(v=>supported?(int)Math.Min(int.MaxValue,Math.Floor(basis*v/100)):0).ToArray();
   return new Damage{Min=rolls[0],Max=rolls[15],Rolls=rolls,Stab=stab,Type=type,Supported=supported};
  }
  public static TurnResult Resolve(Database db,Fighter[] input,Move[] moves,Rules original,Func<double> rng){
   var commands=moves.Select(m=>new BattleCommand{Move=m}).ToArray();return Resolve(db,input,commands,original,new[]{new TrainerBattleState(),new TrainerBattleState()},rng,null);
  }
  public static TurnResult Resolve(Database db,Fighter[] input,BattleCommand[] commands,Rules original,TrainerBattleState[] trainerInput,Func<double> rng){
   return Resolve(db,input,commands,original,trainerInput,rng,null);
  }
  public static TurnResult Resolve(Database db,Fighter[] input,BattleCommand[] commands,Rules original,TrainerBattleState[] trainerInput,Func<double> rng,Func<SwitchRequest,Fighter> chooseSwitch){
   if(input==null||input.Length!=2||commands==null||commands.Length!=2)throw new Exception("양쪽 행동을 모두 선택하세요.");
   var states=(trainerInput??new[]{new TrainerBattleState(),new TrainerBattleState()}).Select(x=>(x??new TrainerBattleState()).Copy()).ToArray();
   var result=new TurnResult{Fighters=input.Select(p=>p.Copy()).ToArray(),Rules=original.Copy(),Trainers=states};var f=result.Fighters;var r=result.Rules;int[] deployed={-1,-1};bool[] returnAway={false,false};for(int i=0;i<2;i++)f[i].OnField=true;
   AbilityRuntime.RefreshSuppression(f,result.Log.Add);EnterAbilities(f,r,rng,i=>!f[i].Conditions.AbilityEntryApplied,result.Log);
   for(int i=0;i<2;i++){
    var c=commands[i]??new BattleCommand();string form=c.Form??"",order=c.Order??"";
    if(c.IsSwitch&&form.Length>0&&!form.Contains("돌아와"))throw new Exception("교대 행동에는 『돌아와!』만 함께 선언할 수 있습니다.");
    if(!c.IsSwitch&&form.Contains("돌아와"))throw new Exception("『돌아와!』는 교대 행동과 함께 선언하세요.");
    if(c.IsSwitch&&order.Length>0)throw new Exception("지령은 기술 선택과 함께 선언하세요.");
    if(!c.IsSwitch&&c.Move==null)throw new Exception("기술 또는 교대 행동을 선택하세요.");
    if(form.Length>0){if(states[i].UsedForms.Contains(form))throw new Exception(form+"은 이미 사용했습니다.");states[i].UsedForms.Add(form);result.Log.Add("TRAINER "+(i+1)+" — 『"+form+"』 선언!");}
    if(order.Length>0){if(states[i].UsedOrders.Contains(order))throw new Exception(order+"은 이미 사용했습니다.");states[i].UsedOrders.Add(order);result.Log.Add("TRAINER "+(i+1)+" — 『"+order+"』 지령!");deployed[i]=ApplyOrder(f[i],f[1-i],order,r,result.Log);if(deployed[i]==-2)c.Move=null;}
    foreach(string potential in c.PreInputs??new string[0]){var definition=(f[i].Data.potentials??new Potential[0]).FirstOrDefault(x=>x!=null&&x.name==potential);bool limited=definition!=null&&(definition.uses??"").Contains("1/");if(limited&&states[i].UsedPotentials.Contains(potential))throw new Exception("『"+potential+"』은 이미 사용했습니다.");if(limited)states[i].UsedPotentials.Add(potential);result.Log.Add(f[i].Data.name+" — 선행입력 『"+potential+"』 선언!"+((definition==null?"":definition.description)??""));}
    if(order.Length>0){RuntimeTriggers.DirectiveReceived(f[i],(c.Party??new Fighter[0]).Where(x=>x!=null&&x.Data.name!=f[i].Data.name).Concat(new[]{f[i]}),order,result.Log.Add);TrainerTriggers.Fire(states[i].Trainer,TriggerStructures.AllyOrderLabel,order,result.Log.Add);}
   }
    AnsweredTriggers.Selected(f,commands,result.Log.Add);int entryStart=result.Log.Count;
    for(int i=0;i<2;i++)if(commands[i].IsSwitch&&(commands[i].Form??"").Contains("돌아와")){Fighter outgoing=f[i].Copy();RuntimeTriggers.Switch(f[i],SwitchReason.Return,result.Log.Add);AbilityRuntime.Leave(f[i],f[1-i],r,SwitchReason.Return,result.Log);f[i].OnField=false;result.SwitchedOut[i]=outgoing;returnAway[i]=true;result.Log.Add("『돌아와!』 — "+f[i].Data.name+"을 먼저 볼로 되돌렸다!");}
   AbilityRuntime.RefreshSuppression(f,result.Log.Add);
     for(int i=0;i<2;i++)if(commands[i].IsSwitch&&!((commands[i].Form??"").Contains("돌아와"))){Fighter outgoing=f[i].Copy();RuntimeTriggers.Switch(f[i],SwitchReason.Normal,result.Log.Add);AbilityRuntime.Leave(f[i],f[1-i],r,SwitchReason.Normal,result.Log);f[i].OnField=false;result.SwitchedOut[i]=outgoing;f[i]=commands[i].SwitchIn.Copy();f[i].OnField=true;result.Fighters=f;result.Switched[i]=true;result.Switches.Add(new SwitchRecord{Side=i,Timing=SwitchTiming.MidTurn,Reason=SwitchReason.Normal,Source="통상 교대",Outgoing=outgoing,Incoming=f[i].Copy()});Mechanics.EnterField(db,f[i],f[1-i],i,r,rng,result.Log);EntryTriggers.Enter(f[i],EntryReason.NormalSwitch,result.Log.Add);RuntimeTriggers.OpponentEntered(f[1-i],f[i],result.Log.Add);result.Log.Add("TRAINER "+(i+1)+"의 통상 교대 — "+f[i].Data.name+" 등장!");}
   AbilityRuntime.RefreshSuppression(f,result.Log.Add);EnterAbilities(f,r,rng,i=>result.Switched[i]&&!((commands[i].Form??"").Contains("돌아와")),result.Log);
    for(int i=0;i<2;i++)if(result.Switched[i]){TrainerTriggers.Fire(states[i].Trainer,TriggerStructures.EntryLabel,f[i].Data.name+"이 장소에 나옴",result.Log.Add,f[i]);TrainerTriggers.Fire(states[1-i].Trainer,TriggerStructures.OpponentEntryLabel,f[i].Data.name+"이 상대 장소에 나옴",result.Log.Add,f[1-i]);}ResolveTriggeredSwitches(db,f,commands,states,r,rng,result,entryStart,SwitchTiming.MidTurn,chooseSwitch);var movers=Enumerable.Range(0,2).Where(i=>!commands[i].IsSwitch&&commands[i].Move!=null).ToArray();
   PriorityEffectRuntime.PrimeTurn(f,commands,states,result.Log.Add);if(movers.Length==2){int delta=Mechanics.Priority(f[0],commands[0].Move,f[1],states[0].Trainer,states[1].Trainer).CompareTo(Mechanics.Priority(f[1],commands[1].Move,f[0],states[1].Trainer,states[0].Trainer));if(delta==0){delta=Effective(f[0],f[1],5,r,0,0).CompareTo(Effective(f[1],f[0],5,r,0,1));if(r.TrickRoom>0)delta=-delta;}int first=delta>0?0:delta<0?1:rng()<.5?0:1;movers=new[]{first,1-first};}
    foreach(int i in movers){AbilityRuntime.RefreshSuppression(f,result.Log.Add);var a=f[i];var b=f[1-i];var m=commands[i].Move;int actionStart=result.Log.Count;if(a.HP<=0)continue;
     if(!Mechanics.BeforeMove(a,b,m,r,rng,result.Log)){ResolveTriggeredSwitches(db,f,commands,states,r,rng,result,actionStart,SwitchTiming.MidTurn,chooseSwitch);continue;}
      RuntimeTriggers.BeforeMove(a,m,result.Log.Add);TrainerTriggers.BeforeMove(states[i].Trainer,m,result.Log.Add);
      bool pivotGrant=SwitchEffectRuntime.TriggeredPivotGrant(a,result.Log.Skip(actionStart))||SwitchEffectRuntime.TriggeredPivotGrant(states[i].Trainer,result.Log.Skip(actionStart));
     if(m.name!="방어"&&m.name!="판별")a.Conditions.ProtectChain=0;
     bool target=Mechanics.TargetsOpponent(m);string defendingForm=commands[1-i].Form??"";
     if(target&&!b.OnField){result.Log.Add(a.Data.name+"의 "+m.name+" — 상대가 볼 안에 있어 실패했다.");ResolveTriggeredSwitches(db,f,commands,states,r,rng,result,actionStart,SwitchTiming.MidTurn,chooseSwitch);continue;}
     if(Mechanics.IsDelayedMove(m)){Mechanics.ScheduleDelayedMove(a,b,m,r,i,result.Log);ResolveTriggeredSwitches(db,f,commands,states,r,rng,result,actionStart,SwitchTiming.MidTurn,chooseSwitch);continue;}
     if(target&&((defendingForm.Contains("물러나")&&m.category=="물리")||(defendingForm.Contains("피해라")&&m.category=="특수"))){result.Log.Add(b.Data.name+"은 『"+defendingForm+"』로 공격을 회피했다!");ResolveTriggeredSwitches(db,f,commands,states,r,rng,result,actionStart,SwitchTiming.MidTurn,chooseSwitch);continue;}
    string reason=target?Mechanics.Block(db,a,b,m,r):"";
     if(reason.Length>0){result.Log.Add(a.Data.name+"의 "+m.name+" — "+reason);Mechanics.Absorb(a,b,reason,r,result.Log);RuntimeTriggers.Nullified(b,a,m,reason,result.Log.Add);AnsweredTriggers.DefensiveBlocked(b,a,m,reason,result.Log.Add);ResolveTriggeredSwitches(db,f,commands,states,r,rng,result,actionStart,SwitchTiming.MidTurn,chooseSwitch);continue;}
     if(target&&b.Conditions.Substitute>0&&m.category=="변화"&&!Mechanics.BypassSub(a,m)){result.Log.Add("대타가 "+m.name+"을 막았다.");ResolveTriggeredSwitches(db,f,commands,states,r,rng,result,actionStart,SwitchTiming.MidTurn,chooseSwitch);continue;}
     bool sureHit=(commands[i].Form??"").Contains("맞춰라");if(!sureHit&&rng()*100>=Mechanics.Accuracy(a,b,m,r)){result.Log.Add(a.Data.name+"의 "+m.name+"! 그러나 빗나갔다!");ResolveTriggeredSwitches(db,f,commands,states,r,rng,result,actionStart,SwitchTiming.MidTurn,chooseSwitch);continue;}
     if(m.category=="변화"){Mechanics.StatusMove(a,b,m,r,rng,result.Log,i);ResolveTriggeredSwitches(db,f,commands,states,r,rng,result,actionStart,SwitchTiming.MidTurn,chooseSwitch);if(f[i]==a&&a.HP>0&&(SwitchEffectRuntime.IsPivotMove(m)||pivotGrant))RequestSwitch(db,f,commands,states,r,rng,result,i,SwitchReason.Pivot,SwitchTiming.MidTurn,m.name,chooseSwitch);continue;}
     var d=Calculate(db,a,b,m,r,i);if(!d.Supported){result.Log.Add(m.name+": 가변 위력 — 수동 판정.");ResolveTriggeredSwitches(db,f,commands,states,r,rng,result,actionStart,SwitchTiming.MidTurn,chooseSwitch);continue;}
    int damage=d.Rolls[Math.Min(15,(int)(rng()*16))],bodyDamage=0;bool sub=b.Conditions.Substitute>0&&!Mechanics.BypassSub(a,m);
    if(sub){b.Conditions.Substitute=Math.Max(0,b.Conditions.Substitute-damage);result.Log.Add(m.name+": 대타에 "+damage+" 대미지. 남은 대타 HP "+b.Conditions.Substitute);}
    else{int hpBefore=b.HP;if(defendingForm.Contains("버텨라")){damage=(int)Math.Floor(damage/2.0);if(damage>=b.HP)damage=Math.Max(0,b.HP-1);result.Log.Add(b.Data.name+"은 『"+defendingForm+"』로 대미지를 반감하고 버텼다!");}else if(damage>=b.HP&&AbilityRuntime.Endures(a,b,r)){damage=Math.Max(0,b.HP-1);result.Log.Add(b.Data.name+"은 「"+AbilityRuntime.Name(b)+"」으로 HP 1을 남겼다!");AnsweredTriggers.AbilityActivated(b,AbilityRuntime.Name(b),result.Log.Add);}b.HP=Math.Max(0,b.HP-damage);bodyDamage=hpBefore-b.HP;result.Log.Add(a.Data.name+"의 "+m.name+"! "+b.Data.name+"에게 "+damage+" 대미지."+((r.Critical&&!AbilityRuntime.BlocksCritical(a,b))?" 급소!":"")+(d.Type>1?" 효과가 굉장했다!":d.Type<1?" 효과가 별로다.":""));RuntimeTriggers.Damaged(b,bodyDamage,a.Data.name+"의 "+m.name,result.Log.Add);AnsweredTriggers.HpChanged(b,a,r,hpBefore,b.HP,a.Data.name+"의 "+m.name,result.Log.Add);if(b.HP==0){result.Log.Add(b.Data.name+"은 쓰러졌다!");DefeatTriggers.ByMove(a,b,m,hpBefore,damage,result.Log.Add);}}
    if(damage>0)Mechanics.AfterHit(a,b,m,r,rng,result.Log,sub,i);
    RuntimeTriggers.Received(b,a,m,bodyDamage,result.Log.Add);
    RuntimeTriggers.AttackSucceeded(a,b,m,result.Log.Add);
    AnsweredTriggers.AttackHit(a,b,m,sub,r.Critical&&!AbilityRuntime.BlocksCritical(a,b),result.Log.Add);
     if(bodyDamage>0)TrainerTriggers.Fire(states[1-i].Trainer,TriggerStructures.DamagedLabel,a.Data.name+"의 "+m.name+"으로 "+bodyDamage+" 대미지",result.Log.Add);if(b.HP==0)TrainerTriggers.Fire(states[i].Trainer,TriggerStructures.DefeatLabel,b.Data.name+"을 직접 쓰러뜨림",result.Log.Add);TrainerTriggers.Fire(states[i].Trainer,TriggerStructures.AttackSuccessLabel,m.name+" 공격 성공",result.Log.Add);AbilityRuntime.RefreshSuppression(f,result.Log.Add);
     ResolveTriggeredSwitches(db,f,commands,states,r,rng,result,actionStart,SwitchTiming.MidTurn,chooseSwitch);
     if(f[i]==a&&a.HP>0&&(SwitchEffectRuntime.IsPivotMove(m)||pivotGrant))RequestSwitch(db,f,commands,states,r,rng,result,i,SwitchReason.Pivot,SwitchTiming.MidTurn,m.name,chooseSwitch);
    }
    for(int i=0;i<2;i++)if(returnAway[i]){f[i]=commands[i].SwitchIn.Copy();f[i].OnField=true;result.Fighters=f;result.Switched[i]=true;result.Switches.Add(new SwitchRecord{Side=i,Timing=SwitchTiming.TurnEnd,Reason=SwitchReason.Return,Source="『돌아와!』",Outgoing=result.SwitchedOut[i],Incoming=f[i].Copy()});Mechanics.EnterField(db,f[i],f[1-i],i,r,rng,result.Log);EntryTriggers.Enter(f[i],EntryReason.Return,result.Log.Add);RuntimeTriggers.OpponentEntered(f[1-i],f[i],result.Log.Add);TrainerTriggers.Fire(states[i].Trainer,TriggerStructures.EntryLabel,f[i].Data.name+"이 장소에 나옴",result.Log.Add,f[i]);TrainerTriggers.Fire(states[1-i].Trainer,TriggerStructures.OpponentEntryLabel,f[i].Data.name+"이 상대 장소에 나옴",result.Log.Add,f[1-i]);result.Log.Add("『돌아와!』 — 턴 마지막 교대 시점에 "+f[i].Data.name+" 등장!");}
   AbilityRuntime.RefreshSuppression(f,result.Log.Add);EnterAbilities(f,r,rng,i=>result.Switched[i]&&(commands[i].Form??"").Contains("돌아와"),result.Log);
    int turnEndStart=result.Log.Count;Mechanics.EndTurn(f,r,result.Log,rng);foreach(int i in Mechanics.SpeedOrder(f,r,rng))AbilityRuntime.EndTurn(f[i],f[1-i],r,result.Log);for(int i=0;i<2;i++)if(!result.Switched[i]){if(deployed[i]>=0)f[i].Multipliers[deployed[i]]/=2;else if(deployed[i]==-3)f[i].AccuracyMultiplier/=2;else if(deployed[i]==-4)f[i].EvasionMultiplier/=2;}RuntimeTriggers.TurnEnd(f,r,rng,result.Log.Add);for(int i=0;i<2;i++)TrainerTriggers.Fire(states[i].Trainer,TriggerStructures.TurnEndLabel,"턴 종료",result.Log.Add);ResolveTriggeredSwitches(db,f,commands,states,r,rng,result,turnEndStart,SwitchTiming.TurnEnd,chooseSwitch);int delayedStart=result.Log.Count;Mechanics.ResolveDelayedMoves(db,f,r,rng,result.Log,(side,attack,damage,defeated)=>{if(damage>0)TrainerTriggers.Fire(states[1-side].Trainer,TriggerStructures.DamagedLabel,attack.SourceName+"의 "+attack.Move.name+"으로 "+damage+" 대미지",result.Log.Add);});ResolveTriggeredSwitches(db,f,commands,states,r,rng,result,delayedStart,SwitchTiming.TurnEnd,chooseSwitch);return result;
   }
   static void ResolveTriggeredSwitches(Database db,Fighter[] fighters,BattleCommand[] commands,TrainerBattleState[] states,Rules rules,Func<double> rng,TurnResult result,int logStart,SwitchTiming timing,Func<SwitchRequest,Fighter> chooseSwitch){var lines=result.Log.Skip(Math.Max(0,logStart)).ToArray();for(int side=0;side<2;side++){Fighter owner=fighters[side];if(owner==null||owner.HP<=0||!owner.OnField)continue;BattleCommand command=commands[side]??new BattleCommand();foreach(var potential in SwitchEffectRuntime.TriggeredSwitches(owner,lines)){bool limited=SwitchEffectRuntime.Limited(potential),declared=(command.PreInputs??new string[0]).Contains(potential.name);if(limited&&states[side].UsedPotentials.Contains(potential.name)&&!declared)continue;string source="『"+potential.name+"』";if(RequestSwitch(db,fighters,commands,states,rules,rng,result,side,SwitchReason.Potential,timing,source,chooseSwitch)){if(limited)states[side].UsedPotentials.Add(potential.name);break;}}if(fighters[side]!=owner||fighters[side].HP<=0||!fighters[side].OnField)continue;foreach(var potential in SwitchEffectRuntime.TriggeredTrainerSwitches(states[side].Trainer,lines)){bool limited=(potential.uses??"").Contains("1/");if(limited&&states[side].UsedPotentials.Contains(potential.name))continue;string source="TRAINER 『"+potential.name+"』";if(RequestSwitch(db,fighters,commands,states,rules,rng,result,side,SwitchReason.Potential,timing,source,chooseSwitch)){if(limited)states[side].UsedPotentials.Add(potential.name);break;}}}}
   static Fighter[] SwitchCandidates(Fighter current,BattleCommand command){var seen=new HashSet<string>();return (command==null?new Fighter[0]:(command.Party??new Fighter[0])).Where(x=>x!=null&&x.Data!=null&&x.HP>0&&current!=null&&x.Data.name!=current.Data.name&&seen.Add(x.Data.name)).Select(x=>x.Copy()).ToArray();}
   static bool RequestSwitch(Database db,Fighter[] fighters,BattleCommand[] commands,TrainerBattleState[] states,Rules rules,Func<double> rng,TurnResult result,int side,SwitchReason reason,SwitchTiming timing,string source,Func<SwitchRequest,Fighter> chooseSwitch){if(side<0||side>1||fighters[side]==null||fighters[side].HP<=0||!fighters[side].OnField)return false;var candidates=SwitchCandidates(fighters[side],commands[side]);if(candidates.Length==0){result.Log.Add(fighters[side].Data.name+"의 "+source+" — 교대할 수 있는 아군이 없다.");return false;}var request=new SwitchRequest{Side=side,Timing=timing,Source=source,Outgoing=fighters[side].Copy(),Candidates=candidates};Fighter selected=chooseSwitch==null?null:chooseSwitch(request);if(selected==null){result.Log.Add(fighters[side].Data.name+"의 "+source+" — 교대를 취소했다.");return false;}var incoming=candidates.FirstOrDefault(x=>x.Data.name==selected.Data.name);if(incoming==null){result.Log.Add(fighters[side].Data.name+"의 "+source+" — 교대 대상이 유효하지 않아 취소했다.");return false;}SwitchNow(db,fighters,states,rules,rng,result,side,incoming,reason,timing,source);return true;}
   static void SwitchNow(Database db,Fighter[] fighters,TrainerBattleState[] states,Rules rules,Func<double> rng,TurnResult result,int side,Fighter incoming,SwitchReason reason,SwitchTiming timing,string source){Fighter outgoing=fighters[side].Copy();RuntimeTriggers.Switch(fighters[side],reason,result.Log.Add);AbilityRuntime.Leave(fighters[side],fighters[1-side],rules,reason,result.Log);fighters[side].OnField=false;result.SwitchedOut[side]=outgoing;fighters[side]=incoming.Copy();fighters[side].OnField=true;result.Fighters=fighters;result.Switched[side]=true;result.Switches.Add(new SwitchRecord{Side=side,Timing=timing,Reason=reason,Source=source,Outgoing=outgoing,Incoming=fighters[side].Copy()});Mechanics.EnterField(db,fighters[side],fighters[1-side],side,rules,rng,result.Log);EntryTriggers.Enter(fighters[side],reason==SwitchReason.Pivot?EntryReason.Pivot:EntryReason.Potential,result.Log.Add);RuntimeTriggers.OpponentEntered(fighters[1-side],fighters[side],result.Log.Add);TrainerTriggers.Fire(states[side].Trainer,TriggerStructures.EntryLabel,fighters[side].Data.name+"이 장소에 나옴",result.Log.Add,fighters[side]);TrainerTriggers.Fire(states[1-side].Trainer,TriggerStructures.OpponentEntryLabel,fighters[side].Data.name+"이 상대 장소에 나옴",result.Log.Add,fighters[1-side]);AbilityRuntime.RefreshSuppression(fighters,result.Log.Add);AbilityRuntime.Enter(fighters[side],fighters[1-side],rules,result.Log.Add);result.Log.Add(source+" — "+(timing==SwitchTiming.TurnEnd?"턴 마지막":"턴 중간")+"에 "+fighters[side].Data.name+" 등장!");}
   static void EnterAbilities(Fighter[] fighters,Rules rules,Func<double> rng,Func<int,bool> include,List<string> log){var sides=Enumerable.Range(0,2).Where(include).ToArray();if(sides.Length==2)sides=Mechanics.SpeedOrder(fighters,rules,rng);foreach(int side in sides)AbilityRuntime.Enter(fighters[side],fighters[1-side],rules,log.Add);}
  static int ApplyOrder(Fighter a,Fighter b,string order,Rules r,List<string> log){
   bool deploy=order.Contains("전개");if(order.Contains("회복")){int max=Stats(a,b.Data.level,r)[0],amount=Math.Max(1,max/(deploy?2:4));int before=a.HP;a.HP=Math.Min(max,a.HP+amount);int gain=a.HP-before;log.Add(a.Data.name+"의 HP가 "+gain+" 회복됐다."+(deploy?" 행동은 생략된다.":""));AnsweredTriggers.Healed(a,gain,order,log.Add);return deploy?-2:-1;}
   if(order.Contains("저격")||order.Contains("명중")){if(deploy){a.AccuracyMultiplier*=2;log.Add(a.Data.name+": 명중 2배(이번 턴)");return -3;}int before=a.AccuracyStage;a.AccuracyStage=Math.Min(6,a.AccuracyStage+1);AnsweredTriggers.StageChanged(a,b,6,before,a.AccuracyStage,log.Add);log.Add(a.Data.name+": 명중 +1");return -1;}
   if(order.Contains("회피")){if(deploy){a.EvasionMultiplier*=2;log.Add(a.Data.name+": 회피 2배(이번 턴)");return -4;}int before=a.EvasionStage;a.EvasionStage=Math.Min(6,a.EvasionStage+1);AnsweredTriggers.StageChanged(a,b,7,before,a.EvasionStage,log.Add);log.Add(a.Data.name+": 회피 +1");return -1;}
   string[] labels={"공격","방어","특공","특방","민첩","속도"};int[] indexes={1,2,3,4,5,5};int at=Array.FindIndex(labels,x=>order.Contains(x));if(at<0)return -1;int stat=indexes[at];if(deploy){a.Multipliers[stat]*=2;log.Add(a.Data.name+": "+Names[stat]+" 2배(이번 턴)");return stat;}Mechanics.ChangeStage(a,b,stat,1,r,order,log);return -1;
  }
  static Fighter TriggerFighter(Fighter source,string name,string potential,string trigger){var p=source.Data;return new Fighter(new Pokemon{id="trigger-test",name=name,level=p.level,@base=(int[])p.@base.Clone(),iv=(int[])p.iv.Clone(),types=(string[])p.types.Clone(),moves=(string[])p.moves.Clone(),potentials=new[]{new Potential{name=potential,description="공격이 오른다.",triggers=new[]{trigger}}}});}
  public static string Test(Database db){
   CatalogTests.Run();SwitchRuntimeTests.Run(db);
   var a=new Fighter(db.pokemon.First(p=>p.name=="선데이"));var b=new Fighter(db.pokemon.First(p=>p.name=="잭 한마"));var m=db.moves.First(v=>v.name=="파괴광선");var r=new Rules();b.Stages[4]=1;
   BattleStateReport.Test(db);
   Check(Stats(a,b.Data.level,r)[0]==598,"HP");Check(Effective(a,b,1,r)==269,"level correction");var d=Calculate(db,a,b,m,r);Check(d.Min==290&&d.Max==342&&d.Rolls[2]==297,"spreadsheet damage");
   Check(Match(db,new[]{"노말"},new[]{"고스트"})==0,"immunity");Check(Match(db,new[]{"물"},new[]{"불꽃","땅","바위"})==8,"triple types");
   var ko=b.Copy();ko.HP=1;var fast=new Move{name=m.name,category=m.category,types=m.types,power=m.power,accuracy=100,priority=7,attack=m.attack,defense=m.defense};var t=Resolve(db,new[]{a,ko},new[]{fast,m},r,()=>0);Check(t.Fighters[1].HP==0&&t.Fighters[0].HP==a.HP&&ko.HP==1,"KO order and input isolation");
   var hunter=new Fighter(new Pokemon{id="trigger-test",name="사냥꾼",level=a.Data.level,@base=(int[])a.Data.@base.Clone(),iv=(int[])a.Data.iv.Clone(),types=(string[])a.Data.types.Clone(),moves=(string[])a.Data.moves.Clone(),potentials=new[]{new Potential{name="승전",description="공격이 오른다.",triggers=new[]{DefeatTriggers.Label}}}});ko=b.Copy();ko.HP=1;var directKo=Resolve(db,new[]{hunter,ko},new[]{fast,m},new Rules(),()=>0);Check(directKo.Log.Any(x=>x.Contains("『승전』")&&x.Contains(DefeatTriggers.Label)),"direct move defeat trigger");var poisoned=b.Copy();poisoned.HP=1;poisoned.Status="독";var protect=db.moves.First(v=>v.name=="방어");var indirectKo=Resolve(db,new[]{hunter,poisoned},new[]{protect,protect},new Rules(),()=>0);Check(indirectKo.Fighters[1].HP==0&&!indirectKo.Log.Any(x=>x.Contains("『승전』")),"indirect damage does not trigger defeat");
   var tap=new Move{name="약한공격",category=m.category,types=m.types,power=1,accuracy=100,priority=7,attack=m.attack,defense=m.defense};var receiver=TriggerFighter(b,"수신자","반격",TriggerStructures.ReceivedLabel);var received=Resolve(db,new[]{a,receiver},new[]{tap,protect},new Rules(),()=>0);Check(received.Log.Any(x=>x.Contains("『반격』")&&x.Contains(TriggerStructures.ReceivedLabel)),"received once after move");var switcher=TriggerFighter(a,"교대자","선회",TriggerStructures.SwitchLabel);var reserveForTest=new Fighter(db.pokemon.First(p=>p.name=="원시 가이오가"));var switched=Resolve(db,new[]{switcher,b},new[]{new BattleCommand{SwitchIn=reserveForTest},new BattleCommand{Move=protect}},new Rules(),new[]{new TrainerBattleState(),new TrainerBattleState()},()=>0);Check(switched.Log.Any(x=>x.Contains("『선회』")&&x.Contains(TriggerStructures.SwitchLabel)),"voluntary switch trigger");var entryTrainer=new TrainerRecord{potentials=new List<PotentialRecord>{new PotentialRecord{slot="고유",name="대면 강화",trigger=TriggerStructures.OpponentEntryLabel,effect="자신의 공격이 오른다."}}};var entryState=new[]{new TrainerBattleState{Trainer=entryTrainer},new TrainerBattleState()};var opponentSwitch=Resolve(db,new[]{a,b},new[]{new BattleCommand{Move=protect},new BattleCommand{SwitchIn=reserveForTest}},new Rules(),entryState,()=>0);Check(opponentSwitch.Fighters[0].Stages[1]==1&&opponentSwitch.Log.Any(x=>x.Contains("『대면 강화』")),"trainer unique opponent entry affects allied active pokemon");var ender=TriggerFighter(a,"종료자","윤회",TriggerStructures.TurnEndLabel);ender.Status="독";var ended=Resolve(db,new[]{ender,b},new[]{protect,protect},new Rules(),()=>0);int residualAt=ended.Log.FindIndex(x=>x.Contains("독: HP")),triggerAt=ended.Log.FindIndex(x=>x.Contains("『윤회』"));Check(residualAt>=0&&triggerAt>residualAt,"turn end trigger after residual");
   var burned=a.Copy();burned.Status="동상";Check(Calculate(db,burned,b,m,r).Max<d.Max,"frostbite");var debuff=a.Copy();debuff.Stages[3]=-6;r.Critical=true;Check(Calculate(db,debuff,b,m,r).Max==Calculate(db,a,b,m,r).Max,"critical ranks");
   var clean=new Rules();var states=new[]{new TrainerBattleState(),new TrainerBattleState()};var dodge=Resolve(db,new[]{a,b},new[]{new BattleCommand{Move=m},new BattleCommand{Move=m,Form="피해라！",Order="숙달 공격 지령"}},clean,states,()=>0);Check(dodge.Fighters[1].HP==b.HP&&dodge.Fighters[1].Stages[1]==1&&dodge.Trainers[1].UsedForms.Contains("피해라！")&&dodge.Trainers[1].UsedOrders.Contains("숙달 공격 지령"),"trainer form and order");
   bool duplicate=false;try{Resolve(db,new[]{a,b},new[]{new BattleCommand{Move=m},new BattleCommand{Move=m,Form="피해라！"}},clean,dodge.Trainers,()=>0);}catch(Exception){duplicate=true;}Check(duplicate,"directive once per battle");
   var endure=b.Copy();endure.HP=1;var held=Resolve(db,new[]{a,endure},new[]{new BattleCommand{Move=fast},new BattleCommand{Move=m,Form="버텨라！"}},clean,states,()=>0);Check(held.Fighters[1].HP==1,"endure trainer protection");
   var reserve=new Fighter(db.pokemon.First(p=>p.name=="원시 가이오가"));int reserveHP=reserve.HP;var returned=Resolve(db,new[]{a,b},new[]{new BattleCommand{SwitchIn=reserve,Form="돌아와！"},new BattleCommand{Move=fast}},clean,states,()=>0);Check(returned.Switched[0]&&returned.Fighters[0].Data.name==reserve.Data.name&&returned.Fighters[0].HP==reserveHP&&returned.SwitchedOut[0].HP==a.HP&&returned.Log.Any(x=>x.Contains("볼 안에 있어 실패")),"return withdraws before opposing action and enters last");
   var future=db.moves.First(v=>v.name=="미래예지");var futureTarget=new Fighter(db.pokemon.First(p=>p.name=="원시 가이오가"));var futureCast=Resolve(db,new[]{a.Copy(),futureTarget},new[]{new BattleCommand{Move=future},new BattleCommand{Move=protect,Form="피해라！"}},new Rules(),new[]{new TrainerBattleState(),new TrainerBattleState()},()=>0);Check(futureCast.Fighters[1].Conditions.DelayedAttacks.Count==1&&futureCast.Fighters[1].Conditions.DelayedAttacks[0].TurnsRemaining==1&&futureCast.Fighters[1].HP==futureTarget.HP,"future sight schedules through protect");int futureHp=futureCast.Fighters[1].HP;var futureResolved=Resolve(db,futureCast.Fighters,new[]{new BattleCommand{Move=protect},new BattleCommand{Move=protect,Form="버텨라！"}},futureCast.Rules,futureCast.Trainers,()=>0);Check(futureResolved.Fighters[1].HP<futureHp&&futureResolved.Log.Any(x=>x.Contains("선데이의 미래예지!")),"future sight resolves at true final");var magicGuardInput=futureCast.Fighters.Select(x=>x.Copy()).ToArray();magicGuardInput[1].Data.ability="매직가드";var magicGuardFuture=Resolve(db,magicGuardInput,new[]{new BattleCommand{Move=protect},new BattleCommand{Move=protect}},futureCast.Rules,futureCast.Trainers,()=>0);Check(magicGuardFuture.Fighters[1].HP<futureHp,"future sight is direct despite magic guard");
   Check(futureCast.Fighters[1].Conditions.DelayedAttacks[0].SourceSpecialAttack==Stats(a,futureTarget.Data.level,new Rules())[3],"future sight snapshots natural special attack");var boostedInput=futureCast.Fighters.Select(x=>x.Copy()).ToArray();boostedInput[0].Stages[3]=6;var boostedRules=futureCast.Rules.Copy();boostedRules.PowerMultiplier=5;boostedRules.DamageMultiplier=5;var boostedFuture=Resolve(db,boostedInput,new[]{new BattleCommand{Move=protect},new BattleCommand{Move=protect}},boostedRules,futureCast.Trainers,()=>0);var normalFuture=Resolve(db,futureCast.Fighters,new[]{new BattleCommand{Move=protect},new BattleCommand{Move=protect}},futureCast.Rules,futureCast.Trainers,()=>0);Check(boostedFuture.Fighters[1].HP==normalFuture.Fighters[1].HP,"future sight ignores source changes and multipliers");
   var sourceSwitch=Resolve(db,futureCast.Fighters,new[]{new BattleCommand{SwitchIn=new Fighter(db.pokemon.First(p=>p.name=="테스트2"))},new BattleCommand{Move=protect}},futureCast.Rules,futureCast.Trainers,()=>0);Check(sourceSwitch.Fighters[1].HP<futureHp&&sourceSwitch.Log.Any(x=>x.Contains("선데이의 미래예지!")),"future sight survives source switch");var cancelCast=Resolve(db,new[]{a.Copy(),futureTarget.Copy()},new[]{new BattleCommand{Move=future},new BattleCommand{Move=protect}},new Rules(),new[]{new TrainerBattleState(),new TrainerBattleState()},()=>0);var cancelled=Resolve(db,cancelCast.Fighters,new[]{new BattleCommand{Move=protect},new BattleCommand{SwitchIn=new Fighter(db.pokemon.First(p=>p.name=="테스트2"))}},cancelCast.Rules,cancelCast.Trainers,()=>0);Check(!cancelled.Log.Any(x=>x.Contains("선데이의 미래예지!"))&&cancelled.Fighters[1].Data.name=="테스트2","future sight cancels on target switch");var missInput=futureCast.Fighters.Select(x=>x.Copy()).ToArray();missInput[1].EvasionStage=6;var missedFuture=Resolve(db,missInput,new[]{new BattleCommand{Move=protect},new BattleCommand{Move=protect}},futureCast.Rules,futureCast.Trainers,()=>.99);Check(missedFuture.Fighters[1].HP==futureHp&&missedFuture.Log.Any(x=>x.Contains("최후 명중판정에서 빗나갔다")),"future sight accuracy is judged at final timing");
   var prep=TriggerFighter(a,"선행자","예고",TriggerStructures.AlwaysLabel);prep.Data.potentials[0].activation="선행";prep.Data.potentials[0].uses="1/시";var prepared=Resolve(db,new[]{prep,b},new[]{new BattleCommand{Move=fast,PreInputs=new[]{"예고"},Party=new[]{prep}},new BattleCommand{Move=m}},clean,states,()=>0);Check(prepared.Trainers[0].UsedPotentials.Contains("예고")&&prepared.Log.Any(x=>x.Contains("선행입력 『예고』")),"pre-input potential declaration");
    return "PASS: HP, level correction, spreadsheet 290-342 / .87=297, immunity, triple types, KO order, isolated inputs, structured battle triggers, frostbite, critical ranks, trainer directives, return/pivot/potential switches and delayed Future Sight timing.";
  }
  static void Check(bool ok,string label){if(!ok)throw new Exception("FAIL: "+label);}
 }
}
