using System;
using System.Linq;
using System.IO;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Text;
using System.Runtime.InteropServices;
using System.Collections.Generic;
using System.Windows.Forms;
using System.Web.Script.Serialization;

namespace AABattle {
 static class Theme {
  public static Color Ink=Color.Black,Muted=Color.Black,Line=Color.Black,Paper=Color.White,Accent=Color.Black;
  public static Font UI(float size=10,FontStyle style=FontStyle.Regular){return new Font(Fonts.System,Math.Max(16,(int)(size*2)),FontStyle.Regular,GraphicsUnit.Pixel);}
  public static void Frame(Graphics g,Rectangle r,bool shadow=true){g.SmoothingMode=SmoothingMode.None;if(shadow)g.FillRectangle(Brushes.Black,r.X+5,r.Y+5,r.Width-5,r.Height-5);int w=r.Width-5,h=r.Height-5,x=r.X,y=r.Y;Point[] outer={new Point(x+6,y),new Point(x+w-6,y),new Point(x+w,y+6),new Point(x+w,y+h-6),new Point(x+w-6,y+h),new Point(x+6,y+h),new Point(x,y+h-6),new Point(x,y+6)};g.FillPolygon(Brushes.Black,outer);g.FillRectangle(Brushes.White,x+3,y+6,w-6,h-12);g.FillRectangle(Brushes.White,x+6,y+3,w-12,h-6);g.DrawRectangle(Pens.Black,x+7,y+7,w-14,h-14);}
  public static void Text(Graphics g,string text,Font font,Rectangle bounds,Color color,ContentAlignment align){g.TextRenderingHint=TextRenderingHint.SingleBitPerPixelGridFit;using(var format=new StringFormat()){format.Alignment=align==ContentAlignment.MiddleCenter?StringAlignment.Center:align==ContentAlignment.MiddleRight?StringAlignment.Far:StringAlignment.Near;format.LineAlignment=StringAlignment.Center;format.Trimming=StringTrimming.EllipsisCharacter;format.FormatFlags=StringFormatFlags.NoWrap;using(var brush=new SolidBrush(color))g.DrawString(text,font,brush,bounds,format);}}
  public static Label Label(string text,int height=26){return new PixelLabel{Text=text,AutoSize=false,Height=height,ForeColor=Ink,Font=UI(),TextAlign=ContentAlignment.MiddleLeft,Dock=DockStyle.Top};}
  public static ComboBox Combo(IEnumerable<string> entries,string value){var c=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Font=new Font("맑은 고딕",10),Dock=DockStyle.Fill};c.DrawMode=DrawMode.OwnerDrawFixed;c.ItemHeight=27;c.DrawItem+=(s,e)=>{e.Graphics.FillRectangle((e.State&DrawItemState.Selected)!=0?Brushes.Black:Brushes.White,e.Bounds);if(e.Index>=0)using(var font=UI())Theme.Text(e.Graphics,c.Items[e.Index].ToString(),font,e.Bounds,(e.State&DrawItemState.Selected)!=0?Color.White:Color.Black,ContentAlignment.MiddleLeft);};c.Items.AddRange(entries.Cast<object>().ToArray());c.SelectedItem=value;if(c.SelectedIndex<0&&c.Items.Count>0)c.SelectedIndex=0;return c;}
  public static NumericUpDown Number(decimal value,decimal min,decimal max,int decimals=0){return new NumericUpDown{Minimum=min,Maximum=max,Value=Math.Min(max,Math.Max(min,value)),DecimalPlaces=decimals,Increment=decimals>0?.1m:1,Font=new Font("맑은 고딕",10),Dock=DockStyle.Fill};}
  public static TableLayoutPanel Table(int cols=2){var t=new TableLayoutPanel{Dock=DockStyle.Top,AutoSize=true,ColumnCount=cols,Padding=new Padding(15)};t.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,145));for(int i=1;i<cols;i++)t.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100f/(cols-1)));return t;}
  public static void Row(TableLayoutPanel t,string label,Control c){int row=t.RowCount++;t.RowStyles.Add(new RowStyle(SizeType.Absolute,42));t.Controls.Add(Label(label),0,row);t.Controls.Add(c,1,row);}
 }
 static class Fonts {
  static List<IntPtr> memory=new List<IntPtr>();static List<PrivateFontCollection> collections=new List<PrivateFontCollection>();
  [DllImport("gdi32.dll")]static extern IntPtr AddFontMemResourceEx(IntPtr data,uint size,IntPtr reserved,ref uint count);
  public static FontFamily AA,System;
  public static void Load(){AA=LoadOne("HeadKasen.ttf");System=LoadOne("pokemon-bw.otf");}
  static FontFamily LoadOne(string name){var bytes=Resource.Bytes(name);var ptr=Marshal.AllocCoTaskMem(bytes.Length);Marshal.Copy(bytes,0,ptr,bytes.Length);memory.Add(ptr);uint count=0;AddFontMemResourceEx(ptr,(uint)bytes.Length,IntPtr.Zero,ref count);var fonts=new PrivateFontCollection();fonts.AddMemoryFont(ptr,bytes.Length);collections.Add(fonts);return fonts.Families[0];}
 }
 class PixelLabel:Label {
  public PixelLabel(){SetStyle(ControlStyles.UserPaint|ControlStyles.OptimizedDoubleBuffer,true);}
  protected override void OnPaint(PaintEventArgs e){Theme.Text(e.Graphics,Text,Font,ClientRectangle,ForeColor,TextAlign);}
 }
 class MessageLabel:PixelLabel {
  protected override void OnPaint(PaintEventArgs e){Theme.Frame(e.Graphics,new Rectangle(0,0,Width,Height),false);Theme.Text(e.Graphics,Text,Font,new Rectangle(14,4,Width-28,Height-12),Color.Black,ContentAlignment.MiddleCenter);}
 }
 class FlatButton:Button {
  public bool Selected,Primary;public string Subtext="";
  public FlatButton(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);FlatStyle=FlatStyle.Flat;FlatAppearance.BorderSize=0;BackColor=Color.White;ForeColor=Color.Black;Font=Theme.UI();Cursor=Cursors.Hand;}
  protected override void OnPaint(PaintEventArgs e){var g=e.Graphics;g.SmoothingMode=SmoothingMode.None;g.Clear(Color.White);bool pressed=ClientRectangle.Contains(PointToClient(MousePosition))&&MouseButtons==MouseButtons.Left;int off=pressed?2:0;var r=new Rectangle(1+off,1+off,Width-6,Height-6);g.FillRectangle(Brushes.Black,r.X+3,r.Y+3,r.Width,r.Height);g.FillRectangle(Primary?Brushes.Black:Brushes.White,r);using(var pen=new Pen(Color.Black,Selected?3:2))g.DrawRectangle(pen,r);Color ink=Primary?Color.White:Color.Black;int left=Selected?27:8;if(Selected){int cy=Subtext.Length>0?Height/3:Height/2;for(int k=0;k<4;k++)g.FillRectangle(Primary?Brushes.White:Brushes.Black,11+k*3,cy-9+k*3,3,18-k*6);}
   var rect=new Rectangle(left+off,Subtext.Length>0?3+off:off,Width-left-10,Subtext.Length>0?Height/2:Height-5);Theme.Text(g,Text,Font,rect,ink,ContentAlignment.MiddleCenter);if(Subtext.Length>0)using(var font=Theme.UI(8))Theme.Text(g,Subtext,font,new Rectangle(8,Height/2-1,Width-22,Height/2-5),ink,ContentAlignment.MiddleCenter);if(!Enabled)for(int x=8;x<Width-8;x+=4)g.FillRectangle(Brushes.Black,x,Height-9,2,2);if(Focused)ControlPaint.DrawFocusRectangle(g,new Rectangle(6,6,Width-15,Height-15),ink,Primary?Color.Black:Color.White);}
 }
 class Card:Panel {
  public Card(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);BackColor=Color.White;Padding=new Padding(16);}
  protected override void OnPaintBackground(PaintEventArgs e){e.Graphics.Clear(Color.White);Theme.Frame(e.Graphics,new Rectangle(1,1,Width-2,Height-2));}
 }
 class AAView:Panel {
  string art="";public float TextSize=15;public bool Fit=true;
  public string Art {get{return art;}set{art=value??"";Invalidate();}}
  public AAView(){DoubleBuffered=true;BackColor=Color.White;AutoScroll=true;}
  protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);e.Graphics.TextRenderingHint=TextRenderingHint.AntiAliasGridFit;string[] lines=art.Replace("\r","").Split('\n');if(string.IsNullOrWhiteSpace(art)){TextRenderer.DrawText(e.Graphics,"AA를 붙여 넣어 주세요",Theme.UI(),ClientRectangle,Theme.Muted,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter);return;}using(var f=new Font(Fonts.AA,TextSize,FontStyle.Regular,GraphicsUnit.Pixel)){var format=(StringFormat)StringFormat.GenericTypographic.Clone();format.FormatFlags|=StringFormatFlags.MeasureTrailingSpaces|StringFormatFlags.NoWrap;float width=lines.Max(s=>e.Graphics.MeasureString(s,f,int.MaxValue,format).Width),height=lines.Length*(TextSize+1);float scale=Fit?Math.Min(1,Math.Min((ClientSize.Width-18)/Math.Max(1,width),(ClientSize.Height-18)/Math.Max(1,height))):1;AutoScrollMinSize=Fit?Size.Empty:new Size((int)width+20,(int)height+20);float x=Fit?Math.Max(8,(ClientSize.Width-width*scale)/2):8+AutoScrollPosition.X,y=Fit?Math.Max(8,(ClientSize.Height-height*scale)/2):8+AutoScrollPosition.Y;e.Graphics.TranslateTransform(x,y);e.Graphics.ScaleTransform(scale,scale);for(int i=0;i<lines.Length;i++)e.Graphics.DrawString(lines[i],f,Brushes.Black,new PointF(0,i*(TextSize+1)),format);format.Dispose();}}
 }
 class PokemonCard:Card {
  public Label Title,Meta,HP;public AAView Art;public FlatButton Edit,State;public Label StateLine;double hpRatio=1;
  public PokemonCard(int side){Title=new PixelLabel{Font=Theme.UI(15,FontStyle.Bold),ForeColor=Theme.Ink,BackColor=Color.White};Meta=new PixelLabel{Font=Theme.UI(8),ForeColor=Theme.Muted,BackColor=Color.White};HP=new PixelLabel{Font=Theme.UI(8),TextAlign=ContentAlignment.MiddleRight,ForeColor=Theme.Muted,BackColor=Color.White};Edit=new FlatButton{Text="편집",Font=Theme.UI(8)};State=new FlatButton{Text="상태",Font=Theme.UI(8)};StateLine=new PixelLabel{Font=Theme.UI(8),BackColor=Color.White};Art=new AAView();Controls.AddRange(new Control[]{Title,Meta,HP,Edit,State,StateLine,Art});}
  protected override void OnResize(EventArgs e){base.OnResize(e);if(Title==null)return;Title.SetBounds(23,20,Width-165,30);State.SetBounds(Width-136,20,53,30);Edit.SetBounds(Width-77,20,53,30);Meta.SetBounds(24,53,Width-160,22);HP.SetBounds(Width-158,53,133,22);StateLine.SetBounds(25,103,Width-52,25);Art.SetBounds(18,137,Width-40,Height-164);}
  protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);int x=25,y=86,w=Width-54;e.Graphics.DrawRectangle(Pens.Black,x,y,w,12);int n=(w-4)/6;for(int i=0;i<n;i++)if(i<(int)Math.Ceiling(n*hpRatio))e.Graphics.FillRectangle(Brushes.Black,x+3+i*6,y+3,4,7);}
  public void ShowFighter(Fighter f,int max,int side){Title.Text=f.Data.name;Meta.Text="TEAM "+(side+1)+"   ·   Lv. "+f.Data.level+"   ·   "+string.Join(" / ",f.Data.types);HP.Text="HP  "+f.HP+" / "+max;hpRatio=max>0?(double)f.HP/max:0;Art.Art=f.AA;Invalidate();}
 }
 class MoveCard:Card {
  public FlatButton[] Buttons=new FlatButton[4];public event Action<int> SelectedMove;
  public MoveCard(){for(int i=0;i<4;i++){int k=i;Buttons[i]=new FlatButton{Font=Theme.UI(10,FontStyle.Bold)};Buttons[i].Click+=(s,e)=>{if(SelectedMove!=null)SelectedMove(k);};Controls.Add(Buttons[i]);}}
  protected override void OnResize(EventArgs e){base.OnResize(e);int w=(Width-38)/2,h=(Height-38)/2;for(int i=0;i<4;i++)if(Buttons[i]!=null)Buttons[i].SetBounds(14+(i%2)*(w+10),14+(i/2)*(h+10),w,h);}
  public void RefreshMoves(Fighter f,Database db){for(int i=0;i<4;i++){string name=i<f.Moves.Length?f.Moves[i]:"";var m=db.moves.FirstOrDefault(x=>x.name==name);Buttons[i].Text=name.Length>0?name:"—";Buttons[i].Subtext=m==null?"기술 편집에서 등록":string.Join("/",m.types)+" · "+m.category+" · "+(m.power>0?m.power.ToString():"—");Buttons[i].Enabled=m!=null;Buttons[i].Selected=f.Selected==i;Buttons[i].Invalidate();}}
 }
 class TurnSelection {public string Form="",Order="";public int SwitchIndex=-1;public TurnSelection Copy(){return new TurnSelection{Form=Form,Order=Order,SwitchIndex=SwitchIndex};}}
 static class DirectiveRules {
  static readonly string[] Forms={"물러나","피해라","돌아와","버텨라","맞춰라"};
  public static bool IsForm(string name){return Forms.Any(x=>(name??"").Contains(x));}
  public static string Label(TurnSelection v){string action=v.SwitchIndex>=0?"교대":"기술";return action+" · 4식 "+(v.Form.Length>0?v.Form:"—")+" · 지령 "+(v.Order.Length>0?v.Order:"—");}
 }
 class DirectiveForm:Form {
  public TurnSelection Value;ComboBox action,target,form,order;List<Fighter> reserves;TrainerBattleState state;TrainerRecord trainer;bool loading;
  public DirectiveForm(TrainerRecord source,TrainerBattleState used,List<Fighter> team,TurnSelection input){trainer=source;state=used;reserves=team;Value=input.Copy();Text="행동 / 4식 / 지령 선언";Size=new Size(590,360);StartPosition=FormStartPosition.CenterParent;BackColor=Color.White;Font=Theme.UI();var table=Theme.Table();action=Theme.Combo(new[]{"기술 사용","교대"},Value.SwitchIndex>=0?"교대":"기술 사용");target=Theme.Combo(new[]{"선택하세요"}.Concat(reserves.Select(x=>x.Data.name)),Value.SwitchIndex>=0&&Value.SwitchIndex<reserves.Count?reserves[Value.SwitchIndex].Data.name:"선택하세요");form=Theme.Combo(new[]{"사용 안 함"},"사용 안 함");order=Theme.Combo(new[]{"사용 안 함"},"사용 안 함");Theme.Row(table,"이번 행동",action);Theme.Row(table,"교대 대상",target);Theme.Row(table,"4식 (턴당 1회)",form);Theme.Row(table,"지령 (턴당 1개)",order);var note=Theme.Label(trainer==null?"트레이너를 적용하면 그 트레이너의 4식·지령이 여기에 나타납니다.":"모두 선택 사항이며, 각 항목은 1시합 1회입니다. 『돌아와!』는 교대와 함께 선언합니다.",48);note.ForeColor=Theme.Muted;Theme.Row(table,"규칙",note);var foot=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=62,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(12)};var apply=new FlatButton{Text="선택",Primary=true,Size=new Size(95,36)};var cancel=new FlatButton{Text="취소",Size=new Size(85,36),DialogResult=DialogResult.Cancel};foot.Controls.AddRange(new Control[]{apply,cancel});Controls.Add(table);Controls.Add(foot);action.SelectedIndexChanged+=(s,e)=>FillChoices();apply.Click+=(s,e)=>Apply();FillChoices();}
  IEnumerable<string> EnabledNames(){return (trainer==null||trainer.potentials==null?Enumerable.Empty<PotentialRecord>():trainer.potentials.Where(x=>x.enabled&&x.slot=="지령"&&x.name.Length>0)).Select(x=>x.name);}
  void FillChoices(){if(loading)return;loading=true;bool switching=(string)action.SelectedItem=="교대";string oldForm=Value.Form,oldOrder=Value.Order;var forms=EnabledNames().Where(DirectiveRules.IsForm).Where(x=>!state.UsedForms.Contains(x)).Where(x=>switching?x.Contains("돌아와"):!x.Contains("돌아와")).Distinct().ToArray();form.Items.Clear();form.Items.Add("사용 안 함");form.Items.AddRange(forms.Cast<object>().ToArray());form.SelectedItem=forms.Contains(oldForm)?oldForm:"사용 안 함";var orders=EnabledNames().Where(x=>!DirectiveRules.IsForm(x)&&!state.UsedOrders.Contains(x)).Distinct().ToArray();order.Items.Clear();order.Items.Add("사용 안 함");if(!switching)order.Items.AddRange(orders.Cast<object>().ToArray());order.SelectedItem=!switching&&orders.Contains(oldOrder)?oldOrder:"사용 안 함";target.Enabled=switching;form.Enabled=forms.Length>0;order.Enabled=!switching&&orders.Length>0;loading=false;}
  void Apply(){bool switching=(string)action.SelectedItem=="교대";int selected=target.SelectedIndex-1;if(switching&&selected<0){MessageBox.Show(this,"교대할 포켓몬을 선택하세요.");return;}string selectedForm=(string)form.SelectedItem,selectedOrder=(string)order.SelectedItem;Value=new TurnSelection{SwitchIndex=switching?selected:-1,Form=selectedForm=="사용 안 함"?"":selectedForm,Order=selectedOrder=="사용 안 함"?"":selectedOrder};DialogResult=DialogResult.OK;Close();}
 }
 class Snapshot {public Rules Rules;public Fighter[] Fighters;public List<Fighter>[] Reserves;public TrainerBattleState[] Trainers;public TurnSelection[] Selections;public int Turn;public string Log;}
 class MainForm:Form {
  readonly Database db;public Fighter[] Fighters;public Rules Rules=new Rules();int turn=1;Random random=new Random();Stack<Snapshot> undo=new Stack<Snapshot>();string log="";
  TrainerRecord[] trainers=new TrainerRecord[2];TrainerBattleState[] trainerStates={new TrainerBattleState(),new TrainerBattleState()};TurnSelection[] selections={new TurnSelection(),new TurnSelection()};List<Fighter>[] reserves={new List<Fighter>(),new List<Fighter>()};
  PokemonCard[] cards=new PokemonCard[2];MoveCard[] moveCards=new MoveCard[2];FlatButton[] directiveButtons=new FlatButton[2];FlatButton calculate,settings,results,reset,back,guide,teamEditor;Label brand,turnLabel,status,fieldLabel;ToolTip hints=new ToolTip{AutoPopDelay=15000,InitialDelay=300};ResultForm resultForm;DataEditorForm dataEditorForm;
  public MainForm(Database database){db=database;Text="AA BATTLE · 지령 시스템 빌드 0.6";ClientSize=new Size(1220,780);MinimumSize=new Size(940,670);StartPosition=FormStartPosition.CenterScreen;BackColor=Theme.Paper;Font=Theme.UI();AutoScaleMode=AutoScaleMode.Dpi;DoubleBuffered=true;
   Fighters=new[]{new Fighter(db.pokemon.First(p=>p.name=="선데이")),new Fighter(db.pokemon.First(p=>p.name=="잭 한마"))};var arts=new JavaScriptSerializer().Deserialize<string[]>(Resource.Text("aa.json"));Fighters[0].AA=ExtractArt(arts[4]);Fighters[1].AA=ExtractArt(arts[3]);
   for(int i=0;i<2;i++){var existing=Fighters[i].Moves.Concat(i==0?new[]{"에어슬래시","10만볼트","방어"}:new[]{"독찌르기","지진","방어"}).Distinct().Where(n=>db.moves.Any(m=>m.name==n)).Take(4).ToArray();Fighters[i].Moves=existing;}
   brand=new PixelLabel{Text="AA BATTLE",Font=Theme.UI(13,FontStyle.Bold),ForeColor=Theme.Ink};turnLabel=new PixelLabel{Font=Theme.UI(10),ForeColor=Theme.Muted,TextAlign=ContentAlignment.MiddleCenter};status=new MessageLabel{Font=Theme.UI(9),ForeColor=Theme.Muted,TextAlign=ContentAlignment.MiddleCenter};
   settings=new FlatButton{Text="계산 설정"};results=new FlatButton{Text="계산 내역"};reset=new FlatButton{Text="초기화"};back=new FlatButton{Text="되돌리기"};calculate=new FlatButton{Text="배틀 !",Primary=true,Font=Theme.UI(11,FontStyle.Bold)};
   guide=new FlatButton{Text="배틀 규칙",Font=Theme.UI(9)};teamEditor=new FlatButton{Text="팀 편집",Font=Theme.UI(9)};fieldLabel=new PixelLabel{Font=Theme.UI(9),TextAlign=ContentAlignment.MiddleCenter};guide.Click+=(s,e)=>{using(var g=new GuideForm(db))g.ShowDialog(this);};teamEditor.Click+=(s,e)=>ShowTeamEditor();Controls.AddRange(new Control[]{brand,turnLabel,status,fieldLabel,guide,teamEditor,settings,results,reset,back,calculate});
   for(int i=0;i<2;i++){int side=i;cards[i]=new PokemonCard(i);cards[i].Edit.Click+=(s,e)=>Edit(side);cards[i].State.Click+=(s,e)=>EditConditions(side);cards[i].Art.DoubleClick+=(s,e)=>Edit(side);moveCards[i]=new MoveCard();moveCards[i].SelectedMove+=k=>{Fighters[side].Selected=k;selections[side].SwitchIndex=-1;RefreshView();};directiveButtons[i]=new FlatButton{Font=Theme.UI(8)};directiveButtons[i].Click+=(s,e)=>SelectDirective(side);Controls.Add(cards[i]);Controls.Add(moveCards[i]);Controls.Add(directiveButtons[i]);}
   settings.Click+=(s,e)=>{using(var dialog=new RulesForm(Rules)){if(dialog.ShowDialog(this)==DialogResult.OK){Save();Rules=dialog.Value;for(int i=0;i<2;i++)Fighters[i].HP=Math.Min(Fighters[i].HP,Engine.Stats(Fighters[i],Fighters[1-i].Data.level,Rules)[0]);RefreshView();}}};results.Click+=(s,e)=>ShowResults();back.Click+=(s,e)=>Undo();reset.Click+=(s,e)=>{Save();for(int i=0;i<2;i++){ResetFighter(Fighters[i],true);foreach(var reserve in reserves[i])ResetFighter(reserve,true);trainerStates[i]=new TrainerBattleState();selections[i]=new TurnSelection();}Rules.Weather="없음";Rules.Terrain="없음";Rules.TrickRoom=Rules.Gravity=0;turn=1;log="배틀을 초기화했습니다.";RefreshView();};calculate.Click+=(s,e)=>Battle();Resize+=(s,e)=>Arrange();Arrange();RefreshView();
  }
  static string ExtractArt(string source){var lines=source.Replace("\r","").Split('\n');int end=Array.FindIndex(lines,l=>l.Contains("【이름】"));return string.Join("\n",lines.Take(end>0?end-1:lines.Length).Select(l=>System.Text.RegularExpressions.Regex.Replace(l,@"\s+[♂♀？]\s*[OXＯＸ]\s*$",""))).Trim('\n');}
  void Arrange(){int margin=34,gap=150,width=(ClientSize.Width-margin*2-gap)/2,top=121,moveHeight=154,commandHeight=36,bottom=ClientSize.Height-62,artHeight=bottom-top-moveHeight-commandHeight-27;brand.SetBounds(margin,25,150,28);guide.SetBounds(margin+170,22,110,32);teamEditor.SetBounds(margin+288,22,100,32);fieldLabel.SetBounds(margin,69,ClientSize.Width-margin*2,30);turnLabel.SetBounds(ClientSize.Width/2-70,25,140,28);settings.SetBounds(ClientSize.Width-margin-294,22,98,32);results.SetBounds(ClientSize.Width-margin-188,22,98,32);reset.SetBounds(ClientSize.Width-margin-82,22,82,32);for(int i=0;i<2;i++){int x=i==0?margin:ClientSize.Width-margin-width;cards[i].SetBounds(x,top,width,artHeight);directiveButtons[i].SetBounds(x,bottom-moveHeight-commandHeight-7,width,commandHeight);moveCards[i].SetBounds(x,bottom-moveHeight,width,moveHeight);}calculate.SetBounds(ClientSize.Width/2-61,bottom-moveHeight+35,122,65);back.SetBounds(ClientSize.Width/2-51,bottom-42,102,28);status.SetBounds(margin,bottom+10,ClientSize.Width-margin*2,43);}
  void Save(){undo.Push(new Snapshot{Fighters=Fighters.Select(f=>f.Copy()).ToArray(),Reserves=reserves.Select(x=>x.Select(f=>f.Copy()).ToList()).ToArray(),Trainers=trainerStates.Select(x=>x.Copy()).ToArray(),Selections=selections.Select(x=>x.Copy()).ToArray(),Rules=Rules.Copy(),Turn=turn,Log=log});}
  void Undo(){if(undo.Count==0)return;var s=undo.Pop();Fighters=s.Fighters;reserves=s.Reserves;trainerStates=s.Trainers;selections=s.Selections;Rules=s.Rules;turn=s.Turn;log=s.Log;RefreshView();}
  void ResetFighter(Fighter f,bool heal){f.Stages=new int[6];f.AccuracyStage=f.EvasionStage=0;f.AccuracyMultiplier=f.EvasionMultiplier=1;f.Multipliers=new[]{1d,1d,1d,1d,1d,1d};f.Status="정상";f.Conditions=new ConditionState();if(heal)f.HP=Engine.Stats(f,f.Data.level,new Rules())[0];}
  void Bench(Fighter f){f.Stages=new int[6];f.AccuracyStage=f.EvasionStage=0;f.AccuracyMultiplier=f.EvasionMultiplier=1;f.Multipliers=new[]{1d,1d,1d,1d,1d,1d};f.Conditions.Confusion=f.Conditions.Taunt=f.Conditions.Substitute=f.Conditions.ProtectChain=0;f.Conditions.Protect=f.Conditions.Flinch=f.Conditions.Seed=f.Conditions.Curse=f.Conditions.Ingrain=false;}
  void SelectDirective(int side){using(var dialog=new DirectiveForm(trainers[side],trainerStates[side],reserves[side],selections[side]))if(dialog.ShowDialog(this)==DialogResult.OK){selections[side]=dialog.Value;RefreshView();}}
  void Edit(int side){using(var dialog=new FighterForm(db,Fighters[side],Fighters[1-side].Data.level,Rules)){if(dialog.ShowDialog(this)==DialogResult.OK){Save();Fighters[side]=dialog.Value;RefreshView();}}}
  void EditConditions(int side){using(var dialog=new ConditionsForm(db,Fighters[side],Fighters[1-side],Rules)){if(dialog.ShowDialog(this)==DialogResult.OK){Save();Fighters[side]=dialog.Value;RefreshView();}}}
  void Battle(){if(Fighters.Any(f=>f.HP<=0))return;var old=Fighters.Select(x=>x.Copy()).ToArray();var commands=new BattleCommand[2];var rangeLines=new List<string>();for(int i=0;i<2;i++){var pick=selections[i];if(pick.SwitchIndex>=0){if(pick.SwitchIndex>=reserves[i].Count){MessageBox.Show(this,"교대 대상을 다시 선택하세요.");return;}commands[i]=new BattleCommand{SwitchIn=reserves[i][pick.SwitchIndex],Form=pick.Form,Order=pick.Order};rangeLines.Add(Fighters[i].Data.name+" · 교대 → "+commands[i].SwitchIn.Data.name);}else{var m=db.moves.First(x=>x.name==Fighters[i].Moves[Math.Min(Fighters[i].Selected,Fighters[i].Moves.Length-1)]);commands[i]=new BattleCommand{Move=m,Form=pick.Form,Order=pick.Order};var d=Engine.Calculate(db,Fighters[i],Fighters[1-i],m,Rules);rangeLines.Add(Fighters[i].Data.name+" · "+m.name+"   "+(d.Supported?d.Min+" – "+d.Max+"  (자속 ×"+d.Stab+", 상성 ×"+d.Type+")":(Mechanics.KnownMove(m)&&m.name!="날개쉬기"?"상태 기술":"수동 판정")));}}Save();try{var result=Engine.Resolve(db,Fighters,commands,Rules,trainerStates,random.NextDouble);for(int i=0;i<2;i++)if(result.Switched[i]){reserves[i].RemoveAt(selections[i].SwitchIndex);var outgoing=old[i];Bench(outgoing);reserves[i].Add(outgoing);}log="TURN "+turn+"\r\n"+string.Join("\r\n",rangeLines)+"\r\n\r\n"+string.Join("\r\n",result.Log)+"\r\n\r\n────────────────────\r\n\r\n"+log;Fighters=result.Fighters;Rules=result.Rules;trainerStates=result.Trainers;selections=new[]{new TurnSelection(),new TurnSelection()};turn++;RefreshView();ShowResults();}catch(Exception ex){undo.Pop();MessageBox.Show(this,ex.Message,"지시 확인",MessageBoxButtons.OK,MessageBoxIcon.Information);}}
  public void RefreshView(){for(int i=0;i<2;i++){cards[i].ShowFighter(Fighters[i],Engine.Stats(Fighters[i],Fighters[1-i].Data.level,Rules)[0],i);moveCards[i].RefreshMoves(Fighters[i],db);directiveButtons[i].Text=DirectiveRules.Label(selections[i]);directiveButtons[i].Subtext=(trainers[i]==null?"트레이너 미적용":(trainers[i].name.Length>0?trainers[i].name:"이름 없는 트레이너"))+" · 대기 "+reserves[i].Count;cards[i].StateLine.Text=RuleBook.Summary(Fighters[i],Fighters[1-i],Rules);hints.SetToolTip(cards[i].StateLine,cards[i].StateLine.Text);hints.SetToolTip(directiveButtons[i],trainers[i]==null?"팀 편집에서 트레이너를 적용하면 4식·지령을 선택할 수 있습니다.":"4식과 지령은 선택 사항이며 각 항목은 1시합 1회입니다.");for(int j=0;j<Fighters[i].Moves.Length;j++){var m=db.moves.FirstOrDefault(v=>v.name==Fighters[i].Moves[j]);if(m==null)continue;string block=Mechanics.TargetsOpponent(m)?Mechanics.Block(db,Fighters[i],Fighters[1-i],m,Rules):"";var button=moveCards[i].Buttons[j];button.Subtext=string.Join("/",m.types)+" / "+(block.Length>0?"무효":m.category=="변화"?(Mechanics.KnownMove(m)&&m.name!="날개쉬기"?"상태 적용":"수동 판정"):"상성 ×"+Mechanics.TypeEffect(db,Fighters[i],Fighters[1-i],m,Rules));hints.SetToolTip(button,(block.Length>0?block+"\n":"")+m.effect+"\n등록된 효과 외에는 수동 판정입니다.");button.Invalidate();}}fieldLabel.Text=RuleBook.Field(Rules,Fighters);turnLabel.Text="TURN  "+turn.ToString("00");calculate.Enabled=Fighters.All(f=>f.HP>0);back.Enabled=undo.Count>0;status.Text=Fighters.Any(f=>f.HP<=0)?"포켓몬이 쓰러졌습니다. 교대하거나 초기화하세요.":"기술을 선택하고 필요하면 4식·지령을 선언한 뒤 배틀 !";if(resultForm!=null&&!resultForm.IsDisposed)resultForm.SetLog(log);}
  void ShowResults(){if(resultForm==null||resultForm.IsDisposed)resultForm=new ResultForm();resultForm.SetLog(log);if(!resultForm.Visible)resultForm.Show(this);resultForm.Activate();}
  void ShowTeamEditor(){if(dataEditorForm==null||dataEditorForm.IsDisposed){dataEditorForm=new DataEditorForm(LoadFromEditor,LoadTrainerFromEditor);dataEditorForm.FormClosed+=(s,e)=>dataEditorForm=null;dataEditorForm.Show(this);}else dataEditorForm.Activate();}
  void LoadFromEditor(PokemonRecord source,int side){string warning;var data=EditorBridge.ToPokemon(source,db,out warning);Save();var fighter=new Fighter(data);fighter.AA=source.asciiArt;if(Fighters[side].Data.name!=data.name){if(reserves[side].Count>=5)throw new Exception("한 팀에는 대기 포켓몬을 5체까지만 둘 수 있습니다.");reserves[side].RemoveAll(x=>x.Data.name==data.name);reserves[side].Add(Fighters[side].Copy());}Fighters[side]=fighter;selections[side]=new TurnSelection();log="팀 편집기에서 "+data.name+"을 "+(side==0?"왼쪽":"오른쪽")+" 배틀 슬롯에 불러왔습니다."+(warning.Length>0?"\r\n"+warning:"")+"\r\n\r\n"+log;RefreshView();status.Text=data.name+" → "+(side==0?"왼쪽":"오른쪽")+" 슬롯 적용 완료 · 이전 포켓몬은 대기"+(warning.Length>0?" (일부 항목 제외)":"");}
  void LoadTrainerFromEditor(TrainerRecord source,int side){Save();string json=new JavaScriptSerializer().Serialize(source);trainers[side]=new JavaScriptSerializer().Deserialize<TrainerRecord>(json);trainerStates[side]=new TrainerBattleState();selections[side]=new TurnSelection();log=(source.name.Length>0?source.name:"이름 없는 트레이너")+"를 TRAINER "+(side+1)+"에 적용했습니다. 지령 사용 이력이 초기화됩니다.\r\n\r\n"+log;RefreshView();}
  public void Smoke(){var old=Fighters[0].HP;var savedRules=Rules.Copy();Rules.Weather="비";Rules.WeatherTurns=3;Fighters[0].Conditions.Reflect=3;Battle();if(turn!=2||log.Length==0)throw new Exception("Turn UI failed");Undo();if(turn!=1||Fighters[0].HP!=old||Rules.WeatherTurns!=3||Fighters[0].Conditions.Reflect!=3)throw new Exception("Undo UI failed");Rules=savedRules;Fighters[0].Conditions.Reflect=0;RefreshView();if(resultForm!=null)resultForm.Close();using(var f=new FighterForm(db,Fighters[0],Fighters[1].Data.level,Rules)){f.CreateControl();}using(var f=new RulesForm(Rules)){f.CreateControl();}using(var f=new DataEditorForm()){f.CreateControl();}}
 }
 class LogView:Panel {
  string content="";public LogView(){DoubleBuffered=true;AutoScroll=true;BackColor=Color.White;}
  public void SetLog(string log){content=log;AutoScrollPosition=Point.Empty;Invalidate();}
  protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);e.Graphics.TextRenderingHint=TextRenderingHint.SingleBitPerPixelGridFit;float y=AutoScrollPosition.Y;int width=Math.Max(50,ClientSize.Width-22);using(var f=new Font(Fonts.System,20,FontStyle.Regular,GraphicsUnit.Pixel)){foreach(string line in content.Replace("\r","").Split('\n')){float height=Math.Max(27,e.Graphics.MeasureString(line.Length==0?" ":line,f,width).Height+5);using(var brush=new SolidBrush(Theme.Ink))e.Graphics.DrawString(line,f,brush,new RectangleF(2,y,width,height));y+=height;}}AutoScrollMinSize=new Size(0,(int)y-AutoScrollPosition.Y+10);}
 }
 class ResultForm:Form {
  LogView text;
  public ResultForm(){Text="계산 내역 · AA BATTLE";Size=new Size(600,480);MinimumSize=new Size(450,300);StartPosition=FormStartPosition.CenterParent;BackColor=Color.White;Font=Theme.UI();var notice=Theme.Label("대미지 / 무효 사유 / 상태 처리 / 턴 종료 효과",45);notice.Padding=new Padding(15,0,10,0);notice.ForeColor=Theme.Muted;text=new LogView{Dock=DockStyle.Fill};var padding=new Panel{Dock=DockStyle.Fill,Padding=new Padding(20,12,20,20)};padding.Controls.Add(text);Controls.Add(padding);Controls.Add(notice);}
  public void SetLog(string log){text.SetLog(string.IsNullOrEmpty(log)?"아직 계산 내역이 없습니다.":log);}
 }
 class FighterForm:Form {
  public Fighter Value;Database db;int other;Rules rules;ComboBox source,status;TextBox name,aa,ability,item;NumericUpDown level,hp;ComboBox[] type=new ComboBox[3],moves=new ComboBox[4];NumericUpDown[] bases=new NumericUpDown[6],ivs=new NumericUpDown[6],stages=new NumericUpDown[6],mult=new NumericUpDown[6];
  public FighterForm(Database database,Fighter input,int opponent,Rules r){db=database;other=opponent;rules=r;Value=input.Copy();Text="포켓몬 / AA 편집";Size=new Size(790,700);MinimumSize=new Size(650,590);StartPosition=FormStartPosition.CenterParent;Font=Theme.UI();BackColor=Color.White;
   var tabs=new TabControl{Dock=DockStyle.Fill,Font=new Font("맑은 고딕",10),DrawMode=TabDrawMode.OwnerDrawFixed,SizeMode=TabSizeMode.Fixed,ItemSize=new Size(110,30)};tabs.DrawItem+=(s,e)=>{bool selected=e.Index==tabs.SelectedIndex;e.Graphics.FillRectangle(selected?Brushes.Black:Brushes.White,e.Bounds);e.Graphics.DrawRectangle(Pens.Black,e.Bounds);using(var font=Theme.UI())Theme.Text(e.Graphics,tabs.TabPages[e.Index].Text,font,e.Bounds,selected?Color.White:Color.Black,ContentAlignment.MiddleCenter);};var dataPage=new TabPage("포켓몬"){AutoScroll=true,BackColor=Color.White};var aaPage=new TabPage("아스키아트"){BackColor=Color.White};var statsPage=new TabPage("능력치"){BackColor=Color.White};var movesPage=new TabPage("기술"){BackColor=Color.White};tabs.TabPages.AddRange(new[]{dataPage,aaPage,statsPage,movesPage});
   var table=Theme.Table();source=Theme.Combo(db.pokemon.Select(p=>p.name),Value.Data.name);name=new TextBox{Dock=DockStyle.Fill,Font=new Font("맑은 고딕",10)};level=Theme.Number(100,1,999);hp=Theme.Number(100,0,999999);status=Theme.Combo(Mechanics.Statuses,Value.Status);status.Enabled=false;ability=new TextBox{Dock=DockStyle.Fill,Font=new Font("맑은 고딕",10)};item=new TextBox{Dock=DockStyle.Fill,Font=new Font("맑은 고딕",10)};Theme.Row(table,"시트에서 불러오기",source);Theme.Row(table,"이름",name);Theme.Row(table,"레벨",level);Theme.Row(table,"현재 HP",hp);for(int i=0;i<3;i++){type[i]=Theme.Combo(new[]{"없음"}.Concat(db.types),"없음");Theme.Row(table,"타입 "+(i+1),type[i]);}Theme.Row(table,"상태 (상태 창)",status);Theme.Row(table,"특성",ability);Theme.Row(table,"소지품",item);var heal=new FlatButton{Text="현재 설정 기준 HP 가득 회복",Dock=DockStyle.Fill};Theme.Row(table,"HP",heal);var info=Theme.Label("등록된 특성·도구만 적용. 배틀 규칙에서 확인하세요.",45);info.ForeColor=Theme.Muted;Theme.Row(table,"판정 범위",info);dataPage.Controls.Add(table);
   aa=new TextBox{Multiline=true,AcceptsReturn=true,AcceptsTab=true,WordWrap=false,ScrollBars=ScrollBars.Both,Dock=DockStyle.Fill,Font=new Font(Fonts.AA,12),BorderStyle=BorderStyle.FixedSingle};aaPage.Padding=new Padding(15);aaPage.Controls.Add(aa);var hint=Theme.Label("공백·줄바꿈을 유지합니다. 배틀 창에서는 AA 전체가 보이도록 비율을 맞춥니다.",45);hint.ForeColor=Theme.Muted;aaPage.Controls.Add(hint);
   var grid=new TableLayoutPanel{Dock=DockStyle.Top,AutoSize=true,ColumnCount=5,Padding=new Padding(18)};foreach(string h in new[]{"능력치","종족치","개체치","랭크","배율"}){grid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,20));grid.Controls.Add(Theme.Label(h));}for(int i=0;i<6;i++){grid.RowStyles.Add(new RowStyle(SizeType.Absolute,48));grid.Controls.Add(Theme.Label(Engine.Names[i]),0,i+1);bases[i]=Theme.Number(100,1,999);ivs[i]=Theme.Number(0,0,31);stages[i]=Theme.Number(0,-6,6);mult[i]=Theme.Number(1,.1m,100,2);grid.Controls.Add(bases[i],1,i+1);grid.Controls.Add(ivs[i],2,i+1);grid.Controls.Add(stages[i],3,i+1);grid.Controls.Add(mult[i],4,i+1);if(i==0){stages[i].Enabled=false;mult[i].Enabled=false;}}statsPage.Controls.Add(grid);
   var mt=Theme.Table();for(int i=0;i<4;i++){moves[i]=new ComboBox{Dock=DockStyle.Fill,Font=new Font("맑은 고딕",10),DropDownStyle=ComboBoxStyle.DropDown,AutoCompleteMode=AutoCompleteMode.SuggestAppend,AutoCompleteSource=AutoCompleteSource.ListItems};moves[i].Items.AddRange(db.moves.Select(m=>m.name).Distinct().Cast<object>().ToArray());Theme.Row(mt,"기술 "+(i+1),moves[i]);}var explanation=new PixelLabel{Text="기술명을 입력해 검색할 수 있습니다.\r\n등록된 상태·날씨 효과는 자동 적용됩니다. 자세한 지원 범위는 배틀 규칙에서 확인하세요.",AutoSize=true,MaximumSize=new Size(530,0),ForeColor=Theme.Muted};Theme.Row(mt,"안내",explanation);movesPage.Controls.Add(mt);
   var foot=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=65,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(12)};var apply=new FlatButton{Text="적용",Primary=true,Size=new Size(100,38)};var cancel=new FlatButton{Text="취소",Size=new Size(85,38),DialogResult=DialogResult.Cancel};foot.Controls.AddRange(new Control[]{apply,cancel});Controls.Add(tabs);Controls.Add(foot);CancelButton=cancel;
   Fill();source.SelectedIndexChanged+=(s,e)=>{var p=db.pokemon.FirstOrDefault(x=>x.name==(string)source.SelectedItem);if(p!=null){string art=aa.Text;Value=new Fighter(p){AA=art};Fill();}};heal.Click+=(s,e)=>{try{ReadFields(false);hp.Value=Engine.Stats(Value,other,rules)[0];}catch(Exception ex){MessageBox.Show(this,ex.Message,"입력 확인",MessageBoxButtons.OK,MessageBoxIcon.Information);}};apply.Click+=(s,e)=>{try{ReadFields(true);Value.HP=Math.Min(Value.HP,Engine.Stats(Value,other,rules)[0]);DialogResult=DialogResult.OK;Close();}catch(Exception ex){MessageBox.Show(this,ex.Message,"입력 확인",MessageBoxButtons.OK,MessageBoxIcon.Information);}};
  }
  void Fill(){name.Text=Value.Data.name;level.Value=Value.Data.level;hp.Value=Value.HP;status.SelectedItem=Value.Status;ability.Text=Value.Data.ability;item.Text=Value.Data.item;aa.Text=Value.AA;for(int i=0;i<3;i++)type[i].SelectedItem=i<Value.Data.types.Length?Value.Data.types[i]:"없음";for(int i=0;i<6;i++){bases[i].Value=Value.Data.@base[i];ivs[i].Value=Value.Data.iv[i];stages[i].Value=Value.Stages[i];mult[i].Value=(decimal)Value.Multipliers[i];}for(int i=0;i<4;i++)moves[i].Text=i<Value.Moves.Length?Value.Moves[i]:"";}
  void ReadFields(bool validate){if(string.IsNullOrWhiteSpace(name.Text))throw new Exception("이름을 입력하세요.");var ts=type.Select(c=>(string)c.SelectedItem).Where(t=>t!="없음").Distinct().ToArray();if(ts.Length==0)throw new Exception("타입을 하나 이상 선택하세요.");string[] ms=moves.Select(c=>c.Text.Trim()).Where(t=>t.Length>0).ToArray();if(validate&&(ms.Length==0||ms.Any(n=>!db.moves.Any(m=>m.name==n))))throw new Exception("목록에 있는 기술을 하나 이상 선택하세요.");Value.Data.ability=ability.Text.Trim();Value.Data.item=item.Text.Trim();Value.Data.name=name.Text.Trim();Value.Data.level=(int)level.Value;Value.Data.types=ts;Value.HP=(int)hp.Value;Value.Status=(string)status.SelectedItem;Value.AA=aa.Text;Value.Data.@base=bases.Select(n=>(int)n.Value).ToArray();Value.Data.iv=ivs.Select(n=>(int)n.Value).ToArray();Value.Stages=stages.Select(n=>(int)n.Value).ToArray();Value.Multipliers=mult.Select(n=>(double)n.Value).ToArray();if(validate){Value.Moves=ms;Value.Selected=0;}}
 }
 static class Program {
  static void Capture(Form form,string path){Application.DoEvents();using(var bitmap=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(bitmap,new Rectangle(Point.Empty,bitmap.Size));bitmap.Save(path,System.Drawing.Imaging.ImageFormat.Png);}}
  [STAThread]static int Main(string[] args){try{var db=Database.Load();if(args.Length>0&&args[0]=="--self-test"){File.WriteAllText(args.Length>1?args[1]:"self-test.txt",Engine.Test(db)+"\r\n"+MechanicsTests.Run(db));return 0;}Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Fonts.Load();var form=new MainForm(db);if(args.Length>1&&args[0]=="--render-preview"){form.Shown+=(s,e)=>{form.Smoke();Capture(form,args[1]);var savedFighters=form.Fighters.Select(f=>f.Copy()).ToArray();var savedRules=form.Rules.Copy();form.Rules.Weather="비";form.Rules.WeatherTurns=3;form.Rules.Terrain="일렉트릭필드";form.Rules.TerrainTurns=4;form.Fighters[0].Status="마비";form.Fighters[1].Conditions.Reflect=3;form.RefreshView();Capture(form,args[1]+".active.png");form.Fighters=savedFighters;form.Rules=savedRules;form.RefreshView();using(var conditions=new ConditionsForm(db,form.Fighters[0],form.Fighters[1],form.Rules)){conditions.Show();Capture(conditions,args[1]+".conditions.png");conditions.Close();}using(var guide=new GuideForm(db)){guide.Show();Capture(guide,args[1]+".guide.png");guide.Close();}using(var editor=new FighterForm(db,form.Fighters[0],form.Fighters[1].Data.level,form.Rules)){editor.Show();Capture(editor,args[1]+".editor.png");editor.Close();}using(var settings=new RulesForm(form.Rules)){settings.Show();Capture(settings,args[1]+".settings.png");settings.Close();}using(var result=new ResultForm()){result.SetLog("TURN 01\r\n선데이의 파괴광선!\r\n잭 한마에게 297 대미지.");result.Show();Capture(result,args[1]+".log.png");result.Close();}form.Close();};}Application.Run(form);return 0;}catch(Exception ex){if(args.Length>0){File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"error.txt"),ex.ToString());return 1;}MessageBox.Show(ex.Message,"AA BATTLE 오류",MessageBoxButtons.OK,MessageBoxIcon.Error);return 1;}}
 }
}



