using System;
using System.Linq;
using System.Drawing;
using System.Collections.Generic;
using System.Windows.Forms;

namespace AABattle {
 public static class RuleBook {
  public const string StatusHelp="상태이상은 동시에 하나만 유지됩니다.\n\n화상: 물리 위력 1/2, 매 턴 최대 HP의 1/16 피해. 불꽃 타입은 새 화상에 면역. 근성은 물리 위력 감소를 무시합니다.\n\n독: 매 턴 최대 HP의 1/8 피해.\n맹독: 매 턴 1/16, 2/16, 3/16… 피해. 독·강철 타입은 독에 면역(부식 제외).\n\n마비: 속도 1/2. 행동 시 25% 확률로 행동 불가. 전기 타입은 면역.\n\n잠듦: 지정한 1–3회 행동을 쉬고 다음 행동에서 깨어납니다. 잠꼬대·코골기는 미구현입니다.\n\n얼음: 행동 전 20% 확률로 해동. 불꽃 공격을 직접 맞아도 해동. 얼음 타입은 면역, 쾌청에서는 새 결빙 방지.\n\n동상: 시트용 확장 상태. 특수 위력 1/2, 매 턴 HP 1/16 피해. 본가 9세대의 얼음과 별도로 표시합니다.\n\n상태변화는 상태이상과 중첩됩니다.\n혼란: 1–4회 행동, 약 1/3 확률로 위력40 자해. 타입·자속 없음.\n풀죽음: 해당 턴의 아직 하지 않은 행동만 차단.\n방어: 그 턴 상대 기술을 차단. 연속 성공 확률은 1, 1/3, 1/9…\n도발: 변화기 사용 제한.\n반동대기: 파괴광선·기가임팩트 명중 후 다음 행동을 쉬기.\n대타: 최대 HP의 1/4를 소모해 생성. 대타 파괴 시 남는 피해는 본체에 전이되지 않음. 소리·틈새포착은 관통.\n씨뿌리기: 상대 HP 1/8을 흡수. 풀 타입은 기술 자체에 면역.\n저주: 걸린 대상이 턴마다 HP 1/4 손실. 기술 '저주'의 타입별 발동은 수동.\n아쿠아링·뿌리박기: 매 턴 HP 1/16 회복. 뿌리박기는 접지.\n리플렉터·빛의장막: 싱글에서 물리·특수 피해 1/2. 급소·틈새포착은 무시.\n순풍: 속도 2배.\n\n숫자는 현재 턴을 포함한 남은 처리 횟수입니다. 이 테스트 빌드는 잔여 피해·회복 후 지속 턴을 차감합니다. 교대에 따른 상태 해제는 아직 자동화하지 않았습니다.";
  public const string WeatherHelp="날씨는 한 종류, 필드는 별도로 한 종류 유지됩니다. 기본 5턴이며 0턴 설정은 수동 유지입니다.\n\n쾌청 / 큰가뭄: 불꽃 1.5배. 일반 쾌청은 물 0.5배, 큰가뭄은 물 공격 자체 실패. 새로운 얼음 방지.\n비 / 강한 비: 물 1.5배. 일반 비는 불꽃 0.5배, 강한 비는 불꽃 공격 자체 실패.\n모래바람: 바위 타입 특방 1.5배. 바위·땅·강철 이외는 턴마다 HP 1/16 피해.\n눈: 얼음 타입 방어 1.5배. 날씨 피해 없음.\n싸라기눈: 이전 세대 날씨. 얼음 이외에 턴마다 HP 1/16 피해. 눈과 별개입니다.\n난기류: 비행 타입 때문에 생긴 약점을 상쇄. 다른 타입의 약점은 남습니다.\n날씨부정·에어록: 살아 있는 보유자가 있으면 날씨 효과를 일시 억제합니다.\n번개·폭풍: 비에서 필중, 쾌청에서 명중50. 눈보라: 눈·싸라기눈에서 필중.\n쓱쓱·엽록소·모래헤치기·눈치우기: 각각 비·쾌청·모래·눈에서 속도2배.\n\n필드는 기본적으로 땅에 닿은 포켓몬에게 적용됩니다.\n일렉트릭: 접지 사용자의 전기 위력1.3배, 접지 대상의 잠듦 방지.\n그래스: 접지 사용자의 풀 위력1.3배, 턴마다 접지 포켓몬 HP1/16 회복. 지진·땅고르기·매그니튜드가 접지 대상에게 주는 위력1/2.\n사이코: 접지 사용자의 에스퍼 위력1.3배, 접지 대상에게 오는 우선도+ 공격/변화기를 차단.\n미스트: 접지 대상에게 새 상태이상·혼란 방지, 드래곤 위력1/2. 기본 규칙에서는 페어리 강화 없음.\n시트 필드 보정 옵션: 기술 강화1.5배와 미스트의 페어리 강화를 추가로 사용.\n\n트릭룸: 동일 우선도에서 느린 쪽이 먼저 행동.\n중력: 비행·부유·풍선도 접지. 일반 명중 보정5/3.\n풍선·부유·비행은 보통 공중. 철구·뿌리박기·중력은 접지.\n\n특수 날씨를 만드는 특성의 등장·퇴장 연동, 날씨 도구의 8턴 연장, 모든 날씨 연계기, 지형 제거 기술은 아직 수동 판정입니다.";
  public const string TypeHelp="타입 상성은 첨부 시트의 20타입 표를 그대로 사용합니다. '다크', '???'와 3중 타입을 포함합니다.\n\n기본 공격 무효 관계\n노말 공격 → 고스트\n격투 공격 → 고스트\n독 공격 → 강철\n땅 공격 → 비행\n전기 공격 → 땅\n에스퍼 공격 → 악\n고스트 공격 → 노말\n드래곤 공격 → 페어리\n\n복합 타입은 배율을 곱하고, 무효가 하나라도 있으면 0배입니다. 시트의 복수 공격 타입은 가장 유리한 타입 배율을 채택합니다.\n\n타입에 따른 특수 면역\n불꽃: 새 화상 무효\n전기: 새 마비 무효\n얼음: 새 얼음·동상 무효\n독·강철: 새 독·맹독 무효(부식 예외)\n풀: 가루·포자, 씨뿌리기 무효\n악: 상대 짓궂은마음 변화기 무효\n고스트: 일반적인 교대 봉쇄 무시\n바위·땅·강철: 모래바람 피해 무효\n얼음: 싸라기눈 피해 무효\n\n일반 노말 변화기는 고스트에게도 적용될 수 있습니다. 공격 상성의 0배를 모든 변화기에 잘못 적용하지 않습니다. 전기자석파의 땅 타입 면역은 별도로 적용합니다.\n\n배짱: 고스트의 노말·격투 면역 무시.\n틀깨기·터보블레이즈·테라볼티지: 등록된 방어 특성의 공격 무효를 무시. 타입 자체 면역은 유지.\n부유·풍선: 땅 무효. 중력·철구·뿌리박기로 접지되면 무효가 해제됩니다.\n타오르는불꽃: 불꽃 흡수 후 불꽃 위력1.5배.\n축전·저수: 전기·물 무효와 HP1/4 회복.\n피뢰침·마중물: 전기·물 무효와 특공+1.\n전기엔진: 전기 무효와 속도+1.\n초식: 풀 무효와 공격+1.\n방음·방탄: 시트 태그에 기록된 소리·탄/볼에 면역.\n\n그 밖의 타입에는 위에 없는 전용 면역을 임의로 부여하지 않습니다.";
  public static string Scope(Database db){return "현재 기준\n기본 능력치·레벨 차·난수·급소2배는 원본 마개조 시트 기반. 일반 상태·날씨는 현대 싱글 규칙을 참고한 단계적 구현입니다. 완전한 본가 시뮬레이터는 아닙니다.\n\n자동 적용\n타입 무효, 등록된 특성의 면역·회복, 상태 행동 제한·턴말 피해, 날씨·필드, 방어·대타·도발·벽·순풍·혼란·씨뿌리기 등.\n\n트레이너 지령\n기술 행동과 함께 4식 1개와 지령 1개를 선언할 수 있습니다. 각 항목은 시합 중 1회입니다. 『돌아와!』만 교대 행동과 함께 선언하며 상대의 행동 후 교대합니다. 기본 4식·숙달/전개 6령과 선택 규칙인 『맞춰라!』·저격/회피 지령을 지원합니다.\n\n자동 변화기 목록\n"+string.Join(", ",db.moves.Where(m=>m.category=="변화"&&Mechanics.KnownMove(m)&&m.name!="날개쉬기").Select(m=>m.name).Distinct())+"\n\n등록된 공격 부가 효과\n파괴광선/기가임팩트의 반동대기, 화염방사/불대문자 화상, 10만볼트/번개 마비, 냉동빔/눈보라 얼음, 독찌르기/오물폭탄 독, 에어슬래시/스톤샤워/악의파동 풀죽음.\n\n기타 공격은 기본 위력 계산만 자동입니다. 기술 목록에 있다고 모든 기술 효과가 구현된 것은 아닙니다.\n\n지원 특성 (아래에 적힌 규칙만)\n"+string.Join(", ",Mechanics.KnownAbilities)+"\n\n지원 도구\n"+string.Join(", ",Mechanics.KnownItems)+"\n\n수동 처리\n지령 이외의 포텐셜, 미등록 특성·도구·기술 효과, 특성의 등장/퇴장 효과, PP, 모든 연속기, 충전기, 일반 반동·흡수, 혼란 예외, 설치기·봉쇄, 다인전. 지속시간·잔여 효과의 미세한 우선순위는 앞으로 확장합니다.\n\n근거\nPokemon Showdown 공개 구현 (2026-09-09 확인)\nhttps://github.com/smogon/pokemon-showdown/blob/master/data/typechart.ts\nhttps://github.com/smogon/pokemon-showdown/blob/master/data/conditions.ts\nhttps://github.com/smogon/pokemon-showdown/blob/master/data/moves.ts\nhttps://github.com/smogon/pokemon-showdown/blob/master/data/abilities.ts\n첨부된 슈퍼 마개조 계산기 Ver 3.617\n\n저장: 현재 세션만 유지. 되돌리기는 HP뿐 아니라 상태와 필드 지속 턴, 지령 사용 이력까지 복원합니다.";}
  public static string Summary(Fighter a,Fighter b,Rules r){var labels=a.Conditions.Labels(a).ToArray();return (labels.Length>0?string.Join(" / ",labels):"정상")+" · "+(Mechanics.Grounded(a,r)?"접지":"공중");}
  public static string Field(Rules r,Fighter[] f){return "날씨 "+r.Weather+(r.Weather!="없음"?" "+(r.WeatherTurns==0?"유지":r.WeatherTurns+"T"):"")+(r.Weather!="없음"&&Mechanics.Weather(f[0],f[1],r)=="없음"?" [효과 억제]":"")+"  /  "+r.Terrain+(r.Terrain!="없음"?" "+(r.TerrainTurns==0?"유지":r.TerrainTurns+"T"):"")+(r.TrickRoom>0?" / 트릭룸 "+r.TrickRoom+"T":"")+(r.Gravity>0?" / 중력 "+r.Gravity+"T":"");}
  public static string Report(Database db,Fighter a,Fighter b,Rules r){var cleared=a.Copy();cleared.Status="정상";var lines=new List<string>{a.Data.name+" — 현재 상태",Summary(a,b,r),"특성: "+(a.Data.ability.Length>0?a.Data.ability:"없음")+" / 도구: "+(a.Data.item.Length>0?a.Data.item:"없음"),"", "방어 상성 (타입만)"};foreach(double k in new[]{0.0,.125,.25,.5,2,4,8}){var names=db.types.Where(t=>Engine.Match(db,new[]{t},a.Data.types)==k).ToArray();if(names.Length>0)lines.Add("×"+k+": "+string.Join(", ",names));}lines.Add("\n새 상태이상 차단 사유");foreach(string status in Mechanics.Statuses.Skip(1)){string reason=Mechanics.StatusBlock(cleared,b,status,r);if(reason.Length>0)lines.Add(status+": "+reason);}lines.Add("\n상성표는 특성/도구를 제외한 기본값입니다. 실제 기술 무효 사유는 아래에 따로 계산합니다.");foreach(string name in b.Moves){var m=db.moves.FirstOrDefault(x=>x.name==name);if(m==null)continue;string block=Mechanics.TargetsOpponent(m)?Mechanics.Block(db,b,a,m,r):"자신/필드 대상";lines.Add(name+": "+(block.Length>0?block:"공격 상성 ×"+Mechanics.TypeEffect(db,b,a,m,r)));}lines.Add("\n"+StatusHelp);return string.Join("\n",lines);}
 }
 class ConditionsForm:Form {
  public Fighter Value;Fighter original,opponent;Rules rules;Database db;ComboBox major;CheckBox force;NumericUpDown sleep,toxic;Dictionary<string,NumericUpDown> numbers=new Dictionary<string,NumericUpDown>();Dictionary<string,CheckBox> flags=new Dictionary<string,CheckBox>();LogView info;
  public ConditionsForm(Database data,Fighter f,Fighter other,Rules r){db=data;original=f;opponent=other;rules=r;Value=f.Copy();Text=f.Data.name+" · 상태 / 무효 판정";Size=new Size(1030,730);MinimumSize=new Size(860,650);StartPosition=FormStartPosition.CenterParent;BackColor=Color.White;Font=Theme.UI();var split=new SplitContainer{Size=new Size(1000,620),Dock=DockStyle.Fill,SplitterDistance=400,FixedPanel=FixedPanel.Panel1};split.Panel1.AutoScroll=true;info=new LogView{Dock=DockStyle.Fill};split.Panel2.Padding=new Padding(18,10,18,10);split.Panel2.Controls.Add(info);var t=Theme.Table();major=Theme.Combo(Mechanics.Statuses,f.Status);Theme.Row(t,"상태이상",major);sleep=Theme.Number(f.Conditions.SleepTurns,0,3);toxic=Theme.Number(f.Conditions.ToxicStage,1,15);Theme.Row(t,"남은 수면 행동",sleep);Theme.Row(t,"맹독 누적 단계",toxic);force=new CheckBox{Text="수동 강제 적용",Font=new Font("맑은 고딕",10),Dock=DockStyle.Fill};Theme.Row(t,"면역 예외",force);
   AddNum(t,"혼란",f.Conditions.Confusion,4);AddNum(t,"도발",f.Conditions.Taunt,8);AddNum(t,"리플렉터",f.Conditions.Reflect,8);AddNum(t,"빛의장막",f.Conditions.LightScreen,8);AddNum(t,"순풍",f.Conditions.Tailwind,8);AddNum(t,"대타 HP",f.Conditions.Substitute,Engine.Stats(f,other.Data.level,r)[0]);
   AddFlag(t,"방어",f.Conditions.Protect);AddFlag(t,"풀죽음",f.Conditions.Flinch);AddFlag(t,"반동대기",f.Conditions.Recharge);AddFlag(t,"씨뿌리기",f.Conditions.Seed);AddFlag(t,"저주",f.Conditions.Curse);AddFlag(t,"아쿠아링",f.Conditions.AquaRing);AddFlag(t,"뿌리박기",f.Conditions.Ingrain);AddFlag(t,"불꽃 흡수 강화",f.Conditions.FlashFire);AddFlag(t,"풍선 터짐",f.Conditions.BalloonPopped);split.Panel1.Controls.Add(t);
   var buttons=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=64,Padding=new Padding(12),FlowDirection=FlowDirection.RightToLeft};var apply=new FlatButton{Text="상태 적용",Primary=true,Size=new Size(140,38)};var cancel=new FlatButton{Text="취소",Size=new Size(90,38),DialogResult=DialogResult.Cancel};buttons.Controls.AddRange(new Control[]{apply,cancel});Controls.Add(split);Controls.Add(buttons);CancelButton=cancel;
   major.SelectedIndexChanged+=(s,e)=>Preview();foreach(var n in numbers.Values)n.ValueChanged+=(s,e)=>Preview();foreach(var c in flags.Values)c.CheckedChanged+=(s,e)=>Preview();sleep.ValueChanged+=(s,e)=>Preview();toxic.ValueChanged+=(s,e)=>Preview();apply.Click+=(s,e)=>{var draft=Read();if(draft.Status!=original.Status&&draft.Status!="정상"&&!force.Checked){var clear=draft.Copy();clear.Status="정상";string reason=Mechanics.StatusBlock(clear,opponent,draft.Status,rules);if(reason.Length>0){MessageBox.Show(this,reason+"\n예외 판정이라면 '수동 강제 적용'을 선택하세요.","상태이상 무효");return;}}Value=draft;DialogResult=DialogResult.OK;Close();};Preview();}
  void AddNum(TableLayoutPanel t,string key,int value,int max){var n=Theme.Number(value,0,max);numbers[key]=n;Theme.Row(t,key+ (key=="대타 HP"?"":" 남은 턴"),n);}
  void AddFlag(TableLayoutPanel t,string key,bool value){var c=new CheckBox{Text="적용",Checked=value,Font=new Font("맑은 고딕",10),Dock=DockStyle.Fill};flags[key]=c;Theme.Row(t,key,c);}
  Fighter Read(){var f=original.Copy();f.Status=(string)major.SelectedItem;var c=f.Conditions;c.SleepTurns=(int)sleep.Value;c.ToxicStage=(int)toxic.Value;c.Confusion=(int)numbers["혼란"].Value;c.Taunt=(int)numbers["도발"].Value;c.Reflect=(int)numbers["리플렉터"].Value;c.LightScreen=(int)numbers["빛의장막"].Value;c.Tailwind=(int)numbers["순풍"].Value;c.Substitute=(int)numbers["대타 HP"].Value;c.Protect=flags["방어"].Checked;c.Flinch=flags["풀죽음"].Checked;c.Recharge=flags["반동대기"].Checked;c.Seed=flags["씨뿌리기"].Checked;c.Curse=flags["저주"].Checked;c.AquaRing=flags["아쿠아링"].Checked;c.Ingrain=flags["뿌리박기"].Checked;c.FlashFire=flags["불꽃 흡수 강화"].Checked;c.BalloonPopped=flags["풍선 터짐"].Checked;return f;}
  void Preview(){info.SetLog(RuleBook.Report(db,Read(),opponent,rules));}
 }
 class RulesForm:Form {
  public Rules Value;public RulesForm(Rules r){Value=r.Copy();Text="날씨 / 필드 / 계산 설정";Size=new Size(920,740);MinimumSize=new Size(800,650);StartPosition=FormStartPosition.CenterParent;Font=Theme.UI();BackColor=Color.White;var split=new SplitContainer{Size=new Size(900,620),Dock=DockStyle.Fill,SplitterDistance=400,FixedPanel=FixedPanel.Panel1};split.Panel1.AutoScroll=true;var details=new LogView{Dock=DockStyle.Fill};details.SetLog(RuleBook.WeatherHelp);split.Panel2.Padding=new Padding(16);split.Panel2.Controls.Add(details);var t=Theme.Table();var weather=Theme.Combo(Mechanics.Weathers,r.Weather);var terrain=Theme.Combo(Mechanics.Terrains,r.Terrain);var wt=Theme.Number(r.WeatherTurns,0,99);var tt=Theme.Number(r.TerrainTurns,0,99);var trick=Theme.Number(r.TrickRoom,0,99);var gravity=Theme.Number(r.Gravity,0,99);var critical=Check("급소 2배 (시트)",r.Critical);var hp=Check("HP 레벨 보정",r.HPCorrection);var sheet=Check("시트 필드 배율",r.SheetTerrain);var bonus=Theme.Number((decimal)r.PowerBonus,-999,999);var power=Theme.Number((decimal)r.PowerMultiplier,0,100,2);var damage=Theme.Number((decimal)r.DamageMultiplier,0,100,2);var stab=Theme.Number((decimal)r.Stab,0,10,2);var correction=Theme.Number((decimal)r.LevelCorrection,0,10,2);
   Theme.Row(t,"날씨",weather);Theme.Row(t,"날씨 잔여 턴",wt);Theme.Row(t,"필드",terrain);Theme.Row(t,"필드 잔여 턴",tt);Theme.Row(t,"트릭룸 잔여 턴",trick);Theme.Row(t,"중력 잔여 턴",gravity);Theme.Row(t,"급소",critical);Theme.Row(t,"필드 규칙",sheet);Theme.Row(t,"위력 고정치",bonus);Theme.Row(t,"위력 배율",power);Theme.Row(t,"대미지 배율",damage);Theme.Row(t,"자속 (0=자동)",stab);Theme.Row(t,"레벨 보정 %",correction);Theme.Row(t,"체력 보정",hp);split.Panel1.Controls.Add(t);Controls.Add(split);var apply=new FlatButton{Text="적용",Primary=true,Dock=DockStyle.Bottom,Height=48};Controls.Add(apply);weather.SelectedIndexChanged+=(s,e)=>{wt.Value=new[]{"큰가뭄","강한 비","난기류"}.Contains((string)weather.SelectedItem)?0:5;};terrain.SelectedIndexChanged+=(s,e)=>tt.Value=5;apply.Click+=(s,e)=>{Value=new Rules{Weather=(string)weather.SelectedItem,Terrain=(string)terrain.SelectedItem,WeatherTurns=(int)wt.Value,TerrainTurns=(int)tt.Value,TrickRoom=(int)trick.Value,Gravity=(int)gravity.Value,Critical=critical.Checked,HPCorrection=hp.Checked,SheetTerrain=sheet.Checked,PowerBonus=(double)bonus.Value,PowerMultiplier=(double)power.Value,DamageMultiplier=(double)damage.Value,Stab=(double)stab.Value,LevelCorrection=(double)correction.Value};DialogResult=DialogResult.OK;Close();};}
  static CheckBox Check(string text,bool value){return new CheckBox{Text=text,Checked=value,Font=new Font("맑은 고딕",10),Dock=DockStyle.Fill};}
 }
 class GuideForm:Form {
  public GuideForm(Database db){Text="배틀 규칙 / 타입 상성표";Size=new Size(1060,750);MinimumSize=new Size(850,600);StartPosition=FormStartPosition.CenterParent;Font=new Font("맑은 고딕",10);var tabs=new TabControl{Dock=DockStyle.Fill};Controls.Add(tabs);var chart=new TabPage("상성표");tabs.TabPages.Add(chart);var grid=new DataGridView{Dock=DockStyle.Fill,ReadOnly=true,AllowUserToAddRows=false,AllowUserToDeleteRows=false,RowHeadersWidth=90,BackgroundColor=Color.White,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.None,EnableHeadersVisualStyles=false,AllowUserToOrderColumns=false};grid.ColumnHeadersDefaultCellStyle.BackColor=Color.Black;grid.ColumnHeadersDefaultCellStyle.ForeColor=Color.White;grid.DefaultCellStyle.SelectionBackColor=Color.Black;grid.DefaultCellStyle.SelectionForeColor=Color.White;foreach(string type in db.types)grid.Columns.Add(type,type);foreach(DataGridViewColumn c in grid.Columns)c.Width=62;foreach(string def in db.types){int i=grid.Rows.Add(db.types.Select(at=>(object)(db.chart[def][at]==0?"무효":db.chart[def][at].ToString())).ToArray());grid.Rows[i].HeaderCell.Value=def;foreach(DataGridViewCell cell in grid.Rows[i].Cells)if((string)cell.Value=="무효"){cell.Style.BackColor=Color.Black;cell.Style.ForeColor=Color.White;}}chart.Controls.Add(grid);var label=new Label{Text="열 = 공격 타입 / 행 = 방어 타입 · 첨부 시트 상성표 · 흑색 칸은 무효",Dock=DockStyle.Top,Height=35};chart.Controls.Add(label);Add(tabs,"타입 면역",RuleBook.TypeHelp);Add(tabs,"날씨·필드",RuleBook.WeatherHelp);Add(tabs,"상태 규칙",RuleBook.StatusHelp);Add(tabs,"자동 / 수동 범위",RuleBook.Scope(db));}
  static void Add(TabControl tabs,string title,string text){var page=new TabPage(title){Padding=new Padding(18),BackColor=Color.White};var view=new LogView{Dock=DockStyle.Fill};view.SetLog(text);page.Controls.Add(view);tabs.TabPages.Add(page);}
 }
}
