using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Drawing;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Windows.Forms;
using System.Web.Script.Serialization;

namespace AABattle {
 public class EditorProject {public string format="aa-battle-data-v1";public List<TrainerRecord> trainers=new List<TrainerRecord>();public List<PokemonRecord> pokemon=new List<PokemonRecord>();}
 public class AptitudeRecord {public string rank="",description="";}
 public class StatsRecord {public int hp,attack,defense,spAttack,spDefense,speed;public int Total(){return hp+attack+defense+spAttack+spDefense+speed;}}
 public class PotentialRecord {public bool enabled=true;public string slot="",name="",activation="",uses="",trigger="",effect="",raw="";}
 public class TrainerRecord {public string name="",origin="";public AptitudeRecord command=new AptitudeRecord(),training=new AptitudeRecord(),leadership=new AptitudeRecord(),ability=new AptitudeRecord();public List<PotentialRecord> potentials=new List<PotentialRecord>();}
 public class PokemonRecord {public string name="",ability="",model="",item="",asciiArt="";public int level=100;public List<string> types=new List<string>(),moves=new List<string>();public StatsRecord stats=new StatsRecord();public List<PotentialRecord> potentials=new List<PotentialRecord>();}
 public static class EditorBridge {
  public static Pokemon ToPokemon(PokemonRecord source,Database db,out string warning){if(source==null)throw new Exception("포켓몬을 선택하세요.");int[] bases={source.stats.hp,source.stats.attack,source.stats.defense,source.stats.spAttack,source.stats.spDefense,source.stats.speed};if(bases.Any(x=>x<=0))throw new Exception("6개 종족값을 모두 1 이상 입력하세요.");var types=source.types.Where(x=>db.types.Contains(x)).Distinct().ToArray();var badTypes=source.types.Where(x=>!db.types.Contains(x)).Distinct().ToArray();if(types.Length==0)throw new Exception("등록된 타입을 하나 이상 입력하세요."+(badTypes.Length>0?" 미등록: "+string.Join(", ",badTypes):""));var moves=source.moves.Where(x=>db.moves.Any(m=>m.name==x)).Distinct().Take(4).ToArray();var badMoves=source.moves.Where(x=>!db.moves.Any(m=>m.name==x)).Distinct().ToArray();if(moves.Length==0)throw new Exception("계산기에 등록된 기술을 하나 이상 입력하세요."+(badMoves.Length>0?" 미등록: "+string.Join(", ",badMoves):""));warning=(badTypes.Length>0?"미등록 타입 제외: "+string.Join(", ",badTypes)+". ":"")+(badMoves.Length>0?"미등록 기술 제외: "+string.Join(", ",badMoves)+".":"");return new Pokemon{id="editor",team="팀 편집기",name=source.name.Length>0?source.name:"이름 없는 포켓몬",ability=source.ability,item=source.item,level=source.level,types=types,moves=moves,@base=bases,iv=new[]{31,31,31,31,31,31},potentials=source.potentials.Where(x=>x.enabled&&x.name.Length>0).Select(x=>new Potential{id=x.slot,name=x.name,description=x.effect.Length>0?x.effect:x.raw,triggers=x.trigger.Length>0?new[]{x.trigger}:new string[0]}).ToArray()};}
  public static int[] PreviewStats(PokemonRecord p){int l=Math.Max(1,p.level);int[] b={p.stats.hp,p.stats.attack,p.stats.defense,p.stats.spAttack,p.stats.spDefense,p.stats.speed};return b.Select((x,i)=>i==0?(int)Math.Floor((x*2+31)*l/100.0)+l+10:(int)Math.Floor((x*2+31)*l/100.0)+5).ToArray();}
 }

 static class EditorTemplate {
  static PotentialRecord P(string name,string activation,string uses,string trigger,string effect){return new PotentialRecord{slot="지령",name=name,activation=activation,uses=uses,trigger=trigger,effect=effect,raw=(uses.Length>0?uses+"/":"")+(activation.Length>0?activation+"/":"")+effect};}
  public static List<PotentialRecord> BaseOrders(){return new List<PotentialRecord>{P("물러나！","선행","1/시","상대가 아군 1체에게 물리 기술을 사용할 때","그 한 번의 물리 공격을 회피시킨다."),P("피해라！","선행","1/시","상대가 아군 1체에게 특수 기술을 사용할 때","그 한 번의 특수 공격을 회피시킨다."),P("돌아와！","임의","1/시","아군이 통상 교대할 때","상대의 행동 후에 교대할 아군을 필드에 낸다."),P("버텨라！","임의","1/시","아군 1체가 상대 기술의 대미지를 받을 때","그 한 번의 대미지를 반감하고 반드시 버틴다.")};}
  static readonly string[] Stats={"공격","방어","특공","특방","민첩","회복"};
  public static List<PotentialRecord> Orders(bool deploy){var list=BaseOrders();foreach(string stat in Stats){string target=stat=="민첩"?"속도":stat;string name=(deploy?"전개 ":"숙달 ")+stat+" 지령";string effect=stat=="회복"?(deploy?"행동을 스킵하고 아군 1체의 체력을 1/2 회복한다.":"아군 1체의 체력을 1/4 회복한다."):(deploy?"1T 동안 아군 1체의 「"+target+"」가 2배가 된다.":"아군 1체의 「"+target+"」을 1랭크 올린다.");list.Add(P(name,"T시","1/시","트레이너가 턴 중 지령을 사용했을 때",effect));}return list;}
  public static List<PotentialRecord> AimOrders(){var list=new List<PotentialRecord>();foreach(bool deploy in new[]{false,true})foreach(string stat in new[]{"저격","회피"}){string target=stat=="저격"?"명중":"회피";list.Add(P((deploy?"전개 ":"숙달 ")+stat+" 지령","T시","1/시","트레이너가 턴 중 지령을 사용했을 때",deploy?"1T 동안 아군 1체의 「"+target+"」이 2배가 된다.":"아군 1체의 「"+target+"」을 1랭크 올린다."));}return list;}
  public static List<PotentialRecord> PokemonSlots(){return new[]{"역할","분류","주인","계제 ①","계제 ②","계제 ③","계제 ④","속별","유대","선","회피","내성","격","범용","부수","특권","PT","전용"}.Select(x=>new PotentialRecord{slot=x}).ToList();}
  public static PotentialRecord Parse(string line,string defaultSlot){var p=new PotentialRecord{slot=defaultSlot,raw=line.Trim()};var m=Regex.Match(line,@"『([^』]+)』\s*…?\s*(.*)");if(!m.Success)return p;p.name=m.Groups[1].Value.Trim();string body=m.Groups[2].Value.Trim();var uses=Regex.Match(body,@"([0-9０-９]+\s*/\s*(?:시|시합|선발|턴))");if(uses.Success){p.uses=uses.Groups[1].Value;body=body.Remove(uses.Index,uses.Length).Trim(' ','/');}foreach(string mode in new[]{"선행","임의","자동","T시","Ｔ시"})if(body.Contains(mode)){p.activation=mode.Replace('Ｔ','T');body=body.Replace(mode,"").Trim(' ','/');break;}var condition=Regex.Match(body,@"^(.+?(?:때|경우|동안|라면|있으면|없으면|시))[,、，]?\s*(.*)$");if(condition.Success&&condition.Groups[2].Value.Length>0){p.trigger=condition.Groups[1].Value;p.effect=condition.Groups[2].Value;}else{p.trigger=p.activation=="선행"?"선행 선언 시":p.activation=="T시"?"턴 중 선언 시":"";p.effect=body;}return p;}
 }

 class DataEditorForm:Form {
  const int Some=100;
  EditorProject project;string path="";bool dirty,loading,allowClose;Action<PokemonRecord,int> sendToBattle;TreeView tree;TabControl tabs;Label fileLabel,selectionLabel,statPreview;DataGridView potentials;TextBox preview,aa,tName,tOrigin,pName,pAbility,pModel,pItem,pTypes,pMoves;NumericUpDown pLevel;TextBox[] aptRank=new TextBox[4],aptDesc=new TextBox[4];NumericUpDown[] stats=new NumericUpDown[6];
  object Current {get{return tree.SelectedNode==null?null:tree.SelectedNode.Tag;}}
  public DataEditorForm():this(null){}
  public DataEditorForm(Action<PokemonRecord,int> sender){sendToBattle=sender;Text="AA BATTLE · 데이터 편집기";Size=new Size(1280,820);MinimumSize=new Size(1040,700);StartPosition=FormStartPosition.CenterScreen;BackColor=Color.White;Font=new Font("맑은 고딕",10);Build();NewProject();}
  FlatButton Button(string text,int width,Action click){var b=new FlatButton{Text=text,Size=new Size(width,36),Font=Theme.UI(8)};b.Click+=(s,e)=>click();return b;}
  void Build(){var top=new FlowLayoutPanel{Dock=DockStyle.Top,Height=54,Padding=new Padding(12,8,8,6),BackColor=Color.White,WrapContents=false};top.Controls.Add(Button("새 데이터",88,NewProject));top.Controls.Add(Button("열기",70,Open));top.Controls.Add(Button("저장",70,Save));top.Controls.Add(Button("다른 이름",92,SaveAs));top.Controls.Add(Button("트레이너 +",100,AddTrainer));top.Controls.Add(Button("포켓몬 +",90,AddPokemon));top.Controls.Add(Button("삭제",70,DeleteCurrent));fileLabel=Theme.Label("",34);fileLabel.Width=360;fileLabel.Dock=DockStyle.None;fileLabel.Margin=new Padding(18,1,0,0);top.Controls.Add(fileLabel);Controls.Add(top);var split=new SplitContainer{Dock=DockStyle.Fill,SplitterDistance=245,FixedPanel=FixedPanel.Panel1,BackColor=Color.White};Controls.Add(split);split.BringToFront();tree=new TreeView{Dock=DockStyle.Fill,Font=new Font("맑은 고딕",10),BorderStyle=BorderStyle.FixedSingle,HideSelection=false};tree.AfterSelect+=(s,e)=>LoadCurrent();split.Panel1.Padding=new Padding(12);split.Panel1.Controls.Add(tree);tabs=new TabControl{Dock=DockStyle.Fill,Font=new Font("맑은 고딕",10)};split.Panel2.Padding=new Padding(0,12,12,12);split.Panel2.Controls.Add(tabs);tabs.SelectedIndexChanged+=(s,e)=>{if(tabs.SelectedTab!=null&&tabs.SelectedTab.Text=="시트 미리보기")RefreshPreview();};BuildTrainerTab();BuildPokemonTab();BuildPotentialTab();BuildPreviewTab();}
  TextBox Box(bool multiline=false){return new TextBox{Dock=DockStyle.Fill,Font=new Font("맑은 고딕",10),Multiline=multiline,ScrollBars=multiline?ScrollBars.Vertical:ScrollBars.None};}
  void Changed(object s,EventArgs e){if(!loading){SaveCurrent();dirty=true;UpdateTitle();UpdateStatPreview();}}
  void Hook(Control c){if(c is TextBox)((TextBox)c).TextChanged+=Changed;else if(c is NumericUpDown)((NumericUpDown)c).ValueChanged+=Changed;}
  TabPage Page(string name){var p=new TabPage(name){BackColor=Color.White,Padding=new Padding(8)};tabs.TabPages.Add(p);return p;}
  void BuildTrainerTab(){var page=Page("트레이너");var panel=new Panel{Dock=DockStyle.Fill,AutoScroll=true};page.Controls.Add(panel);var t=Theme.Table();panel.Controls.Add(t);tName=Box();tOrigin=Box();Theme.Row(t,"이름",tName);Theme.Row(t,"출신",tOrigin);string[] labels={"지시","육성","통솔","능력"};for(int i=0;i<4;i++){aptRank[i]=Box();aptDesc[i]=Box();Theme.Row(t,labels[i]+" 랭크",aptRank[i]);Theme.Row(t,labels[i]+" 평가",aptDesc[i]);Hook(aptRank[i]);Hook(aptDesc[i]);}Hook(tName);Hook(tOrigin);Theme.Row(t,"지령",Theme.Label("지령 프리셋은 [포텐셜] 탭에서 추가합니다.",40));}
  void BuildPokemonTab(){var page=Page("포켓몬");var sendBar=new FlowLayoutPanel{Dock=DockStyle.Top,Height=48,Padding=new Padding(5)};var left=Button("왼쪽 배틀 슬롯",130,()=>SendCurrent(0));var right=Button("오른쪽 배틀 슬롯",140,()=>SendCurrent(1));left.Enabled=right.Enabled=sendToBattle!=null;var note=Theme.Label("입력값은 종족값 · 적용 시 IV31 / EV0 / 성격 무보정",34);note.Width=490;note.Dock=DockStyle.None;sendBar.Controls.Add(left);sendBar.Controls.Add(right);sendBar.Controls.Add(note);var split=new SplitContainer{Dock=DockStyle.Fill,SplitterDistance=520};page.Controls.Add(split);page.Controls.Add(sendBar);split.BringToFront();var panel=new Panel{Dock=DockStyle.Fill,AutoScroll=true};split.Panel1.Controls.Add(panel);var t=Theme.Table();panel.Controls.Add(t);pName=Box();pTypes=Box();pAbility=Box();pModel=Box();pItem=Box();pMoves=Box(true);pLevel=Theme.Number(Some,1,999);Theme.Row(t,"이름",pName);Theme.Row(t,"타입 (, 구분)",pTypes);Theme.Row(t,"특성",pAbility);Theme.Row(t,"모델",pModel);Theme.Row(t,"레벨",pLevel);Theme.Row(t,"소지품",pItem);Theme.Row(t,"기술 (한 줄 하나)",pMoves);string[] labels={"체력","공격","방어","특공","특방","속도"};for(int i=0;i<6;i++){stats[i]=Theme.Number(0,0,9999);Theme.Row(t,labels[i]+" 종족값",stats[i]);Hook(stats[i]);}statPreview=Theme.Label("",40);statPreview.Font=new Font("맑은 고딕",9);Theme.Row(t,"실능력치 참고",statPreview);foreach(Control c in new Control[]{pName,pTypes,pAbility,pModel,pLevel,pItem,pMoves})Hook(c);var aaPanel=new Panel{Dock=DockStyle.Fill,Padding=new Padding(10)};split.Panel2.Controls.Add(aaPanel);aa=Box(true);aa.WordWrap=false;aa.Font=new Font("Consolas",9);aaPanel.Controls.Add(aa);aaPanel.Controls.Add(Theme.Label("아스키아트",34));aa.TextChanged+=Changed;}
  void BuildPotentialTab(){var page=Page("포텐셜");var top=new FlowLayoutPanel{Dock=DockStyle.Top,Height=88,Padding=new Padding(5),WrapContents=true};top.Controls.Add(Button("빈 포텐셜 +",105,()=>AddPotential(new PotentialRecord())));top.Controls.Add(Button("포켓몬 슬롯 틀",115,AddPokemonSlots));top.Controls.Add(Button("기본4 + 숙달6",125,()=>AddOrders(false)));top.Controls.Add(Button("기본4 + 전개6",125,()=>AddOrders(true)));top.Controls.Add(Button("저격·회피 후보",125,AddAimOrders));top.Controls.Add(Button("클립보드 원문",125,PastePotentials));top.Controls.Add(Button("선택 행 삭제",105,DeletePotential));selectionLabel=Theme.Label("",32);selectionLabel.Width=380;selectionLabel.Dock=DockStyle.None;top.Controls.Add(selectionLabel);page.Controls.Add(top);potentials=new DataGridView{Dock=DockStyle.Fill,BackgroundColor=Color.White,BorderStyle=BorderStyle.FixedSingle,AllowUserToAddRows=true,AllowUserToDeleteRows=true,RowHeadersWidth=38,AutoSizeRowsMode=DataGridViewAutoSizeRowsMode.AllCells,DefaultCellStyle=new DataGridViewCellStyle{WrapMode=DataGridViewTriState.True,Font=new Font("맑은 고딕",9)},ColumnHeadersHeight=36};potentials.Columns.Add(new DataGridViewCheckBoxColumn{Name="enabled",HeaderText="사용",Width=45});AddCol("slot","분류/슬롯",82);AddCol("name","이름",155);AddCol("activation","발동",65);AddCol("uses","제한",62);AddCol("trigger","트리거 / 조건",250);AddCol("effect","효과",330);AddCol("raw","원문",330);potentials.CellValueChanged+=(s,e)=>GridChanged();potentials.UserDeletedRow+=(s,e)=>GridChanged();page.Controls.Add(potentials);potentials.BringToFront();}
  void AddCol(string name,string title,int width){potentials.Columns.Add(new DataGridViewTextBoxColumn{Name=name,HeaderText=title,Width=width,SortMode=DataGridViewColumnSortMode.NotSortable});}
  void BuildPreviewTab(){var page=Page("시트 미리보기");var top=new FlowLayoutPanel{Dock=DockStyle.Top,Height=50,Padding=new Padding(5)};top.Controls.Add(Button("새로고침",90,RefreshPreview));top.Controls.Add(Button("클립보드 복사",120,()=>{RefreshPreview();Clipboard.SetText(preview.Text);}));preview=new TextBox{Dock=DockStyle.Fill,ReadOnly=true,Multiline=true,ScrollBars=ScrollBars.Both,WordWrap=false,Font=new Font("맑은 고딕",10),BackColor=Color.White,BorderStyle=BorderStyle.FixedSingle};page.Controls.Add(preview);page.Controls.Add(top);preview.BringToFront();}
  void GridChanged(){if(loading)return;SaveCurrent();dirty=true;UpdateTitle();}
  void NewProject(){if(!DiscardOkay())return;project=new EditorProject();project.trainers.Add(new TrainerRecord());project.pokemon.Add(new PokemonRecord());path="";dirty=false;RefreshTree(project.trainers[0]);}
  void RefreshTree(object select){loading=true;tree.Nodes.Clear();var trainers=tree.Nodes.Add("트레이너");foreach(var x in project.trainers){var n=trainers.Nodes.Add(x.name.Length>0?x.name:"(이름 없음)");n.Tag=x;}var mons=tree.Nodes.Add("포켓몬");foreach(var x in project.pokemon){var n=mons.Nodes.Add(x.name.Length>0?x.name:"(이름 없음)");n.Tag=x;}trainers.Expand();mons.Expand();tree.SelectedNode=tree.Nodes.Cast<TreeNode>().SelectMany(n=>n.Nodes.Cast<TreeNode>()).FirstOrDefault(n=>Object.ReferenceEquals(n.Tag,select));loading=false;LoadCurrent();UpdateTitle();}
  void AddTrainer(){SaveCurrent();var x=new TrainerRecord();project.trainers.Add(x);dirty=true;RefreshTree(x);}void AddPokemon(){SaveCurrent();var x=new PokemonRecord();project.pokemon.Add(x);dirty=true;RefreshTree(x);}
  void DeleteCurrent(){var x=Current;if(x==null)return;if(MessageBox.Show(this,"선택 데이터를 삭제할까요?","삭제",MessageBoxButtons.YesNo)!=DialogResult.Yes)return;if(x is TrainerRecord)project.trainers.Remove((TrainerRecord)x);else project.pokemon.Remove((PokemonRecord)x);dirty=true;RefreshTree(project.trainers.Cast<object>().Concat(project.pokemon).FirstOrDefault());}
  void LoadCurrent(){if(loading)return;loading=true;var trainer=Current as TrainerRecord;var pokemon=Current as PokemonRecord;tabs.TabPages[0].Enabled=trainer!=null;tabs.TabPages[1].Enabled=pokemon!=null;if(trainer!=null){tName.Text=trainer.name;tOrigin.Text=trainer.origin;var a=new[]{trainer.command,trainer.training,trainer.leadership,trainer.ability};for(int i=0;i<4;i++){aptRank[i].Text=a[i].rank;aptDesc[i].Text=a[i].description;}FillPotentials(trainer.potentials);selectionLabel.Text="트레이너 · "+(trainer.name.Length>0?trainer.name:"이름 없음");tabs.SelectedIndex=0;}else if(pokemon!=null){pName.Text=pokemon.name;pTypes.Text=string.Join(", ",pokemon.types);pAbility.Text=pokemon.ability;pModel.Text=pokemon.model;pLevel.Value=Math.Max(pLevel.Minimum,Math.Min(pLevel.Maximum,pokemon.level));pItem.Text=pokemon.item;pMoves.Text=string.Join("\r\n",pokemon.moves);aa.Text=pokemon.asciiArt;int[] v={pokemon.stats.hp,pokemon.stats.attack,pokemon.stats.defense,pokemon.stats.spAttack,pokemon.stats.spDefense,pokemon.stats.speed};for(int i=0;i<6;i++)stats[i].Value=Math.Min(stats[i].Maximum,v[i]);FillPotentials(pokemon.potentials);selectionLabel.Text="포켓몬 · "+(pokemon.name.Length>0?pokemon.name:"이름 없음");tabs.SelectedIndex=1;}else{potentials.Rows.Clear();selectionLabel.Text="왼쪽에서 데이터를 선택하세요.";}loading=false;UpdateStatPreview();}
  List<PotentialRecord> CurrentPotentials(){var t=Current as TrainerRecord;if(t!=null)return t.potentials;var p=Current as PokemonRecord;return p==null?null:p.potentials;}
  void FillPotentials(List<PotentialRecord> list){potentials.Rows.Clear();foreach(var p in list)potentials.Rows.Add(p.enabled,p.slot,p.name,p.activation,p.uses,p.trigger,p.effect,p.raw);}
  string Cell(DataGridViewRow r,string name){var v=r.Cells[name].Value;return v==null?"":v.ToString().Trim();}
  void SaveCurrent(){if(loading||Current==null)return;var trainer=Current as TrainerRecord;var pokemon=Current as PokemonRecord;if(trainer!=null){trainer.name=tName.Text.Trim();trainer.origin=tOrigin.Text.Trim();var a=new[]{trainer.command,trainer.training,trainer.leadership,trainer.ability};for(int i=0;i<4;i++){a[i].rank=aptRank[i].Text.Trim();a[i].description=aptDesc[i].Text.Trim();}}else if(pokemon!=null){pokemon.name=pName.Text.Trim();pokemon.types=pTypes.Text.Split(new[]{',','/','\r','\n'},StringSplitOptions.RemoveEmptyEntries).Select(x=>x.Trim()).Where(x=>x.Length>0).ToList();pokemon.ability=pAbility.Text.Trim();pokemon.model=pModel.Text.Trim();pokemon.level=(int)pLevel.Value;pokemon.item=pItem.Text.Trim();pokemon.moves=pMoves.Lines.Select(x=>x.Trim()).Where(x=>x.Length>0).ToList();pokemon.asciiArt=aa.Text;pokemon.stats.hp=(int)stats[0].Value;pokemon.stats.attack=(int)stats[1].Value;pokemon.stats.defense=(int)stats[2].Value;pokemon.stats.spAttack=(int)stats[3].Value;pokemon.stats.spDefense=(int)stats[4].Value;pokemon.stats.speed=(int)stats[5].Value;}var list=CurrentPotentials();if(list!=null){list.Clear();foreach(DataGridViewRow row in potentials.Rows)if(!row.IsNewRow&&(Cell(row,"name").Length>0||Cell(row,"slot").Length>0)){var value=row.Cells["enabled"].Value;list.Add(new PotentialRecord{enabled=value==null||Convert.ToBoolean(value),slot=Cell(row,"slot"),name=Cell(row,"name"),activation=Cell(row,"activation"),uses=Cell(row,"uses"),trigger=Cell(row,"trigger"),effect=Cell(row,"effect"),raw=Cell(row,"raw")});}}if(tree.SelectedNode!=null)tree.SelectedNode.Text=trainer!=null?(trainer.name.Length>0?trainer.name:"(이름 없음)"):(pokemon.name.Length>0?pokemon.name:"(이름 없음)");}
  void UpdateStatPreview(){var p=Current as PokemonRecord;if(statPreview==null||p==null){if(statPreview!=null)statPreview.Text="";return;}int[] value=EditorBridge.PreviewStats(p);statPreview.Text="동레벨 · IV31 / EV0 / 중립:  "+string.Join(" / ",value);}
  void SendCurrent(int side){SaveCurrent();var p=Current as PokemonRecord;if(p==null||sendToBattle==null)return;try{sendToBattle(p,side);}catch(Exception ex){MessageBox.Show(this,ex.Message,"배틀 슬롯 적용 실패");}}
  void AddPotential(PotentialRecord p){var list=CurrentPotentials();if(list==null){MessageBox.Show(this,"트레이너 또는 포켓몬을 먼저 선택하세요.");return;}SaveCurrent();list.Add(p);loading=true;FillPotentials(list);loading=false;tabs.SelectedIndex=2;dirty=true;UpdateTitle();}
  void AddPokemonSlots(){var list=CurrentPotentials();if(!(Current is PokemonRecord)){MessageBox.Show(this,"포켓몬을 선택한 뒤 사용하세요.");return;}SaveCurrent();foreach(var p in EditorTemplate.PokemonSlots())if(!list.Any(x=>x.slot==p.slot))list.Add(p);loading=true;FillPotentials(list);loading=false;dirty=true;tabs.SelectedIndex=2;UpdateTitle();}
  void AddOrders(bool deploy){if(!(Current is TrainerRecord)){MessageBox.Show(this,"트레이너를 선택한 뒤 사용하세요.");return;}SaveCurrent();var list=CurrentPotentials();foreach(var p in EditorTemplate.Orders(deploy))if(!list.Any(x=>x.name==p.name))list.Add(p);loading=true;FillPotentials(list);loading=false;dirty=true;tabs.SelectedIndex=2;UpdateTitle();}
  void AddAimOrders(){if(!(Current is TrainerRecord)){MessageBox.Show(this,"트레이너를 선택한 뒤 사용하세요.");return;}SaveCurrent();var list=CurrentPotentials();foreach(var p in EditorTemplate.AimOrders())if(!list.Any(x=>x.name==p.name))list.Add(p);loading=true;FillPotentials(list);loading=false;dirty=true;tabs.SelectedIndex=2;UpdateTitle();}
  void PastePotentials(){if(!Clipboard.ContainsText()){MessageBox.Show(this,"클립보드에 텍스트가 없습니다.");return;}string slot=Current is TrainerRecord?"고유":"계제";int added=0;foreach(string line in Clipboard.GetText().Replace("\r","").Split('\n'))if(line.Contains("『")&&line.Contains("』")){var p=EditorTemplate.Parse(line,slot);if(p.name.Length>0){AddPotential(p);added++;}}if(added==0)MessageBox.Show(this,"『이름』… 효과 형식의 줄을 찾지 못했습니다.");}
  void DeletePotential(){if(potentials.SelectedRows.Count==0)return;foreach(DataGridViewRow row in potentials.SelectedRows)if(!row.IsNewRow)potentials.Rows.Remove(row);GridChanged();}
  string Json(){SaveCurrent();return new JavaScriptSerializer{MaxJsonLength=50000000}.Serialize(project);}
  void Open(){if(!DiscardOkay())return;var d=new OpenFileDialog{Filter="AA Battle 데이터 (*.aabdata.json)|*.aabdata.json|JSON (*.json)|*.json"};if(d.ShowDialog(this)!=DialogResult.OK)return;try{project=new JavaScriptSerializer{MaxJsonLength=50000000}.Deserialize<EditorProject>(File.ReadAllText(d.FileName,Encoding.UTF8));if(project.trainers==null)project.trainers=new List<TrainerRecord>();if(project.pokemon==null)project.pokemon=new List<PokemonRecord>();path=d.FileName;dirty=false;RefreshTree(project.trainers.Cast<object>().Concat(project.pokemon).FirstOrDefault());}catch(Exception ex){MessageBox.Show(this,"파일을 열 수 없습니다.\r\n"+ex.Message,"열기 오류");}}
  void Save(){if(path.Length==0){SaveAs();return;}try{File.WriteAllText(path,Pretty(Json()),new UTF8Encoding(true));dirty=false;UpdateTitle();}catch(Exception ex){MessageBox.Show(this,ex.Message,"저장 오류");}}
  void SaveAs(){var d=new SaveFileDialog{Filter="AA Battle 데이터 (*.aabdata.json)|*.aabdata.json",FileName="battle-data.aabdata.json"};if(d.ShowDialog(this)!=DialogResult.OK)return;path=d.FileName;Save();}
  static string Pretty(string json){var sb=new StringBuilder();bool quoted=false,escape=false;int indent=0;foreach(char c in json){if(quoted){sb.Append(c);if(escape)escape=false;else if(c=='\\')escape=true;else if(c=='\"')quoted=false;continue;}if(c=='\"'){quoted=true;sb.Append(c);}else if(c=='{'||c=='['){sb.Append(c).AppendLine();indent++;sb.Append(new string(' ',indent*2));}else if(c=='}'||c==']'){sb.AppendLine();indent--;sb.Append(new string(' ',indent*2)).Append(c);}else if(c==','){sb.Append(c).AppendLine().Append(new string(' ',indent*2));}else if(c==':')sb.Append(": ");else if(!Char.IsWhiteSpace(c))sb.Append(c);}return sb.ToString();}
  bool DiscardOkay(){return !dirty||MessageBox.Show(this,"저장하지 않은 변경을 버릴까요?","변경 사항",MessageBoxButtons.YesNo)==DialogResult.Yes;}
  void UpdateTitle(){fileLabel.Text=(path.Length>0?Path.GetFileName(path):"새 데이터")+(dirty?" ＊":"");}
  void RefreshPreview(){SaveCurrent();preview.Text=Current is TrainerRecord?TrainerText((TrainerRecord)Current):Current is PokemonRecord?PokemonText((PokemonRecord)Current):"왼쪽에서 데이터를 선택하세요.";}
  static string PotentialText(IEnumerable<PotentialRecord> list){var sb=new StringBuilder();foreach(var p in list.Where(x=>x.enabled)){sb.Append("『").Append(p.name).Append("』…　");if(p.uses.Length>0)sb.Append(p.uses).Append('/');if(p.activation.Length>0)sb.Append(p.activation).Append('/');if(p.trigger.Length>0)sb.Append(p.trigger).Append("、");sb.AppendLine(p.effect.Length>0?p.effect:p.raw);}return sb.ToString();}
  static string TrainerText(TrainerRecord t){var a=new[]{t.command,t.training,t.leadership,t.ability};string[] n={"지시","육성","통솔","능력"};var sb=new StringBuilder("───────────────────────────────────────────────────\r\n【이름】 ").AppendLine(t.name).Append("【출신】 ").AppendLine(t.origin).AppendLine("\r\n【자질 평가】");for(int i=0;i<4;i++)sb.Append("ㆍ").Append(n[i]).Append("：「").Append(a[i].rank).Append("」　…　").AppendLine(a[i].description);sb.AppendLine("\r\n【지령 포텐셜】").Append(PotentialText(t.potentials.Where(x=>x.slot=="지령"))).AppendLine("\r\n【고유 포텐셜】").Append(PotentialText(t.potentials.Where(x=>x.slot!="지령")));return sb.ToString();}
  static string PokemonText(PokemonRecord p){var s=p.stats;return new StringBuilder("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\r\n【이름】 ").AppendLine(p.name).Append("【타입】 ").AppendLine(string.Join(" / ",p.types)).Append("【특성】 ").AppendLine(p.ability).Append("【모델】 《").Append(p.model).AppendLine("》").Append("【레벨】 ").AppendLine(p.level.ToString()).Append("【소지품】 ").AppendLine(p.item).Append("\r\n【기술 × ").Append(p.moves.Count).Append(" : ").Append(string.Join(", ",p.moves)).AppendLine("】\r\n").Append("체력 : ").AppendLine(s.hp.ToString()).Append("공격 : ").AppendLine(s.attack.ToString()).Append("방어 : ").AppendLine(s.defense.ToString()).Append("특공 : ").AppendLine(s.spAttack.ToString()).Append("특방 : ").AppendLine(s.spDefense.ToString()).Append("속도 : ").AppendLine(s.speed.ToString()).Append("총합 : ").AppendLine(s.Total().ToString()).AppendLine("\r\n○종족치 랭크 견본\r\nS…200~ / AAA…170~195 / AA…140~165 / A…110~135\r\nB…90~105 / C…60~85 / D…40~55 / E…1~35\r\n예: A+=135, A=111~134, A-=110 (각 랭크 ++ 상한은 제공 양식 참조)\r\n").AppendLine("【포텐셜】").Append(PotentialText(p.potentials.Where(x=>x.slot!="전용"))).AppendLine("\r\n＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿").Append(PotentialText(p.potentials.Where(x=>x.slot=="전용"))).AppendLine("전용 포텐셜\r\n＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿＿").ToString();}
  protected override void OnFormClosing(FormClosingEventArgs e){if(!allowClose&&!DiscardOkay())e.Cancel=true;base.OnFormClosing(e);}
  public void Sample(){var t=project.trainers[0];t.name="테스트 트레이너";t.origin="참치 지방";t.command.rank="B";t.potentials=EditorTemplate.Orders(false);var p=project.pokemon[0];p.name="테스트몬";p.types.AddRange(new[]{"전기","강철"});p.ability="부유";p.model="샘플";p.level=200;p.moves.AddRange(new[]{"10만볼트","방어","비바라기","볼트체인지"});p.stats=new StatsRecord{hp=100,attack=80,defense=100,spAttack=130,spDefense=100,speed=90};p.potentials=EditorTemplate.PokemonSlots();p.potentials[3].name="샘플의 전도";p.potentials[3].trigger="전기 기술이 명중했을 때";p.potentials[3].effect="상대의 특방을 1랭크 내린다.";RefreshTree(p);tabs.SelectedIndex=2;}
  public void SelectTabForTest(int index){tabs.SelectedIndex=index;if(index==3)RefreshPreview();Application.DoEvents();}
  public void CloseForTest(){allowClose=true;Close();}
 }

 static class DataEditorProgram {
  static void Check(bool ok,string label){if(!ok)throw new Exception("Data editor FAIL: "+label);}
  static void Capture(Form form,string path){using(var bitmap=new Bitmap(form.Width,form.Height)){form.DrawToBitmap(bitmap,new Rectangle(Point.Empty,bitmap.Size));bitmap.Save(path,System.Drawing.Imaging.ImageFormat.Png);}}
  [STAThread]public static int Main(string[] args){try{if(args.Length>0&&args[0]=="--self-test"){var p=new EditorProject();var t=new TrainerRecord{name="T"};t.potentials=EditorTemplate.Orders(false);p.trainers.Add(t);var mon=new PokemonRecord{name="P"};mon.potentials=EditorTemplate.PokemonSlots();p.pokemon.Add(mon);var j=new JavaScriptSerializer().Serialize(p);var q=new JavaScriptSerializer().Deserialize<EditorProject>(j);var parsed=EditorTemplate.Parse("『시험』… 1/시/선행/상대가 교대할 때, 자신의 속도를 올린다.","계제");Check(q.trainers.Count==1&&q.pokemon.Count==1,"roundtrip");Check(t.potentials.Count==10,"base four and six orders");Check(mon.potentials.Count==18,"pokemon slots");Check(parsed.name=="시험"&&parsed.uses.Length>0&&parsed.activation=="선행"&&parsed.trigger.Length>0&&parsed.effect.Length>0,"potential split");File.WriteAllText(args.Length>1?args[1]:"data-editor-test.txt","PASS: project roundtrip, trainer directives, pokemon slots, trigger/effect parser.");return 0;}Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);Fonts.Load();var form=new DataEditorForm();if(args.Length>1&&args[0]=="--render-preview"){form.Shown+=(s,e)=>{form.Sample();form.SelectTabForTest(2);Capture(form,args[1]);form.SelectTabForTest(1);Capture(form,args[1]+".pokemon.png");form.SelectTabForTest(3);Capture(form,args[1]+".sheet.png");form.CloseForTest();};}Application.Run(form);return 0;}catch(Exception ex){if(args.Length>0){File.WriteAllText(Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"data-editor-error.txt"),ex.ToString());return 1;}MessageBox.Show(ex.Message,"데이터 편집기 오류");return 1;}}
 }
}
