using System;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections.Generic;
using System.Drawing;
using System.Windows.Forms;

namespace AABattle {
 public static class EffectNormalizer {
  static readonly Regex Scalar=new Regex(@"(?<target>(?:자신|상대|아군)[^,.\n]*?)\s*(?:을|를|이|가)\s*(?<action>강화|약화|저하)\s*\(\s*(?<rate>[0-9]+(?:\.[0-9]+)?)\s*배\s*\)\s*(?:한다|시킨다|된다)",RegexOptions.Compiled);
  const string RankTarget=@"(?<target>.+?(?:전능력치|능력치|능력|「(?:공격|방어|특공|특방|속도|속|명중|회피|C|공/특공|방/특방|공격/특공|방어/특방)」|공격|방어|특공|특방|속도|명중|회피))";
  static readonly Regex RankUp=new Regex("^"+RankTarget+@"(?:을|를|이|가)\s*(?:(?<rank>[123])\s*랭크\s*)?(?<degree>매우 크게|크게)?\s*(?:올린다|오른다|상승시킨다|상승한다)$",RegexOptions.Compiled);
  static readonly Regex RankDown=new Regex("^"+RankTarget+@"(?:을|를|이|가)\s*(?:(?<rank>[123])\s*랭크\s*)?(?<degree>매우 크게|크게)?\s*(?:내린다|떨어진다|저하한다|하락한다|저하시킨다)$",RegexOptions.Compiled);
  public static string Normalize(string text){
   string clean=PotentialParts.Clean(text);
   clean=Regex.Replace(clean,@"임의의\s*능력치","임의의 능력");
   clean=Regex.Replace(clean,@"랜덤한\s*능력(?!치)","랜덤한 능력치");
   clean=Regex.Replace(clean,@"제일\s*(높은|낮은)\s*능력치?",m=>"가장 "+m.Groups[1].Value+" 능력");
   clean=Regex.Replace(clean,@"가장\s*(높은|낮은)\s*능력치",m=>"가장 "+m.Groups[1].Value+" 능력");
   var rank=RankUp.Match(clean);if(!rank.Success)rank=RankDown.Match(clean);if(rank.Success&&!rank.Groups["target"].Value.Contains("까지")){int amount=rank.Groups["rank"].Success?int.Parse(rank.Groups["rank"].Value):rank.Groups["degree"].Value=="매우 크게"?3:rank.Groups["degree"].Value=="크게"?2:1;return CanonicalRank(rank.Groups["target"].Value,RankDown.IsMatch(clean)?-amount:amount);}return Scalar.Replace(clean,m=>Canonical(m.Groups["target"].Value,m.Groups["action"].Value,double.Parse(m.Groups["rate"].Value,System.Globalization.CultureInfo.InvariantCulture)));
  }
  public static string NormalizeLines(string text){return string.Join("\r\n",(text??"").Replace("\r","").Split('\n').Select(Normalize).Where(x=>x.Length>0));}
  public static string Canonical(string target,string action,double rate){
   target=PotentialParts.Clean(target);string verb=action=="강화"?"강화":"약화";
   return target+Particle(target)+" "+verb+"("+rate.ToString("0.##",System.Globalization.CultureInfo.InvariantCulture)+"배)한다.";
  }
  public static string CanonicalRank(string target,int amount){target=PotentialParts.Clean(target);bool down=amount<0;amount=Math.Max(1,Math.Min(3,Math.Abs(amount)));return target+(down?Particle(target):SubjectParticle(target))+" "+(amount==3?"매우 크게 ":amount==2?"크게 ":"")+(down?"내린다.":"오른다.");}
  static string Particle(string value){if(string.IsNullOrEmpty(value))return "을";for(int i=value.Length-1;i>=0;i--){char c=value[i];if(c>='가'&&c<='힣')return ((c-'가')%28)==0?"를":"을";}return "을";}
  static string SubjectParticle(string value){if(string.IsNullOrEmpty(value))return "이";for(int i=value.Length-1;i>=0;i--){char c=value[i];if(c>='가'&&c<='힣')return ((c-'가')%28)==0?"가":"이";}return "이";}
  public static void Test(){
   if(Normalize("자신의 기술의 위력이 강화(1.50배)된다.")!="자신의 기술의 위력을 강화(1.5배)한다.")throw new Exception("Effect normalization failed");
   string weak=Normalize("상대의 「방어」를 저하(0.8배)시킨다.");if(weak!="상대의 「방어」를 약화(0.8배)한다.")throw new Exception("Effect weakening normalization failed: "+weak);
   if(Normalize("자신의 「공격」을 1랭크 올린다.").Contains("강화"))throw new Exception("Rank effect must stay distinct");
   if(Normalize("자신의 「공격」을 상승시킨다")!="자신의 「공격」이 오른다."||Normalize("자신의 「공격」을 크게 올린다")!="자신의 「공격」이 크게 오른다."||Normalize("자신의 「공격」을 3랭크 올린다")!="자신의 「공격」이 매우 크게 오른다.")throw new Exception("Rank wording normalization failed");
   if(Normalize("상대의 「방어」가 떨어진다")!="상대의 「방어」를 내린다."||Normalize("상대의 「방어」를 크게 내린다")!="상대의 「방어」를 크게 내린다."||Normalize("상대의 「방어」를 3랭크 내린다")!="상대의 「방어」를 매우 크게 내린다.")throw new Exception("Rank decrease normalization failed");
   if(Normalize("자신의 임의의 능력치를 올린다")!="자신의 임의의 능력이 오른다."||!Normalize("자신의 랜덤한 능력을 올린다").Contains("랜덤한 능력치"))throw new Exception("Stat choice wording normalization failed");
   if(Normalize("상대의 제일 높은 능력치를 내린다")!="상대의 가장 높은 능력을 내린다."||Normalize("자신의 가장 낮은 능력치를 올린다")!="자신의 가장 낮은 능력이 오른다.")throw new Exception("Extreme stat wording normalization failed");
  }
 }

 public static class PotentialStatRules {
  public static readonly string[] Arbitrary={"공격","방어","특공","특방","속도","명중","회피","C"};
  public static readonly string[] Random={"공격","방어","특공","특방","속도"};
  public static string ChooseRandom(Func<double> random){if(random==null)throw new ArgumentNullException("random");double roll=Math.Max(0,Math.Min(.999999999,random()));return Random[(int)(roll*Random.Length)];}
  public static int ExtremeIndex(int[] values,bool highest,Func<double> random){if(values==null||values.Length!=5)throw new ArgumentException("Five battle stat values are required","values");if(random==null)throw new ArgumentNullException("random");int extreme=highest?values.Max():values.Min();var tied=Enumerable.Range(0,5).Where(i=>values[i]==extreme).ToArray();double roll=Math.Max(0,Math.Min(.999999999,random()));return tied[(int)(roll*tied.Length)];}
  public static string ChooseExtreme(Fighter fighter,Fighter opponent,Rules rules,bool highest,Func<double> random){var values=Enumerable.Range(1,5).Select(i=>Engine.Effective(fighter,opponent,i,rules)).ToArray();return Random[ExtremeIndex(values,highest,random)];}
  public static string ChooseExtremeBase(Pokemon pokemon,bool highest,Func<double> random){if(pokemon==null||pokemon.@base==null||pokemon.@base.Length<6)throw new ArgumentException("Pokemon base stats are required","pokemon");return Random[ExtremeIndex(pokemon.@base.Skip(1).Take(5).ToArray(),highest,random)];}
  public static int CopyBase(Pokemon pokemon,int sourceIndex){if(pokemon==null||pokemon.@base==null||pokemon.@base.Length<6||sourceIndex<0||sourceIndex>5)throw new ArgumentException("Pokemon base stat source is required");return pokemon.@base[sourceIndex];}
  public static void Test(){var p=new Pokemon{@base=new[]{1,100,200,200,50,70}};if(Arbitrary.Length!=8||Arbitrary.Last()!="C"||Random.Length!=5||Random.Contains("명중")||ChooseRandom(()=>0)!="공격"||ChooseRandom(()=>.999)!="속도"||ExtremeIndex(new[]{100,200,200,50,70},true,()=>0)!=1||ExtremeIndex(new[]{100,200,200,50,50},true,()=>.999)!=2||ExtremeIndex(new[]{100,200,200,50,50},false,()=>.999)!=4||ChooseExtremeBase(p,true,()=>.999)!="특공"||CopyBase(p,4)!=50)throw new Exception("Potential stat selection rules failed");}
 }

 public static class SpeciesStatRanks {
  static readonly int[] Starts={1,40,60,90,110,140,170,200};
  public static readonly string[] Labels={"E-","E","E+","D-","D","D+","C-","C","C+","B-","B","B+","A-","A","A+","AA-","AA","AA+","AAA-","AAA","AAA+","S"};
  public static int[] RaisedRange(int value,int amount=1){int tier=Tier(value),modifier=Modifier(value,tier);int next=Math.Min(Starts.Length-1,tier+Math.Max(1,amount));if(next==Starts.Length-1)return new[]{200,999};int start=Starts[next],end=Starts[next+1]-1;if(modifier<0)return new[]{start,start};if(modifier>0)return new[]{end-4,end};return new[]{start+1,end-5};}
  static int Tier(int value){for(int i=Starts.Length-1;i>=0;i--)if(value>=Starts[i])return i;return 0;}
  static int Modifier(int value,int tier){if(tier>=Starts.Length-1)return 0;int start=Starts[tier],end=Starts[tier+1]-1;if(value==start)return -1;if(value>=end-4)return 1;return 0;}
  public static int[] LabelRange(string label){if(label=="S")return new[]{200,999};int modifier=label.EndsWith("-")?-1:label.EndsWith("+")?1:0;string core=label.TrimEnd('-','+');int tier=Array.IndexOf(new[]{"E","D","C","B","A","AA","AAA"},core);if(tier<0)throw new ArgumentException("Unknown species rank","label");int start=Starts[tier],end=Starts[tier+1]-1;if(modifier<0)return new[]{start,start};if(modifier>0)return new[]{end-4,end};return new[]{start+1,end-5};}
  public static void Test(){if(!RaisedRange(90).SequenceEqual(new[]{110,110})||!RaisedRange(100).SequenceEqual(new[]{111,134})||!RaisedRange(105).SequenceEqual(new[]{135,139})||!RaisedRange(135).SequenceEqual(new[]{165,169})||!RaisedRange(90,2).SequenceEqual(new[]{140,140})||!RaisedRange(105,2).SequenceEqual(new[]{165,169})||!LabelRange("A").SequenceEqual(new[]{111,134})||!LabelRange("AA+").SequenceEqual(new[]{165,169}))throw new Exception("Species stat rank ranges failed");}
 }

 public static class FractionalHpRule {
  public static int Amount(int maxHp,int denominator){if(denominator<1)throw new ArgumentOutOfRangeException("denominator");return Math.Max(1,maxHp/denominator);}
  public static int DamageHp(int currentHp,int maxHp,int denominator,bool canFaint){int left=currentHp-Amount(maxHp,denominator);return canFaint?Math.Max(0,left):Math.Max(1,left);}
  public static int HealHp(int currentHp,int maxHp,int denominator){return Math.Min(maxHp,currentHp+Amount(maxHp,denominator));}
  public static void Test(){if(Amount(101,4)!=25||DamageHp(10,100,4,true)!=0||DamageHp(10,100,4,false)!=1||HealHp(90,101,4)!=101)throw new Exception("Fractional HP rule failed");}
 }
 public static class EffectStructures {
  static readonly Regex Fraction=new Regex(@"^(?<target>자신|상대|아군 1체|아군 전체|아군)(?:의|에게)?\s*(?:(?:최대|전체)\s*)?체력(?:의|을|를|이|가)?\s*1/(?<n>[0-9]+)(?:만큼|을|를|의)?\s*(?<action>회복한다|회복시킨다|감소시킨다|감소한다|대미지를 준다|데미지를 준다)$",RegexOptions.Compiled);
  public static bool IsScalar(string text){string normalized=EffectNormalizer.Normalize(text);return Regex.IsMatch(PotentialParts.Clean(normalized),@"^(?:자신|상대|아군)[^,]*?\s*(?:을|를)\s*(?:강화|약화)\([0-9]+(?:\.[0-9]+)?배\)한다$");}
  public static bool IsRank(string text){return Regex.IsMatch(PotentialParts.Clean(EffectNormalizer.Normalize(text)),@"^.+?(?:(?:이|가)\s*(?:매우 크게 |크게 )?오른다|(?:을|를)\s*(?:매우 크게 |크게 )?내린다)$");}
  public static bool TryFraction(string text,out string target,out string action,out int denominator){var m=Fraction.Match(PotentialParts.Clean(text));target=action="";denominator=0;if(!m.Success)return false;target=m.Groups["target"].Value;action=m.Groups["action"].Value.Contains("회복")?"회복":"대미지";return int.TryParse(m.Groups["n"].Value,out denominator)&&denominator>0;}
  public static List<PotentialPart> Collapse(IEnumerable<PotentialPart> source){var input=source.Where(x=>!x.excludedFromImplementation).ToList();var result=new List<PotentialPart>();var scalar=input.Where(x=>!x.protectedTemplate&&IsScalar(x.text)).ToList();var fraction=input.Where(x=>!x.protectedTemplate&&TryFractionOnly(x.text)).ToList();var rank=input.Where(x=>!x.protectedTemplate&&IsRank(x.text)).ToList();var grouped=new HashSet<PotentialPart>(scalar.Concat(fraction).Concat(rank));result.AddRange(input.Where(x=>!grouped.Contains(x)));if(scalar.Count>0)result.Add(Template("scalar","수치 배율 — 대상 / 강화·약화 / 배율을 선택",scalar));if(fraction.Count>0)result.Add(Template("fraction","최대 HP의 1/N — 대상 / 회복·대미지 / 빈사 여부를 선택",fraction));if(rank.Count>0)result.Add(Template("rank","능력 랭크 변화 — 대상 / 상승·하락 / 1·2·3랭크를 선택",rank));return result.OrderBy(x=>x.text).ToList();}
  static bool TryFractionOnly(string text){string target,action;int n;return TryFraction(text,out target,out action,out n);}
  static PotentialPart Template(string kind,string text,List<PotentialPart> variants){var p=new PotentialPart{id="structure-"+kind,key="structure-"+kind,text=text,structureKind=kind,variantCount=variants.Count,searchText=string.Join(" ",variants.Select(x=>x.text))};foreach(var x in variants){foreach(var n in x.names)if(!p.names.Contains(n))p.names.Add(n);foreach(var s in x.sources)if(!p.sources.Contains(s))p.sources.Add(s);foreach(var r in x.raws)if(!p.raws.Contains(r))p.raws.Add(r);}return p;}
  public static void Test(){string target,action;int n;if(!TryFraction("자신의 체력을 1/4 회복한다",out target,out action,out n)||target!="자신"||action!="회복"||n!=4)throw new Exception("Fraction structure failed");var collapsed=Collapse(PotentialParts.Build(PotentialParts.StandardEntries()).effects);if(!collapsed.Any(x=>x.structureKind=="scalar")||!collapsed.Any(x=>x.structureKind=="fraction")||!collapsed.Any(x=>x.structureKind=="rank"))throw new Exception("Effect structure collapse failed");FractionalHpRule.Test();PotentialStatRules.Test();SpeciesStatRanks.Test();}
 }

 partial class DataEditorForm {
  static readonly string[] RankEffectTargets={"자신의 「공격」","자신의 「방어」","자신의 「특공」","자신의 「특방」","자신의 「속도」","자신의 「명중」","자신의 「회피」","자신의 「C」","자신의 임의의 능력","자신의 랜덤한 능력치","자신의 가장 높은 능력","자신의 가장 낮은 능력","자신의 전능력치","상대의 「공격」","상대의 「방어」","상대의 「특공」","상대의 「특방」","상대의 「속도」","상대의 「명중」","상대의 「회피」","상대의 「C」","상대의 임의의 능력","상대의 랜덤한 능력치","상대의 가장 높은 능력","상대의 가장 낮은 능력"};
  static readonly string[] SpeciesEffectTargets={"자신의 「체력」","자신의 「공격」","자신의 「방어」","자신의 「특공」","자신의 「특방」","자신의 「속도」"};
  static readonly string[] SpeciesGradeTargets=SpeciesEffectTargets.Concat(new[]{"자신의 「공/방」","자신의 「공/특공」","자신의 「방/특방」","자신의 「공/방/특공」","자신의 전종족치","상대의 「체력」","상대의 「공격」","상대의 「방어」","상대의 「특공」","상대의 「특방」","상대의 「속도」","상대의 「공/방」","상대의 「공/특공」","상대의 「방/특방」","상대의 전종족치"}).ToArray();
  ComboBox effectKind,effectAction,effectTarget,effectSpeciesRank,effectSpeciesSource;NumericUpDown effectRate,effectDenominator,effectSpeciesValue;CheckBox effectCanFaint;PixelText effectPreview;TableLayoutPanel effectTable,effectNumberPair;
  Panel BuildStructuredEffectPanel(){var panel=new Panel{Dock=DockStyle.Fill,Padding=new Padding(10)};var header=Theme.Label("효과 구조 · 원문 없이 값으로 구성",40);header.Dock=DockStyle.Top;var help=Theme.Label("구조를 고른 뒤 대상과 수치를 정합니다. 여러 효과는 효과 추가로 한 줄씩 저장합니다.",52);help.Dock=DockStyle.Top;help.ForeColor=Theme.Muted;var actions=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=42,FlowDirection=FlowDirection.LeftToRight,WrapContents=false};actions.Controls.Add(Button("구조 효과 입력",190,()=>ApplyPart(false)));actions.Controls.Add(Button("효과 추가 +",150,AppendConfiguredEffect));var builder=BuildInlineEffectBuilder();effectSubject=Theme.Combo(new[]{"자신","아군","상대"},"자신");effectSubject.SelectedIndexChanged+=(s,e)=>RefreshStructuredEffect();Theme.Row(effectTable,"효과 주체",effectSubject);builder.Dock=DockStyle.Top;panel.Controls.Add(builder);panel.Controls.Add(help);panel.Controls.Add(header);panel.Controls.Add(actions);return panel;}
  void AppendConfiguredEffect(){var row=SelectedPotentialRow();if(row==null){MessageBox.Show(this,"포텐셜 편집에서 입력할 행을 먼저 선택하세요.");return;}string effect=ConfiguredEffect();if(effect.Length==0)return;string current=Cell(row,"effect").Trim();loading=true;row.Cells["effect"].Value=current.Length==0?effect:current+"\r\n"+effect;loading=false;GridChanged();}
  Control BuildInlineEffectBuilder(){
   var panel=new Panel{Dock=DockStyle.Top,Height=436,Padding=new Padding(2)};effectTable=Theme.Table();effectTable.Dock=DockStyle.Fill;panel.Controls.Add(effectTable);
   effectKind=Theme.Combo(new[]{"능력 랭크 변화","종족치 변경","수치 배율","최대 HP의 1/N"},"능력 랭크 변화");effectKind.DropDownStyle=ComboBoxStyle.DropDown;effectKind.KeyPress+=(s,e)=>e.Handled=true;
   effectTarget=Theme.Combo(RankEffectTargets,"자신의 「공격」");effectTarget.DropDownStyle=ComboBoxStyle.DropDown;
   effectAction=Theme.Combo(new[]{"상승","하락"},"상승");effectAction.DropDownStyle=ComboBoxStyle.DropDown;effectAction.KeyPress+=(s,e)=>e.Handled=true;effectSpeciesRank=Theme.Combo(SpeciesStatRanks.Labels,"A");effectSpeciesRank.DropDownStyle=ComboBoxStyle.DropDown;effectSpeciesRank.KeyPress+=(s,e)=>e.Handled=true;effectSpeciesSource=Theme.Combo(new[]{"체력","공격","방어","특공","특방","속도"},"공격");effectSpeciesSource.DropDownStyle=ComboBoxStyle.DropDown;effectSpeciesSource.KeyPress+=(s,e)=>e.Handled=true;effectRate=new NumericUpDown{DecimalPlaces=2,Minimum=.01M,Maximum=10M,Increment=.05M,Value=1.5M,Dock=DockStyle.Fill,Font=new Font("맑은 고딕",10),BorderStyle=BorderStyle.FixedSingle};effectDenominator=new NumericUpDown{Minimum=1,Maximum=999,Value=1,Dock=DockStyle.Fill,Font=new Font("맑은 고딕",10),BorderStyle=BorderStyle.FixedSingle};effectSpeciesValue=new NumericUpDown{Minimum=1,Maximum=999,Value=110,Dock=DockStyle.Fill,Font=new Font("맑은 고딕",10),BorderStyle=BorderStyle.FixedSingle};effectCanFaint=new CheckBox{Text="이 대미지로 빈사 가능",Checked=true,Dock=DockStyle.Fill,Font=Theme.UI(8)};effectPreview=new PixelText{Dock=DockStyle.Fill};
   effectNumberPair=(TableLayoutPanel)Pair(effectRate,effectDenominator);Theme.Row(effectTable,"구조",effectKind);Theme.Row(effectTable,"대상",effectTarget);Theme.Row(effectTable,"종류",effectAction);Theme.Row(effectTable,"복사 원본",effectSpeciesSource);Theme.Row(effectTable,"수치",effectNumberPair);Theme.Row(effectTable,"종족치 등급",effectSpeciesRank);Theme.Row(effectTable,"설정 종족치",effectSpeciesValue);Theme.Row(effectTable,"빈사",effectCanFaint);Theme.Row(effectTable,"결과",effectPreview);
   EventHandler refresh=(s,e)=>RefreshStructuredEffect();effectKind.SelectedIndexChanged+=(s,e)=>{RefreshEffectActions();RefreshEffectTargets();RefreshSpeciesSources();RefreshStructuredEffect();};effectTarget.TextChanged+=(s,e)=>{RefreshSpeciesSources();RefreshStructuredEffect();};effectAction.SelectedIndexChanged+=(s,e)=>{RefreshEffectTargets();RefreshSpeciesSources();RefreshStructuredEffect();};effectSpeciesRank.SelectedIndexChanged+=refresh;effectSpeciesSource.SelectedIndexChanged+=refresh;effectRate.ValueChanged+=refresh;effectDenominator.ValueChanged+=refresh;effectSpeciesValue.ValueChanged+=refresh;effectCanFaint.CheckedChanged+=refresh;RefreshEffectActions();RefreshEffectTargets();RefreshSpeciesSources();RefreshStructuredEffect();return panel;
  }
  Control Pair(Control a,Control b){var row=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,Margin=Padding.Empty};row.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));row.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,50));row.Controls.Add(a,0,0);row.Controls.Add(b,1,0);return row;}
  void ShowEffectRow(Control control,bool shown,string label=null){if(effectTable==null||control==null)return;int row=effectTable.GetRow(control);effectTable.RowStyles[row].Height=shown?42:0;control.Visible=shown;var caption=effectTable.GetControlFromPosition(0,row);if(caption!=null){caption.Visible=shown;if(label!=null)caption.Text=label;}}
  bool GradeAction(){return effectAction.Text.StartsWith("지정 등급");}
  void RefreshEffectTargets(){if(effectKind==null||effectTarget==null)return;string[] choices=effectKind.Text=="종족치 변경"?(GradeAction()?SpeciesGradeTargets:SpeciesEffectTargets):effectKind.Text=="최대 HP의 1/N"?new[]{"자신","상대","아군 1체","아군 전체"}:effectKind.Text=="수치 배율"?RankEffectTargets.Concat(new[]{"자신의 기술의 위력","자신이 주는 대미지","자신이 받는 대미지","상대의 기술의 위력","상대가 주는 대미지","상대가 받는 대미지"}).ToArray():RankEffectTargets;string current=effectTarget.Text;if(effectTarget.Items.Cast<object>().Select(x=>x.ToString()).SequenceEqual(choices))return;effectTarget.Items.Clear();effectTarget.Items.AddRange(choices.Cast<object>().ToArray());effectTarget.SelectedItem=choices.Contains(current)?current:choices[0];}
  void RefreshEffectActions(){if(effectKind==null||effectAction==null)return;string[] choices=effectKind.Text=="종족치 변경"?new[]{"가장 높은 종족치 복사","가장 낮은 종족치 복사","다른 종족치 복사","1랭크 상승","2랭크 상승","지정 등급까지 상승","지정 등급까지 하락","지정 등급으로 변경","직접 수치 지정"}:effectKind.Text=="수치 배율"?new[]{"강화","약화"}:effectKind.Text=="최대 HP의 1/N"?new[]{"회복","대미지"}:new[]{"상승","하락"};string current=effectAction.Text;if(effectAction.Items.Cast<object>().Select(x=>x.ToString()).SequenceEqual(choices))return;effectAction.Items.Clear();effectAction.Items.AddRange(choices.Cast<object>().ToArray());effectAction.SelectedItem=choices.Contains(current)?current:choices[0];}
  void RefreshSpeciesSources(){if(effectSpeciesSource==null)return;string target=SpeciesEffectTargets.Select((x,i)=>new{value=x,index=i}).Where(x=>effectTarget.Text==x.value).Select(x=>new[]{"체력","공격","방어","특공","특방","속도"}[x.index]).FirstOrDefault();var choices=new[]{"체력","공격","방어","특공","특방","속도"}.Where(x=>x!=target).ToArray();string current=effectSpeciesSource.Text;if(!effectSpeciesSource.Items.Cast<object>().Select(x=>x.ToString()).SequenceEqual(choices)){effectSpeciesSource.Items.Clear();effectSpeciesSource.Items.AddRange(choices.Cast<object>().ToArray());effectSpeciesSource.SelectedItem=choices.Contains(current)?current:choices[0];}}
  int CurrentSpeciesValue(){var p=Current as PokemonRecord;if(p==null)return 0;var s=p.stats;if(effectTarget.Text.Contains("체력"))return s.hp;if(effectTarget.Text.Contains("공격"))return s.attack;if(effectTarget.Text.Contains("방어"))return s.defense;if(effectTarget.Text.Contains("특공"))return s.spAttack;if(effectTarget.Text.Contains("특방"))return s.spDefense;if(effectTarget.Text.Contains("속도"))return s.speed;return 0;}
  int SpeciesRaiseAmount(){return effectAction.Text=="2랭크 상승"?2:effectAction.Text=="1랭크 상승"?1:0;}
  void RefreshSpeciesRange(){int min=1,max=999,amount=SpeciesRaiseAmount();if(GradeAction()){var range=SpeciesStatRanks.LabelRange(effectSpeciesRank.Text);min=range[0];max=range[1];}else if(amount>0&&CurrentSpeciesValue()>0){var range=SpeciesStatRanks.RaisedRange(CurrentSpeciesValue(),amount);min=range[0];max=range[1];}effectSpeciesValue.Maximum=max;effectSpeciesValue.Minimum=min;if(effectSpeciesValue.Value<min)effectSpeciesValue.Value=min;if(effectSpeciesValue.Value>max)effectSpeciesValue.Value=max;}
  void RefreshStructuredEffect(){if(effectPreview==null)return;bool scalar=effectKind.Text=="수치 배율",fraction=effectKind.Text=="최대 HP의 1/N",rank=effectKind.Text=="능력 랭크 변화",species=effectKind.Text=="종족치 변경";int raise=SpeciesRaiseAmount();bool source=species&&effectAction.Text=="다른 종족치 복사",grade=species&&GradeAction(),value=species&&(raise>0||grade||effectAction.Text=="직접 수치 지정"),faint=fraction&&effectAction.Text=="대미지";ShowEffectRow(effectTarget,true);ShowEffectRow(effectAction,true);ShowEffectRow(effectSpeciesSource,source);ShowEffectRow(effectNumberPair,scalar||fraction||rank,scalar?"배율":fraction?"분모 N":"변화 랭크");ShowEffectRow(effectSpeciesRank,grade);ShowEffectRow(effectSpeciesValue,value);ShowEffectRow(effectCanFaint,faint);effectRate.Visible=scalar;effectDenominator.Visible=fraction||rank;effectNumberPair.ColumnStyles[0].Width=scalar?100:0;effectNumberPair.ColumnStyles[1].Width=scalar?0:100;if(species){RefreshSpeciesRange();string target=effectTarget.Text+" 종족치";if(effectAction.Text=="가장 높은 종족치 복사")effectPreview.Text=target+"를 가장 높은 종족치로 한다.";else if(effectAction.Text=="가장 낮은 종족치 복사")effectPreview.Text=target+"를 가장 낮은 종족치로 한다.";else if(effectAction.Text=="다른 종족치 복사")effectPreview.Text=target+"를 자신의 「"+effectSpeciesSource.Text+"」 종족치와 같게 한다.";else if(raise>0&&CurrentSpeciesValue()<=0)effectPreview.Text="포켓몬과 대상 종족치를 먼저 설정하세요.";else if(raise>0)effectPreview.Text=target+"를 「"+(int)effectSpeciesValue.Value+"」로 하여 "+raise+"랭크 올린다.";else if(effectAction.Text=="지정 등급까지 상승")effectPreview.Text=target+"를 「"+effectSpeciesRank.Text+"」 범위의 「"+(int)effectSpeciesValue.Value+"」까지 올린다.";else if(effectAction.Text=="지정 등급까지 하락")effectPreview.Text=target+"를 「"+effectSpeciesRank.Text+"」 범위의 「"+(int)effectSpeciesValue.Value+"」까지 내린다.";else if(effectAction.Text=="지정 등급으로 변경")effectPreview.Text=target+"를 「"+effectSpeciesRank.Text+"」 범위의 「"+(int)effectSpeciesValue.Value+"」로 한다.";else effectPreview.Text=target+"를 「"+(int)effectSpeciesValue.Value+"」로 한다.";}else if(scalar){effectPreview.Text=EffectNormalizer.Canonical(effectTarget.Text,effectAction.Text=="약화"?"약화":"강화",(double)effectRate.Value);}else if(fraction){string target=new[]{"자신","상대","아군 1체","아군 전체"}.Contains(effectTarget.Text)?effectTarget.Text:"자신";int n=(int)effectDenominator.Value;effectPreview.Text=effectAction.Text=="대미지"?target+"에게 최대 HP의 1/"+n+" 대미지를 준다."+(effectCanFaint.Checked?"":" 이 대미지로는 빈사로 할 수 없다."):target+"의 체력을 최대 HP의 1/"+n+" 회복한다.";}else if(rank){if(effectDenominator.Value>3)effectDenominator.Value=3;effectPreview.Text=EffectNormalizer.CanonicalRank(effectTarget.Text,(effectAction.Text=="하락"?-1:1)*(int)effectDenominator.Value);}else effectPreview.Text="";effectKind.Invalidate();effectAction.Invalidate();}
  string ConfiguredEffect(){string value=effectPreview==null?"":effectPreview.Text;if(effectSubject==null||effectSubject.Text=="자신")return value;string owner=effectSubject.Text;value=Regex.Replace(value,@"^자신의",owner+"의");value=Regex.Replace(value,@"^자신이",owner+(owner=="아군"?"이":"가"));value=Regex.Replace(value,@"^자신에게",owner+"에게");return value;}
 }
}
