from pathlib import Path
p=Path(__file__).with_name('BattleApp.cs');s=p.read_text(encoding='utf-8-sig')
start=s.index(' class RulesForm:Form {');end=s.index(' static class Program {',start);s=s[:start]+s[end:]
s=s.replace('public FlatButton Edit;double hpRatio=1;','public FlatButton Edit,State;public Label StateLine;double hpRatio=1;')
s=s.replace('Art=new AAView();Controls.AddRange(new Control[]{Title,Meta,HP,Edit,Art});','State=new FlatButton{Text="상태",Font=Theme.UI(8)};StateLine=new PixelLabel{Font=Theme.UI(8),BackColor=Color.White};Art=new AAView();Controls.AddRange(new Control[]{Title,Meta,HP,Edit,State,StateLine,Art});')
s=s.replace('Title.SetBounds(23,20,Width-110,30);','Title.SetBounds(23,20,Width-165,30);State.SetBounds(Width-136,20,53,30);')
s=s.replace('Art.SetBounds(18,114,Width-40,Height-140);','StateLine.SetBounds(25,103,Width-52,25);Art.SetBounds(18,137,Width-40,Height-164);')
s=s.replace('public class Snapshot','public class Snapshot')
s=s.replace('class Snapshot {public Fighter[] Fighters;','class Snapshot {public Rules Rules;public Fighter[] Fighters;')
s=s.replace('FlatButton calculate,settings,results,reset,back;Label brand,turnLabel,status;','FlatButton calculate,settings,results,reset,back,guide;Label brand,turnLabel,status,fieldLabel;ToolTip hints=new ToolTip{AutoPopDelay=15000,InitialDelay=300};')
s=s.replace('Text="AA BATTLE · MONO EDITION"','Text="AA BATTLE · 상태 규칙 빌드 0.4"')
s=s.replace('Controls.AddRange(new Control[]{brand,turnLabel,status,settings,results,reset,back,calculate});','guide=new FlatButton{Text="배틀 규칙",Font=Theme.UI(9)};fieldLabel=new PixelLabel{Font=Theme.UI(9),TextAlign=ContentAlignment.MiddleCenter};guide.Click+=(s,e)=>{using(var g=new GuideForm(db))g.ShowDialog(this);};Controls.AddRange(new Control[]{brand,turnLabel,status,fieldLabel,guide,settings,results,reset,back,calculate});')
s=s.replace('cards[i].Edit.Click+=(s,e)=>Edit(side);','cards[i].Edit.Click+=(s,e)=>Edit(side);cards[i].State.Click+=(s,e)=>EditConditions(side);')
s=s.replace('Rules=dialog.Value;for(int i=0;','Save();Rules=dialog.Value;for(int i=0;')
s=s.replace('Fighters[i].Stages=new int[6];}turn=1;','Fighters[i].Stages=new int[6];Fighters[i].Status="정상";Fighters[i].Conditions=new ConditionState();}Rules.Weather="없음";Rules.Terrain="없음";Rules.TrickRoom=Rules.Gravity=0;turn=1;')
s=s.replace('top=91,moveHeight','top=121,moveHeight')
s=s.replace('brand.SetBounds(margin,25,200,28);','brand.SetBounds(margin,25,180,28);guide.SetBounds(margin+170,22,110,32);fieldLabel.SetBounds(margin,69,ClientSize.Width-margin*2,30);')
s=s.replace('Fighters=Fighters.Select(f=>f.Copy()).ToArray(),Turn=turn,Log=log','Fighters=Fighters.Select(f=>f.Copy()).ToArray(),Rules=Rules.Copy(),Turn=turn,Log=log')
s=s.replace('Fighters=s.Fighters;turn=s.Turn;','Fighters=s.Fighters;Rules=s.Rules;turn=s.Turn;')
s=s.replace('  void Battle(){','  void EditConditions(int side){using(var dialog=new ConditionsForm(db,Fighters[side],Fighters[1-side],Rules)){if(dialog.ShowDialog(this)==DialogResult.OK){Save();Fighters[side]=dialog.Value;RefreshView();}}}\n  void Battle(){')
s=s.replace('Fighters=result.Fighters;turn++;','Fighters=result.Fighters;Rules=result.Rules;turn++;')
s=s.replace('moveCards[i].RefreshMoves(Fighters[i],db);','moveCards[i].RefreshMoves(Fighters[i],db);cards[i].StateLine.Text=RuleBook.Summary(Fighters[i],Fighters[1-i],Rules);hints.SetToolTip(cards[i].StateLine,cards[i].StateLine.Text);for(int j=0;j<Fighters[i].Moves.Length;j++){var m=db.moves.FirstOrDefault(v=>v.name==Fighters[i].Moves[j]);if(m==null)continue;string block=Mechanics.TargetsOpponent(m)?Mechanics.Block(db,Fighters[i],Fighters[1-i],m,Rules):"";var button=moveCards[i].Buttons[j];button.Subtext=string.Join("/",m.types)+" / "+(block.Length>0?"무효":m.category=="변화"?(Mechanics.KnownMove(m)&&m.name!="날개쉬기"?"상태 적용":"수동 판정"):"상성 ×"+Mechanics.TypeEffect(db,Fighters[i],Fighters[1-i],m,Rules));hints.SetToolTip(button,(block.Length>0?block+"\\n":"")+m.effect+"\\n등록된 효과 외에는 수동 판정입니다.");button.Invalidate();}')
s=s.replace('turnLabel.Text="TURN  "+turn.ToString("00");','fieldLabel.Text=RuleBook.Field(Rules,Fighters);turnLabel.Text="TURN  "+turn.ToString("00");')
s=s.replace('기본 대미지 계산 · 부가 효과와 포텐셜은 수동 판정','대미지 / 무효 사유 / 상태 처리 / 턴 종료 효과')
s=s.replace('TextBox name,aa;','TextBox name,aa,ability,item;')
s=s.replace('status=Theme.Combo(new[]{"정상","화상","동상"},Value.Status);','status=Theme.Combo(Mechanics.Statuses,Value.Status);status.Enabled=false;ability=new TextBox{Dock=DockStyle.Fill,Font=new Font("맑은 고딕",10)};item=new TextBox{Dock=DockStyle.Fill,Font=new Font("맑은 고딕",10)};')
s=s.replace('Theme.Row(table,"상태",status);','Theme.Row(table,"상태 (상태 창)",status);Theme.Row(table,"특성",ability);Theme.Row(table,"소지품",item);')
s=s.replace('특성·소지품·포텐셜 효과는 자동 적용하지 않습니다.','등록된 특성·도구만 적용. 배틀 규칙에서 확인하세요.')
s=s.replace('status.SelectedItem=Value.Status;aa.Text=Value.AA;','status.SelectedItem=Value.Status;ability.Text=Value.Data.ability;item.Text=Value.Data.item;aa.Text=Value.AA;')
s=s.replace('Value.Data.name=name.Text.Trim();','Value.Data.ability=ability.Text.Trim();Value.Data.item=item.Text.Trim();Value.Data.name=name.Text.Trim();')
s=s.replace('File.WriteAllText(args.Length>1?args[1]:"self-test.txt",Engine.Test(db));','File.WriteAllText(args.Length>1?args[1]:"self-test.txt",Engine.Test(db)+"\\r\\n"+MechanicsTests.Run(db));')
s=s.replace('form.Smoke();Capture(form,args[1]);','form.Smoke();Capture(form,args[1]);using(var conditions=new ConditionsForm(db,form.Fighters[0],form.Fighters[1],form.Rules)){conditions.Show();Capture(conditions,args[1]+".conditions.png");conditions.Close();}using(var guide=new GuideForm(db)){guide.Show();Capture(guide,args[1]+".guide.png");guide.Close();}')
p.write_text(s,encoding='utf-8-sig')
