using System;
using System.Linq;
using System.Collections.Generic;
namespace AABattle {
 public static class MechanicsTests {
  static int count;
  static void Check(bool value,string name){if(!value)throw new Exception("Mechanics FAIL: "+name);count++;}
  static Fighter F(string type="노말"){return new Fighter(new Pokemon{name="TEST",level=100,types=new[]{type},ability="",item="",@base=new[]{100,100,100,100,100,100},iv=new[]{31,31,31,31,31,31},moves=new[]{"몸통박치기"}});}
  static Move M(string type="노말",string name="몸통박치기",string category="물리"){return new Move{name=name,category=category,types=new[]{type},tags=new string[0],power=80,accuracy=100,attack="공격",defense="방어"};}
  public static string Run(Database db){count=0;var a=F();var b=F();var r=new Rules();var log=new List<string>();
   string[] attack={"노말","격투","독","땅","고스트","전기","에스퍼","드래곤"},defend={"고스트","고스트","강철","비행","노말","땅","악","페어리"};
   for(int i=0;i<attack.Length;i++){b=F(defend[i]);Check(Engine.Calculate(db,a,b,M(attack[i]),r).Max==0,"type immunity "+attack[i]);}
   b=F("불꽃");Check(Mechanics.StatusBlock(b,a,"화상",r)!="","fire burn immunity");b=F("전기");Check(Mechanics.StatusBlock(b,a,"마비",r)!="","electric paralysis immunity");b=F("강철");Check(Mechanics.StatusBlock(b,a,"맹독",r)!="","steel toxic immunity");a.Data.ability="부식";Check(Mechanics.StatusBlock(b,a,"맹독",r)=="","corrosion");a=F();b=F("얼음");Check(Mechanics.StatusBlock(b,a,"얼음",r)!="","ice freeze immunity");
   b=F();b.Status="독";Check(!Mechanics.ApplyStatus(b,a,"마비",r,()=>.5,log)&&b.Status=="독","one major status");b=F("풀");Check(Mechanics.Block(db,a,b,M("풀","버섯포자","변화"),r)!="","powder immunity");
   b=F();b.Data.ability="부유";Check(Mechanics.Block(db,a,b,M("땅"),r)!="","levitate");a.Data.ability="틀깨기";Check(Mechanics.Block(db,a,b,M("땅"),r)=="","mold breaker levitate");b.Data.item="풍선";Check(Mechanics.Block(db,a,b,M("땅"),r)!="","mold breaker cannot bypass balloon");r.Gravity=5;Check(Mechanics.Block(db,a,b,M("땅"),r)=="","gravity grounding");r=new Rules();a=F();b=F("땅");b.Data.ability="피뢰침";string reason=Mechanics.Block(db,a,b,M("전기"),r);Mechanics.Absorb(a,b,reason,r,log);Check(b.Stages[3]==1,"lightningrod ground absorbs");
   b=F();b.Data.ability="저수";b.HP-=100;int hp=b.HP;Mechanics.Absorb(a,b,Mechanics.Block(db,a,b,M("물"),r),r,log);Check(b.HP>hp,"water absorb heals");
   a=F();b=F("바위");r.Weather="모래바람";Check(Mechanics.StatFactor(b,a,4,r)==1.5,"sand rock spdef");int max=Engine.Stats(a,100,r)[0];hp=a.HP;Mechanics.EndTurn(new[]{a,b},r,log);Check(a.HP==hp-max/16&&b.HP==max,"sand chip and rock immunity");r.Weather="눈";b=F("얼음");Check(Mechanics.StatFactor(b,a,2,r)==1.5,"snow ice defense");hp=a.HP;Mechanics.EndTurn(new[]{a,b},r,log);Check(a.HP==hp,"snow no chip");
   r.Weather="큰가뭄";Check(Engine.Calculate(db,a,b,M("물"),r).Max==0,"harsh sun fails water");r.Weather="강한 비";Check(Engine.Calculate(db,a,b,M("불꽃"),r).Max==0,"heavy rain fails fire");b.Data.ability="날씨부정";Check(Mechanics.Weather(a,b,r)=="없음"&&Mechanics.Block(db,a,b,M("불꽃"),r)=="","weather suppression");
   r=new Rules{Terrain="일렉트릭필드"};a=F();b=F();Check(Mechanics.PowerFactor(a,b,M("전기"),r)==1.3,"modern terrain boost");a.Data.types=new[]{"비행"};Check(Mechanics.PowerFactor(a,b,M("전기"),r)==1,"airborne terrain no boost");Check(Mechanics.StatusBlock(b,a,"잠듦",r)!="","electric terrain sleep prevention");r.Terrain="미스트필드";Check(Mechanics.PowerFactor(b,a,M("페어리"),r)==1,"misty no fairy boost");Check(Mechanics.PowerFactor(a,b,M("드래곤"),r)==.5,"misty grounded dragon reduction");Check(Mechanics.StatusBlock(a,b,"독",r)=="","airborne misty unprotected");r.Terrain="사이코필드";var priority=M();priority.priority=1;Check(Mechanics.Block(db,a,b,priority,r)!="","psychic priority prevention");
   r=new Rules();a=F();b=F();b.Conditions.Reflect=5;Check(Mechanics.DamageFactor(a,b,M(),r)==.5,"reflect");r.Critical=true;Check(Mechanics.DamageFactor(a,b,M(),r)==1,"critical ignores screen");r.Critical=false;a.Status="마비";Check(Mechanics.StatFactor(a,b,5,r)==.5,"paralysis speed");Check(!Mechanics.BeforeMove(a,b,M(),r,()=>0,log),"full paralysis");a.Status="잠듦";a.Conditions.SleepTurns=1;Check(!Mechanics.BeforeMove(a,b,M(),r,()=>.9,log),"sleep blocks");Check(Mechanics.BeforeMove(a,b,M(),r,()=>.9,log)&&a.Status=="정상","sleep wakes");a.Status="얼음";Check(Mechanics.BeforeMove(a,b,M(),r,()=>.1,log)&&a.Status=="정상","freeze thaws");a.Conditions.Confusion=2;hp=a.HP;Check(!Mechanics.BeforeMove(a,b,M(),r,()=>0,log)&&a.HP<hp,"confusion self hit");a.Conditions.Confusion=0;a.Conditions.Recharge=true;Check(!Mechanics.BeforeMove(a,b,M(),r,()=>.9,log)&&!a.Conditions.Recharge,"recharge expires");
   a=F();b=F();a.Status="맹독";hp=a.HP;Mechanics.EndTurn(new[]{a,b},r,log);Check(a.HP==hp-max/16&&a.Conditions.ToxicStage==2,"toxic first tick");hp=a.HP;Mechanics.EndTurn(new[]{a,b},r,log);Check(a.HP==hp-(int)Math.Floor(max*2/16.0),"toxic escalation");a=F();a.Data.ability="매직가드";a.Status="독";hp=a.HP;Mechanics.EndTurn(new[]{a,b},r,log);Check(a.HP==hp,"magic guard indirect");a=F();a.HP=1;a.Data.item="먹다남은음식";r.Weather="모래바람";Mechanics.EndTurn(new[]{a,b},r,log);Check(a.HP==0,"no revival from residual healing");
   r=new Rules{Weather="비",WeatherTurns=1,Terrain="미스트필드",TerrainTurns=1,Gravity=1,TrickRoom=1};a=F();b=F();Mechanics.EndTurn(new[]{a,b},r,log);Check(r.Weather=="없음"&&r.Terrain=="없음"&&r.Gravity==0&&r.TrickRoom==0,"field expiration");r.Weather="비";r.WeatherTurns=0;Mechanics.EndTurn(new[]{a,b},r,log);Check(r.Weather=="비","permanent weather");
   r=new Rules();var protect=M("노말","방어","변화");protect.priority=4;var t=Engine.Resolve(db,new[]{a,b},new[]{protect,M()},r,()=>.5);Check(t.Fighters[0].HP==a.HP&&!t.Fighters[0].Conditions.Protect,"protect blocks and clears");Check(a.Conditions.ProtectChain==0&&t.Fighters[0].Conditions.ProtectChain==1,"deep condition clone");a.Conditions.ProtectChain=1;Mechanics.StatusMove(a,b,protect,r,()=>.9,log);Check(a.Conditions.ProtectChain==0,"protect failure resets chain");a=F();b=F();b.Conditions.Substitute=1;var hit=M();hit.priority=2;var pass=M("ノーマル","未登録","변화");t=Engine.Resolve(db,new[]{a,b},new[]{hit,pass},r,()=>.5);Check(t.Fighters[1].HP==b.HP&&t.Fighters[1].Conditions.Substitute==0,"substitute no spill");r.Weather="비";r.WeatherTurns=3;t=Engine.Resolve(db,new[]{a,b},new[]{pass,pass},r,()=>.5);Check(r.WeatherTurns==3&&t.Rules.WeatherTurns==2,"rules isolation");
   a=F();b=F();a.Stages[5]=6;b.HP=1;a.HP=1;r=new Rules{TrickRoom=3};t=Engine.Resolve(db,new[]{a,b},new[]{M(),M()},r,()=>.5);Check(t.Fighters[0].HP==0&&t.Fighters[1].HP==1,"trick room order");hit=M();hit.priority=1;t=Engine.Resolve(db,new[]{a,b},new[]{hit,M()},r,()=>.5);Check(t.Fighters[1].HP==0,"priority precedes trick room");
   var record=new PokemonRecord{name="편집몬",level=100};record.types.Add("노말");record.moves.Add(db.moves[0].name);record.stats=new StatsRecord{hp=100,attack=100,defense=100,spAttack=100,spDefense=100,speed=100};string bridgeWarning;var bridged=EditorBridge.ToPokemon(record,db,out bridgeWarning);var bridgedFighter=new Fighter(bridged);Check(bridged.@base.All(x=>x==100)&&bridged.iv.All(x=>x==31),"editor base stats and default IV");Check(Engine.Stats(bridgedFighter,100,new Rules())[0]==341&&Engine.Stats(bridgedFighter,100,new Rules())[1]==236,"base stats convert to battle stats");Check(bridgeWarning=="","editor bridge known data");
   record.potentials.Add(new PotentialRecord{enabled=false,name="발동 금지",effect="절대 실행되지 않는다."});record.potentials.Add(new PotentialRecord{enabled=true,name="발동 허용",effect="실행 후보다."});bridged=EditorBridge.ToPokemon(record,db,out bridgeWarning);Check(bridged.potentials.Length==1&&bridged.potentials[0].name=="발동 허용","disabled potential excluded from battle");
   return "PASS: "+count+" mechanics regression checks.";
  }
 }
}
