using System;
using System.Linq;

namespace AABattle {
 static class SwitchRuntimeTests {
  static void Check(bool ok,string label){if(!ok)throw new Exception("Switch runtime FAIL: "+label);}
  static Fighter Tracker(Fighter source){var p=source.Data;return new Fighter(new Pokemon{id="tracker",name="추적대원 보유자",level=p.level,@base=(int[])p.@base.Clone(),iv=(int[])p.iv.Clone(),types=(string[])p.types.Clone(),moves=(string[])p.moves.Clone(),potentials=new[]{new Potential{id="역할",name="추적대원",description=EffectNormalizer.CanonicalSwitchRestriction(),triggers=new[]{TriggerStructures.FieldLabel}}}});}
  public static void Run(Database db){
   var user=new Fighter(db.pokemon.First(p=>p.name=="선데이"));var target=new Fighter(db.pokemon.First(p=>p.name=="잭 한마"));var protect=db.moves.First(v=>v.name=="방어");var pivotMove=db.moves.First(v=>v.name=="유턴");var pivotReserve=new Fighter(db.pokemon.First(p=>p.name=="테스트2"));var wait=new Move{name="대기",category="변화",types=new[]{"노말"},accuracy=100,target="자신"};var pivot=Engine.Resolve(db,new[]{user,target},new[]{new BattleCommand{Move=pivotMove,Party=new[]{pivotReserve,user.Copy()}},new BattleCommand{Move=wait}},new Rules(),new[]{new TrainerBattleState(),new TrainerBattleState()},()=>0,x=>x.Candidates.First());Check(pivot.Fighters[0].Data.name==pivotReserve.Data.name&&pivot.Switches.Any(x=>x.Reason==SwitchReason.Pivot&&x.Timing==SwitchTiming.MidTurn),"pivot move switches during the turn: "+string.Join(" / ",pivot.Log));
   var tracker=Tracker(target);Check(SwitchEffectRuntime.HasSwitchRestriction(tracker),"tracker field restriction active");Check(SwitchEffectRuntime.CanSwitch(tracker,SwitchReason.Normal)&&SwitchEffectRuntime.CanSwitch(tracker,SwitchReason.Return)&&SwitchEffectRuntime.CanSwitch(tracker,SwitchReason.Forced),"normal, return and forced switches remain allowed");Check(!SwitchEffectRuntime.CanSwitch(tracker,SwitchReason.Pivot)&&!SwitchEffectRuntime.CanSwitch(tracker,SwitchReason.Potential),"pivot and potential switches are restricted");var blocked=Engine.Resolve(db,new[]{user.Copy(),tracker},new[]{new BattleCommand{Move=pivotMove,Party=new[]{pivotReserve,user.Copy()}},new BattleCommand{Move=wait}},new Rules(),new[]{new TrainerBattleState(),new TrainerBattleState()},()=>0,x=>x.Candidates.First());Check(blocked.Fighters[0].Data.name==user.Data.name&&!blocked.Switches.Any(x=>x.Reason==SwitchReason.Pivot)&&blocked.Log.Any(x=>x.Contains("교대 제한 효과")),"tracker blocks pivot switch");
   var reaction=new Fighter(new Pokemon{id="reaction",name="피격 교대",level=user.Data.level,@base=(int[])user.Data.@base.Clone(),iv=(int[])user.Data.iv.Clone(),types=(string[])user.Data.types.Clone(),moves=(string[])user.Data.moves.Clone(),potentials=new[]{new Potential{name="피격 교대",description="아군과 교대할 수 있다.",triggers=new[]{TriggerStructures.ReceivedLabel}}}});var reactionReserve=new Fighter(db.pokemon.First(p=>p.name=="테스트2"));var tap=new Move{name="약한공격",category="물리",types=new[]{"노말"},power=1,accuracy=100,priority=7,attack="공격",defense="방어"};var reactionResult=Engine.Resolve(db,new[]{user.Copy(),reaction},new[]{new BattleCommand{Move=tap},new BattleCommand{Move=protect,Party=new[]{reactionReserve,reaction.Copy()}}},new Rules(),new[]{new TrainerBattleState(),new TrainerBattleState()},()=>0,x=>x.Candidates.First());Check(reactionResult.Fighters[1].Data.name==reactionReserve.Data.name&&reactionResult.Switches.Any(x=>x.Reason==SwitchReason.Potential&&x.Timing==SwitchTiming.MidTurn),"mid-turn potential switch");
   var ending=new Fighter(new Pokemon{id="ending",name="턴 종료 교대",level=user.Data.level,@base=(int[])user.Data.@base.Clone(),iv=(int[])user.Data.iv.Clone(),types=(string[])user.Data.types.Clone(),moves=(string[])user.Data.moves.Clone(),potentials=new[]{new Potential{name="턴 종료 교대",description="아군과 교대할 수 있다.",triggers=new[]{TriggerStructures.TurnEndLabel}}}});var endingReserve=new Fighter(db.pokemon.First(p=>p.name=="테스트2"));var endingResult=Engine.Resolve(db,new[]{user.Copy(),ending},new[]{new BattleCommand{Move=protect},new BattleCommand{Move=protect,Party=new[]{endingReserve,ending.Copy()}}},new Rules(),new[]{new TrainerBattleState(),new TrainerBattleState()},()=>0,x=>x.Candidates.First());Check(endingResult.Fighters[1].Data.name==endingReserve.Data.name&&endingResult.Switches.Any(x=>x.Reason==SwitchReason.Potential&&x.Timing==SwitchTiming.TurnEnd),"turn-end potential switch");
  }
 }
}
